// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

export interface AIProviderConfig {
	id?: string // For custom providers
	name?: string // Provider display name
	base_url?: string // API base URL for custom providers
	api_key?: string
	enabled: boolean
}

export interface AcceptCustomQuoteRequest {
}
export interface AcceptCustomQuoteRequestParams {
}

export interface ActionParamInfo {
	name: string
	type: string
	description: string
	required: boolean
	options?: Array<string>
	default?: string
}

export interface ActionTypeInfo {
	id: string
	name: string
	description: string
	category: string
	icon: string
	params: Array<ActionParamInfo>
	ai_managed: boolean
}

export interface AddContactTagsRequest {
	tags: Array<string>
}
export interface AddContactTagsRequestParams {
}

export interface AddCustomerNoteRequest {
	note: string
}
export interface AddCustomerNoteRequestParams {
}

export interface AddCustomerNoteResponse {
	success: boolean
	message: string
}

export interface AddLeadTagRequest {
	tag: string
}
export interface AddLeadTagRequestParams {
}

export interface AddTicketMessageRequest {
	message: string
	attachments?: Array<string>
}
export interface AddTicketMessageRequestParams {
}

export interface AddTicketMessageResponse {
	success: boolean
	message: TicketMessageInfo
}

export interface AdminAnalyticsResponse {
	topPages: Array<AdminTopPage>
	topReferrers: Array<AdminTopReferrer>
}

export interface AdminCancelSubscriptionRequest {
	immediately?: boolean
	reason?: string
}
export interface AdminCancelSubscriptionRequestParams {
}

export interface AdminCancelSubscriptionResponse {
	success: boolean
	message: string
}

export interface AdminContact {
	id: number
	name: string
	email: string
	subject: string
	message: string
	source: string
	createdAt: string
	read: boolean
}

export interface AdminContactsResponse {
	contacts: Array<AdminContact>
	total: number
}

export interface AdminExtendSubscriptionRequest {
	days: number
}
export interface AdminExtendSubscriptionRequestParams {
}

export interface AdminExtendSubscriptionResponse {
	success: boolean
	message: string
}

export interface AdminStatsResponse {
	totalContacts: number
	unreadContacts: number
	totalSubscribers: number
	pageViewsToday: number
	pageViewsWeek: number
}

export interface AdminTopPage {
	page: string
	views: number
}

export interface AdminTopReferrer {
	referrer: string
	views: number
}

export interface AgentActionLogEntry {
	id: string
	org_id: string
	action_type: string
	domain: string
	description: string
	context?: string // JSON context data
	result?: string // JSON result data
	status: string // pending, approved, executed, rejected
	approved_by?: string
	executed_at?: string
	created_at: string
}

export interface AgentConfigInfo {
	id: string
	org_id: string
	enabled: boolean
	global_autonomy_level: number // 0-100, affects all domains
	domain_configs: Array<AgentDomainConfig>
	system_prompt?: string // Base system prompt
	max_actions_per_hour: number
	require_approval: Array<string> // Action types requiring approval
	notify_on_action: boolean
	model_tier: string // LLM model tier (standard, advanced, fast)
	created_at: string
	updated_at: string
}

export interface AgentDomainConfig {
	domain: string // support, billing, email, customer, orders, disputes
	enabled: boolean
	autonomy_level: number // 0-100
	prompt?: string // Optional custom prompt override
}

export interface AgentPromptInfo {
	id: string
	org_id: string
	name: string
	description?: string
	category: string // support, billing, email, customer, general
	prompt: string
	is_active: boolean
	created_at: string
	updated_at: string
}

export interface AllFunnelStatsRequest {
}
export interface AllFunnelStatsRequestParams {
	start_date?: string
	end_date?: string
}

export interface AllFunnelStatsResponse {
	funnels: Array<FunnelPerformance>
}

export interface AnalyticsResponse {
	success: boolean
	message?: string
}

export interface ApplyCreditRequest {
	amount_cents: number
	reason?: string
	expires_at?: string
}
export interface ApplyCreditRequestParams {
}

export interface ApplyCreditResponse {
	success: boolean
	message: string
}

export interface ApproveAgentActionRequest {
}
export interface ApproveAgentActionRequestParams {
}

export interface AssignLeadRequest {
	agent_id: string
	notes?: string
}
export interface AssignLeadRequestParams {
}

export interface AssignTagToCustomerRequest {
	customer_id: string
	tag_id: string
}

export interface AttributionSourceStats {
	source: string
	medium?: string
	campaign?: string
	visitors: number
	conversions: number
	conversion_rate: number
	steps?: { [key: string]: number }
}

export interface AttributionTotals {
	visitors: number
	conversions: number
	conversion_rate: number
}

export interface AuthorProfileInfo {
	id: string
	user_id: string
	user_name?: string
	user_email?: string
	display_name: string
	bio?: string
	avatar_url?: string
	website_url?: string
	twitter_handle?: string
	linkedin_url?: string
	github_handle?: string
	is_public: boolean
	created_at: string
	updated_at: string
}

export interface AutomationLogEntry {
	id: string
	org_id: string
	event_id: string
	event_type: string
	event_payload?: string
	rule_id?: string
	rule_name: string
	rule_snapshot?: string
	actions_executed: Array<RuleAction>
	success: boolean
	error_message?: string
	execution_time_ms: number
	created_at: string
}

export interface AvailabilityRequest {
}
export interface AvailabilityRequestParams {
	date: string
	timezone?: string
}

export interface AvailabilityResponse {
	date: string
	timezone: string
	availability: Array<TimeSlot>
}

export interface AvailableLLMModel {
	provider: string // anthropic, openai, azure
	model: string // claude-sonnet-4, gpt-4o, etc.
	display_name: string // Human-friendly name
	tier?: string // haiku, sonnet, opus
	is_default: boolean // Whether this is the default for the tier
	is_active: boolean // Whether this model is active at platform level
	complexity_min: number // Min complexity score
	complexity_max: number // Max complexity score
	input_cost_per_1m: number // Cost per 1M input tokens
	output_cost_per_1m: number // Cost per 1M output tokens
}

export interface BillingPriceInfo {
	id: string
	org_id: string
	product_id: string
	product_name?: string
	stripe_price_id?: string
	provider?: string
	provider_price_id?: string
	nickname?: string
	display_name?: string
	unit_amount_cents: number
	compare_at_cents?: number
	currency: string
	recurring_interval?: string
	recurring_interval_count?: number
	usage_type: string
	active: boolean
	// Billing model
	price_type: string
	billing_model: string
	minimum_quantity?: number
	maximum_quantity?: number
	// Trials
	trial_period_days?: number
	// Usage/metered
	included_units?: number
	overage_unit_amount_cents?: number
	// Feature limits (for SaaS tiers)
	feature_limits?: { [key: string]: any }
	// Display
	display_order: number
	highlighted: boolean
	// Related
	tiers?: Array<PriceTierInfo>
	currencies?: Array<PriceCurrencyInfo>
	created_at: string
}

export interface BillingProductInfo {
	id: string
	org_id: string
	slug?: string
	stripe_product_id?: string
	provider?: string
	provider_product_id?: string
	name: string
	description?: string
	tagline?: string
	type: string
	category: string
	delivery_method?: string
	active: boolean
	// Marketing
	features?: Array<ProductFeature>
	whats_included?: Array<string>
	who_its_for?: Array<string>
	// Stripe/Tax
	tax_code?: string
	unit_label?: string
	shippable: boolean
	images?: Array<string>
	// Inventory
	inventory_type?: string
	inventory_count?: number
	low_stock_threshold?: number
	// Display
	display_order: number
	highlighted: boolean
	cta_text?: string
	// Related
	prices?: Array<BillingPriceInfo>
	email_sequence_id?: number
	created_at: string
}

export interface BookMeetingRequest {
	lead_id: string
	attendee_name: string
	attendee_email: string
	attendee_phone?: string
	meeting_date: string
	meeting_time: string
	timezone: string
	notes?: string
}

export interface BookMeetingResponse {
	meeting_id: string
	meeting_time: string
	zoom_join_url?: string
	google_calendar_id?: string
	status: string
}

export interface CampaignInfo {
	id: number
	org_id: string
	design_id?: number
	name: string
	subject: string
	preview_text?: string
	from_name?: string
	from_email?: string
	reply_to?: string
	html_body: string
	plain_text?: string
	list_ids: Array<number>
	exclude_list_ids?: Array<number>
	status: string // draft, scheduled, sending, sent, paused, cancelled
	scheduled_at?: string
	started_at?: string
	completed_at?: string
	track_opens: boolean
	track_clicks: boolean
	recipients_count: number
	sent_count: number
	delivered_count: number
	opened_count: number
	clicked_count: number
	bounced_count: number
	complained_count: number
	unsubscribed_count: number
	created_at: string
	updated_at: string
}

export interface CampaignLinkStat {
	url: string
	name?: string
	click_count: number
}

export interface CampaignStatsResponse {
	campaign: CampaignInfo
	links: Array<CampaignLinkStat>
}

export interface CancelEmailRequest {
}
export interface CancelEmailRequestParams {
}

export interface CancelSubscriptionRequest {
}
export interface CancelSubscriptionRequestParams {
}

export interface CancelWorkshopRegistrationRequest {
	reason?: string
}
export interface CancelWorkshopRegistrationRequestParams {
}

export interface CapabilityDefinition {
	id: string // e.g., 'support.ticket_triage'
	domain: string
	capability: string
	name: string
	description?: string
	level_1_behavior?: string
	level_2_behavior?: string
	level_3_behavior?: string
	level_4_behavior?: string
	has_amount_threshold: boolean
	threshold_label?: string
	requires_ai: boolean
	display_order: number
	icon?: string
}

export interface CheckoutItem {
	price_id: string
	quantity: number
}

export interface CheckoutRequest {
	customer_email: string
	line_items: Array<CheckoutItem>
	mode: string // payment, subscription
	success_url: string
	cancel_url: string
}

export interface CheckoutResponse {
	session_id: string
	checkout_url: string
}

export interface ComplexityThreshold {
	tier: string // haiku, sonnet, opus
	min: number
	max: number
}

export interface ConfirmEmailRequest {
}
export interface ConfirmEmailRequestParams {
	token: string
}

export interface ConfirmEmailResponse {
	success: boolean
	message?: string
	redirect?: string
}

export interface ContactActivityInfo {
	event: string // email_sent, email_opened, email_clicked, subscribed, unsubscribed, purchase, etc.
	timestamp: string
	details?: string // Event-specific details (email subject, link clicked, etc.)
}

export interface ContactRequest {
	email: string
	name?: string
	phone?: string
	company?: string
	employees?: string // For lead scoring context
	message?: string // Contact form message
	source?: string
	tags?: Array<string>
	funnel_slug?: string // Auto-subscribe to funnel
	list_slug?: string // Auto-subscribe to list
	score?: boolean // Trigger AI lead scoring
	utm_source?: string
	utm_medium?: string
	utm_campaign?: string
	meta?: { [key: string]: string }
}

export interface ContactResponse {
	id: string
	email: string
	name: string
	score?: number // Lead score (if scoring requested)
	qualified?: boolean // Is qualified lead
	reasoning?: string // AI reasoning
	next_steps?: string // Suggested next steps
}

export interface ContactStatsPoint {
	date: string
	new_contacts: number
	unsubscribed: number
	bounced: number
	net_growth: number
}

export interface ContentCategoryInfo {
	id: string
	name: string
	slug: string
	description?: string
	post_count?: number
	created_at: string
	updated_at: string
}

export interface ContentPageInfo {
	id: string
	template_id?: string
	template_name?: string
	template_slug?: string
	title: string
	slug: string
	content?: string
	status: string
	meta_title?: string
	meta_description?: string
	featured_image?: string
	author_id?: string
	created_at: string
	updated_at: string
	published_at?: string
}

export interface ContentPostInfo {
	id: string
	category_id?: string
	category_name?: string
	category_slug?: string
	title: string
	slug: string
	content?: string
	excerpt?: string
	status: string
	scheduled_at?: string
	meta_title?: string
	meta_description?: string
	featured_image?: string
	author_id?: string
	created_at: string
	updated_at: string
	published_at?: string
}

export interface CreateAgentPromptRequest {
	name: string
	description?: string
	category: string
	prompt: string
	is_active: boolean
}

export interface CreateAuthorProfileRequest {
	user_id: string
	display_name: string
	bio?: string
	avatar_url?: string
	website_url?: string
	twitter_handle?: string
	linkedin_url?: string
	github_handle?: string
	is_public?: boolean
}

export interface CreateBillingPriceRequest {
	product_id: string
	nickname?: string
	display_name?: string
	unit_amount_cents: number
	compare_at_cents?: number
	currency?: string
	recurring_interval?: string
	recurring_interval_count?: number
	usage_type?: string
	active?: boolean
	// Provider
	provider?: string
	provider_price_id?: string
	// Billing model
	price_type?: string
	billing_model?: string
	minimum_quantity?: number
	maximum_quantity?: number
	// Trials
	trial_period_days?: number
	// Usage/metered
	included_units?: number
	overage_unit_amount_cents?: number
	// Feature limits
	feature_limits?: { [key: string]: any }
	// Display
	display_order?: number
	highlighted?: boolean
}

export interface CreateBillingProductRequest {
	slug?: string
	name: string
	description?: string
	tagline?: string
	type: string
	category?: string
	delivery_method?: string
	active?: boolean
	// Provider
	provider?: string
	provider_product_id?: string
	// Marketing
	features?: Array<ProductFeature>
	whats_included?: Array<string>
	who_its_for?: Array<string>
	// Stripe/Tax
	tax_code?: string
	unit_label?: string
	shippable?: boolean
	images?: Array<string>
	// Inventory
	inventory_type?: string
	inventory_count?: number
	low_stock_threshold?: number
	// Display
	display_order?: number
	highlighted?: boolean
	cta_text?: string
	// Related
	email_sequence_id?: number
}

export interface CreateCampaignRequest {
	design_id?: number
	name: string
	subject: string
	preview_text?: string
	from_name?: string
	from_email?: string
	reply_to?: string
	html_body: string
	plain_text?: string
	list_ids: Array<number>
	exclude_list_ids?: Array<number>
	track_opens?: boolean
	track_clicks?: boolean
}

export interface CreateContentCategoryRequest {
	name: string
	slug: string
	description?: string
}

export interface CreateContentPageRequest {
	template_id?: string
	title: string
	slug: string
	content?: string
	status?: string
	meta_title?: string
	meta_description?: string
	featured_image?: string
}

export interface CreateContentPostRequest {
	category_id?: string
	title: string
	slug: string
	content?: string
	excerpt?: string
	status?: string
	scheduled_at?: string
	meta_title?: string
	meta_description?: string
	featured_image?: string
}

export interface CreateCustomQuoteRequest {
	customer_id?: string
	customer_email?: string
	company_name?: string
	name: string
	valid_until?: string
	base_product_id?: string
	custom_amount_cents: number
	currency?: string
	billing_type?: string
	recurring_interval?: string
	recurring_interval_count?: number
	contract_term_months?: number
	custom_features?: Array<string>
	custom_terms?: string
	notes?: string
}

export interface CreateCustomerActivityRequest {
	customer_id: string
	activity_type: string
	title: string
	description?: string
	metadata?: string
}

export interface CreateCustomerRequest {
	email: string
	password?: string
	name?: string
	phone?: string
	metadata?: string
}

export interface CreateCustomerTagRequest {
	name: string
	color?: string
	description?: string
}

export interface CreateEmailDesignRequest {
	name: string
	slug: string
	description?: string
	category?: string // general, newsletter, promotional, transactional
	html_body: string
	plain_text?: string
	is_active?: boolean
}

export interface CreateEmailListRequest {
	name: string
	slug: string
	description?: string
	double_optin?: boolean
}

export interface CreateEntryRuleRequest {
	sequence_id: number
	trigger_type: string // list_join, sequence_complete, tag_added, manual
	source_id?: number
	priority?: number
}

export interface CreateFunnelRequest {
	slug: string
	name: string
	description?: string
	list_id?: number // Email list to subscribe opt-ins to
}

export interface CreateFunnelStepRequest {
	funnel_id: number
	slug: string
	step_type: string
	position?: number
	title: string
	headline?: string
	subheadline?: string
	content?: { [key: string]: any }
	product_id?: string
	order_bump_product_id?: string
	order_bump_headline?: string
	order_bump_description?: string
	next_step_id?: number
	decline_step_id?: number
	success_redirect?: string
	email_sequence_id?: number
	trigger_event?: string
	is_active?: boolean
}

export interface CreateLLMModelRequest {
	provider: string
	model: string
	model_tier?: string
	input_price_per_million_micros: number
	output_price_per_million_micros: number
	credit_multiplier: number
	display_name?: string
	display_order?: number
	is_default?: boolean
	active?: boolean
	// Complexity routing fields
	min_complexity?: number
	max_complexity?: number
	max_context_tokens?: number
	supports_vision?: boolean
	supports_function_calling?: boolean
}

export interface CreateMCPAPIKeyRequest {
	name: string
	expires_at?: string // ISO 8601 date or empty for no expiry
}

export interface CreateMCPAPIKeyResponse {
	id: string
	name: string
	key: string // Full key - ONLY returned on creation
	key_prefix: string
	created_at: string
}

export interface CreateNavigationItemRequest {
	menu_id: string
	parent_id?: string
	label: string
	url?: string
	target?: string
	icon?: string
	sort_order?: number
	is_active?: boolean
}

export interface CreateNavigationMenuRequest {
	name: string
	slug: string
	location?: string
}

export interface CreateOrgRequest {
	name: string
	slug: string
	plan?: string
	max_contacts?: number
	app_url?: string
}

export interface CreatePageTemplateRequest {
	name: string
	slug: string
	description?: string
}

export interface CreatePriceCurrencyRequest {
	price_id: string
	currency: string
	unit_amount_cents: number
	compare_at_cents?: number
}

export interface CreatePriceTierRequest {
	price_id: string
	tier_type?: string
	up_to?: number
	unit_amount_cents: number
	flat_amount_cents?: number
}

export interface CreateProductBundleRequest {
	parent_product_id: string
	child_product_id: string
	bundle_type?: string
	quantity?: number
	discount_percent?: number
	required?: boolean
	display_order?: number
}

export interface CreateProductCustomFieldRequest {
	product_id: string
	field_key: string
	field_value?: string
	field_type?: string
}

export interface CreateQuoteItemRequest {
	quote_id: string
	product_id?: string
	price_id?: string
	description?: string
	quantity?: number
	unit_amount_cents: number
	discount_percent?: number
	display_order?: number
}

export interface CreateRuleRequest {
	name: string
	description?: string
	category: string
	rule_json: string
	entity_type?: string
	entity_id?: string
	enabled: boolean
	salience: number
}

export interface CreateSequenceRequest {
	list_id?: number // Optional - use entry rules instead
	slug: string
	name: string
	trigger_event?: string
	sequence_type?: string // lifecycle or transactional
}

export interface CreateTemplateRequest {
	sequence_id: number
	position: number
	delay_hours: number
	subject: string
	html_body: string
	plain_text?: string
	template_type?: string // none, simple, branded
	is_active?: boolean
	design_id?: number // Optional reference to email design
}

export interface CreateTicketRequest {
	customer_id: string
	subject: string
	description?: string
	priority?: string
}

export interface CreateTransactionalEmailRequest {
	design_id?: number
	name: string
	slug: string
	description?: string
	subject: string
	html_body: string
	plain_text?: string
	from_name?: string
	from_email?: string
	reply_to?: string
	is_active?: boolean
}

export interface CreateUserRequest {
	email: string
	password: string
	name: string
	role?: string
}

export interface CreateUserResponse {
	user: UserInfo
}

export interface CreateWorkshopEventRequest {
	slug: string
	product_id?: string // Link to workshop product (inherits price/description)
	title?: string // Override product title if needed
	description?: string
	start_date: string
	end_date: string
	start_time: string
	end_time: string
	timezone?: string
	location_type?: string
	location_details?: string
	price_cents?: number // Override product price if needed
	currency?: string
	max_seats?: number
	allow_waitlist?: boolean
	waitlist_limit?: number // 0 = unlimited waitlist
	whats_included?: Array<string>
	who_its_for?: Array<string>
	agenda?: Array<WorkshopAgendaDay>
	// Funnel integration
	funnel_id?: number
	confirmation_sequence_id?: number
	reminder_sequence_id?: number
	order_bump_product_ids?: Array<string>
}

export interface CrowdGainsEventRequest {
	visitorId: string
	sessionId?: string
	event: string
	properties?: { [key: string]: any }
	timestamp?: string
}

export interface CrowdGainsFingerprintRequest {
	sid?: string
	ua?: string
	d?: { [key: string]: any }
}

export interface CrowdGainsResponse {
	success: boolean
	visitorId?: string
	sessionId?: string
	message?: string
}

export interface CustomQuoteInfo {
	id: string
	org_id: string
	customer_id?: string
	customer_email?: string
	company_name?: string
	name: string
	status: string
	valid_until?: string
	base_product_id?: string
	base_product_name?: string
	custom_amount_cents: number
	currency: string
	billing_type: string
	recurring_interval?: string
	recurring_interval_count?: number
	contract_term_months?: number
	custom_features?: Array<string>
	custom_terms?: string
	notes?: string
	created_by?: string
	created_by_email?: string
	accepted_at?: string
	created_at: string
	updated_at: string
	// Related
	items?: Array<CustomQuoteItemInfo>
	total_cents?: number
}

export interface CustomQuoteItemInfo {
	id: string
	quote_id: string
	product_id?: string
	product_name?: string
	price_id?: string
	price_nickname?: string
	description?: string
	quantity: number
	unit_amount_cents: number
	discount_percent: number
	total_cents: number
	display_order: number
	created_at: string
}

export interface CustomerActivityInfo {
	id: string
	activity_type: string
	title: string
	description?: string
	metadata?: string
	created_at: string
	created_by?: string
}

export interface CustomerCreditInfo {
	id: string
	amount: number
	currency: string
	reason?: string
	expires_at?: string
	used_at?: string
	created_by?: string
	created_at: string
}

export interface CustomerDetailResponse {
	customer: CustomerInfo
	subscription?: SubscriptionInfo
	invoices: Array<InvoiceInfo>
	payments: Array<PaymentInfo>
	credits: Array<CustomerCreditInfo>
	notes: Array<CustomerNoteInfo>
	tags: Array<CustomerTagInfo>
	recent_activities: Array<CustomerActivityInfo>
	credit_balance: number
	open_tickets: number
	lifecycle_stage: string
	health_score: number
	tenure_days: number
	total_payments: number
	ltv: number
}

export interface CustomerEmailInfo {
	id: string
	subject: string
	status: string
	sent_at?: string
	opened_at?: string
	clicked_at?: string
	created_at: string
}

export interface CustomerInfo {
	id: string
	org_id: string
	email: string
	name: string
	phone?: string
	status: string
	email_verified: boolean
	stripe_customer_id?: string
	metadata?: string
	created_at: string
	updated_at: string
	last_login_at?: string
}

export interface CustomerListResponse {
	customers: Array<CustomerInfo>
	total: number
	page: number
	page_size: number
}

export interface CustomerNoteInfo {
	id: string
	note: string
	created_by: string
	created_at: string
}

export interface CustomerRequest {
	email: string
	name?: string
	phone?: string
	meta?: { [key: string]: string }
}

export interface CustomerResponse {
	id: string
	stripe_customer_id: string
	email: string
	name: string
}

export interface CustomerStatsResponse {
	total: number
	active: number
	inactive: number
	suspended: number
	verified: number
	with_stripe: number
	new_last_30_days: number
	open_tickets: number
}

export interface CustomerTagInfo {
	id: string
	name: string
	color: string
	description?: string
}

export interface CustomerTagWithCountInfo {
	id: string
	name: string
	color: string
	description?: string
	customer_count: number
}

export interface DashboardNeedsAttention {
	type: string
	count: number
	description: string
}

export interface DashboardRecentOrder {
	id: string
	order_number: string
	customer_email: string
	customer_name: string
	total_cents: number
	payment_status: string
	created_at: string
}

export interface DashboardRevenueTrend {
	month: string
	revenue_cents: number
	order_count: number
}

export interface DashboardStatsResponse {
	// Revenue stats
	total_revenue_cents: number
	revenue_mtd_cents: number
	revenue_last_month_cents: number
	revenue_ytd_cents: number
	revenue_growth_pct: number // MoM growth
	// Order stats
	paid_orders_count: number
	orders_mtd_count: number
	pending_orders_count: number
	failed_orders_count: number
	// Customer stats
	total_customers: number
	new_customers_30d: number
	new_customers_7d: number
	customer_growth_pct: number
	// Subscription stats (MRR)
	active_subscriptions: number
	churned_30d: number
	trialing_count: number
	new_subscriptions_mtd: number
	churn_rate: number // churned_30d / total
	// LLM stats
	llm_total_requests: number
	llm_total_tokens: number
	llm_total_cost_micros: number
	llm_success_count: number
	llm_error_count: number
	llm_avg_latency_ms: number
	// Email stats
	emails_sent_30d: number
	emails_opened_30d: number
	emails_clicked_30d: number
	email_open_rate: number
	// Recent orders
	recent_orders: Array<DashboardRecentOrder>
	// Revenue trend (6 months)
	revenue_trend: Array<DashboardRevenueTrend>
	// Needs attention items
	needs_attention: Array<DashboardNeedsAttention>
	// Setup checklist
	stripe_configured: boolean
	has_products: boolean
	has_email_lists: boolean
	has_funnels: boolean
	has_mcp_configured: boolean
}

export interface DeleteAgentPromptRequest {
}
export interface DeleteAgentPromptRequestParams {
}

export interface DeleteAuthorProfileRequest {
}
export interface DeleteAuthorProfileRequestParams {
}

export interface DeleteBillingPriceRequest {
}
export interface DeleteBillingPriceRequestParams {
}

export interface DeleteBillingProductRequest {
}
export interface DeleteBillingProductRequestParams {
}

export interface DeleteCampaignRequest {
}
export interface DeleteCampaignRequestParams {
}

export interface DeleteContentCategoryRequest {
}
export interface DeleteContentCategoryRequestParams {
}

export interface DeleteContentPageRequest {
}
export interface DeleteContentPageRequestParams {
}

export interface DeleteContentPostRequest {
}
export interface DeleteContentPostRequestParams {
}

export interface DeleteCustomQuoteRequest {
}
export interface DeleteCustomQuoteRequestParams {
}

export interface DeleteCustomerRequest {
}
export interface DeleteCustomerRequestParams {
}

export interface DeleteCustomerTagRequest {
}
export interface DeleteCustomerTagRequestParams {
}

export interface DeleteEmailDesignRequest {
}
export interface DeleteEmailDesignRequestParams {
}

export interface DeleteEmailListRequest {
}
export interface DeleteEmailListRequestParams {
}

export interface DeleteEntryRuleRequest {
}
export interface DeleteEntryRuleRequestParams {
}

export interface DeleteFunnelRequest {
}
export interface DeleteFunnelRequestParams {
}

export interface DeleteFunnelStepRequest {
}
export interface DeleteFunnelStepRequestParams {
}

export interface DeleteLLMModelRequest {
}
export interface DeleteLLMModelRequestParams {
}

export interface DeleteLeadRequest {
}
export interface DeleteLeadRequestParams {
}

export interface DeleteNavigationItemRequest {
}
export interface DeleteNavigationItemRequestParams {
}

export interface DeleteNavigationMenuRequest {
}
export interface DeleteNavigationMenuRequestParams {
}

export interface DeleteOrgRequest {
}
export interface DeleteOrgRequestParams {
}

export interface DeletePageTemplateRequest {
}
export interface DeletePageTemplateRequestParams {
}

export interface DeletePriceCurrencyRequest {
}
export interface DeletePriceCurrencyRequestParams {
}

export interface DeletePriceTierRequest {
}
export interface DeletePriceTierRequestParams {
}

export interface DeleteProductBundleRequest {
}
export interface DeleteProductBundleRequestParams {
}

export interface DeleteProductCustomFieldRequest {
}
export interface DeleteProductCustomFieldRequestParams {
}

export interface DeleteQuoteItemRequest {
}
export interface DeleteQuoteItemRequestParams {
}

export interface DeleteRuleRequest {
}
export interface DeleteRuleRequestParams {
}

export interface DeleteTemplateRequest {
}
export interface DeleteTemplateRequestParams {
}

export interface DeleteTransactionalEmailRequest {
}
export interface DeleteTransactionalEmailRequestParams {
}

export interface DeleteUserRequest {
}
export interface DeleteUserRequestParams {
}

export interface DeleteWebhookRequest {
}
export interface DeleteWebhookRequestParams {
}

export interface DeleteWorkshopEventRequest {
}
export interface DeleteWorkshopEventRequestParams {
}

export interface EmailClickRequest {
}
export interface EmailClickRequestParams {
	url: string
	name?: string
}

export interface EmailDashboardStatsRequest {
}
export interface EmailDashboardStatsRequestParams {
	from?: string
	to?: string
}

export interface EmailDashboardStatsResponse {
	total_sent: number
	total_opened: number
	total_clicked: number
	total_bounced: number
	total_complaints: number
	total_unsubscribed: number
	open_rate: number
	click_rate: number
}

export interface EmailDesignInfo {
	id: number
	org_id: string
	name: string
	slug: string
	description?: string
	category: string // general, newsletter, promotional, transactional
	html_body: string
	plain_text?: string
	is_active: boolean
	created_at: string
	updated_at: string
}

export interface EmailEventInfo {
	event: string // sent, delivered, opened, clicked, bounced, complained
	timestamp: string
	data?: string // Additional event data (link clicked, bounce reason, etc.)
}

export interface EmailListInfo {
	id: number
	org_id: string
	name: string
	slug: string
	description: string
	double_optin: boolean
	confirmation_subject?: string
	confirmation_body?: string
	confirmation_design_id?: number
	subscriber_count: number
	created_at: string
	updated_at: string
}

export interface EmailListStatsResponse {
	total_subscribers: number
	active_subscribers: number
	unsubscribed: number
	bounced: number
	complained: number
}

export interface EmailOpenRequest {
}
export interface EmailOpenRequestParams {
}

export interface EmailQueueItem {
	id: number
	lead_id: number
	lead_email: string
	lead_name: string
	template_id: number
	subject: string
	scheduled_for: string
	sent_at?: string
	status: string
	error_message?: string
}

export interface EmailQueueListRequest {
}
export interface EmailQueueListRequestParams {
	status?: string
	lead_id?: string
}

export interface EmailQueueListResponse {
	items: Array<EmailQueueItem>
	total: number
}

export interface EmailStatsPoint {
	date: string
	sent: number
	delivered: number
	opened: number
	clicked: number
	bounced: number
	open_rate: number
	click_rate: number
}

export interface EmailStatusResponse {
	message_id: string
	to: string
	subject: string
	status: string // queued, sent, delivered, opened, clicked, bounced, complained
	sent_at?: string
	delivered_at?: string
	opened_at?: string
	clicked_at?: string
	bounced_at?: string
	bounce_type?: string
	opens: number
	clicks: number
}

export interface EmptyResponse {
}

export interface EnrollSequenceRequest {
	sequence_slug: string
	email: string
	variables?: { [key: string]: string } // Custom merge fields
	start_at_step?: number // Skip to specific step (1-indexed)
	scheduled_for?: string // Delay start (RFC3339)
}

export interface EnrollSequenceResponse {
	success: boolean
	enrollment_id: string
	status: string // active, scheduled, paused
	message?: string
}

export interface EntryRuleInfo {
	id: number
	sequence_id: number
	trigger_type: string // list_join, sequence_complete, tag_added, manual
	source_id?: number
	source_name?: string // list name or sequence name
	priority: number
	is_active: boolean
	created_at: string
}

export interface EntryRuleResponse {
	entry_rule: EntryRuleInfo
}

export interface EventRequest {
	event: string // e.g., "page_view", "click", "signup"
	email?: string
	visitor_id?: string
	session_id?: string
	page?: string
	referrer?: string
	funnel_slug?: string
	funnel_step?: string
	scroll_depth?: number
	properties?: { [key: string]: any }
	utm_source?: string
	utm_medium?: string
	utm_campaign?: string
}

export interface FactCategoryInfo {
	id: string
	name: string
	description: string
	icon: string
	fields: Array<FactFieldInfo>
}

export interface FactFieldInfo {
	path: string
	name: string
	type: string // string, number, boolean, date, enum
	description: string
	options?: Array<string> // For enum types
}

export interface ForgotPasswordRequest {
	email: string
}

export interface ForgotPasswordResponse {
	message: string
}

export interface FunnelAttributionRequest {
}
export interface FunnelAttributionRequestParams {
	slug: string
	start_date?: string
	end_date?: string
}

export interface FunnelAttributionResponse {
	sources: Array<AttributionSourceStats>
	total: AttributionTotals
}

export interface FunnelCheckoutRequest {
	step_slug: string
	name: string
	email: string
	company?: string
	include_bump?: boolean
}

export interface FunnelCheckoutResponse {
	success: boolean
	checkout_url?: string
	session_id?: string
	error_message?: string
}

export interface FunnelEventRequest {
	visitor_id: string
	session_id: string
	funnel_step: string
	page: string
	scroll_depth?: number
	referrer?: string
	utm_source?: string
	utm_medium?: string
	utm_campaign?: string
	lead_id?: string
}

export interface FunnelInfo {
	id: number
	slug: string
	name: string
	description?: string
	list_id?: number // Email list to subscribe opt-ins to
	list_slug?: string
	list_name?: string
	step_count: number
	steps?: Array<FunnelStepInfo>
	created_at: string
}

export interface FunnelOptInRequest {
	name: string
	email: string
	funnel: string
	utm_source?: string
	utm_medium?: string
	utm_campaign?: string
}

export interface FunnelOptInResponse {
	success: boolean
	message?: string
	lead_id?: string
	redirect?: string
}

export interface FunnelPerformance {
	slug: string
	visitors: number
	conversions: number
	conversion_rate: number
}

export interface FunnelStatsRequest {
}
export interface FunnelStatsRequestParams {
	start_date?: string
	end_date?: string
	slug?: string
}

export interface FunnelStatsResponse {
	steps: Array<FunnelStepStats>
	scroll_depth: Array<ScrollDepthStats>
	conversion_rates: { [key: string]: number }
}

export interface FunnelStepInfo {
	id: number
	funnel_id: number
	funnel_slug?: string
	slug: string
	step_type: string
	position: number
	title: string
	headline?: string
	subheadline?: string
	content?: { [key: string]: any }
	product_id?: string
	product?: BillingProductInfo
	order_bump_product_id?: string
	order_bump_product?: BillingProductInfo
	order_bump_headline?: string
	order_bump_description?: string
	next_step_id?: number
	decline_step_id?: number
	success_redirect?: string
	email_sequence_id?: number
	trigger_event?: string
	is_active: boolean
	created_at: string
}

export interface FunnelStepStats {
	step: string
	unique_visitors: number
	unique_sessions: number
	total_events: number
	avg_scroll_depth: number
}

export interface FunnelSubscriberInfo {
	id: string
	name: string
	email: string
	status: string
	email_verified: boolean
	funnel_step: string
	source: string
	created_at: string
	verified_at?: string
	unsubscribed_at?: string
	blocked_at?: string
}

export interface FunnelSubscribersResponse {
	subscribers: Array<FunnelSubscriberInfo>
	total: number
	page: number
	page_size: number
}

export interface FunnelTrackEventRequest {
	lead_id?: string
	visitor_id?: string
	event: string
	funnel?: string
	data?: { [key: string]: any }
}

export interface GetAgentConfigRequest {
}

export interface GetAuthorProfileRequest {
}
export interface GetAuthorProfileRequestParams {
}

export interface GetBillingPriceRequest {
}
export interface GetBillingPriceRequestParams {
}

export interface GetBillingProductRequest {
}
export interface GetBillingProductRequestParams {
}

export interface GetCampaignRequest {
}
export interface GetCampaignRequestParams {
}

export interface GetContactRequest {
}
export interface GetContactRequestParams {
}

export interface GetContactStatsRequest {
}
export interface GetContactStatsRequestParams {
	start_date?: string // RFC3339
	end_date?: string // RFC3339
	group_by?: string // day, week, month
}

export interface GetContactStatsResponse {
	stats: Array<ContactStatsPoint>
	// Current state
	total_active: number
	total_unsubscribed: number
	total_bounced: number
	net_growth: number // For period
}

export interface GetContentCategoryRequest {
}
export interface GetContentCategoryRequestParams {
}

export interface GetContentPageRequest {
}
export interface GetContentPageRequestParams {
}

export interface GetContentPostRequest {
}
export interface GetContentPostRequestParams {
}

export interface GetCustomQuoteRequest {
}
export interface GetCustomQuoteRequestParams {
}

export interface GetCustomerByEmailRequest {
}
export interface GetCustomerByEmailRequestParams {
}

export interface GetCustomerRequest {
}
export interface GetCustomerRequestParams {
}

export interface GetDashboardStatsRequest {
}
export interface GetDashboardStatsRequestParams {
	from?: string
	to?: string
}

export interface GetEmailDesignRequest {
}
export interface GetEmailDesignRequestParams {
}

export interface GetEmailListRequest {
}
export interface GetEmailListRequestParams {
}

export interface GetEmailStatsRequest {
}
export interface GetEmailStatsRequestParams {
	start_date?: string // RFC3339
	end_date?: string // RFC3339
	group_by?: string // day, week, month
}

export interface GetEmailStatsResponse {
	stats: Array<EmailStatsPoint>
	// Totals for the period
	total_sent: number
	total_delivered: number
	total_opened: number
	total_clicked: number
	total_bounced: number
	avg_open_rate: number
	avg_click_rate: number
}

export interface GetEmailStatusRequest {
}
export interface GetEmailStatusRequestParams {
}

export interface GetFunnelRequest {
}
export interface GetFunnelRequestParams {
}

export interface GetFunnelStepBySlugRequest {
}
export interface GetFunnelStepBySlugRequestParams {
}

export interface GetFunnelStepRequest {
}
export interface GetFunnelStepRequestParams {
}

export interface GetLeadRequest {
}
export interface GetLeadRequestParams {
}

export interface GetNavigationItemRequest {
}
export interface GetNavigationItemRequestParams {
}

export interface GetNavigationMenuRequest {
}
export interface GetNavigationMenuRequestParams {
}

export interface GetNextWorkshopByProductRequest {
}
export interface GetNextWorkshopByProductRequestParams {
}

export interface GetOrderRequest {
}
export interface GetOrderRequestParams {
}

export interface GetOrgBySlugRequest {
}
export interface GetOrgBySlugRequestParams {
}

export interface GetOrgLLMCredentialsRequest {
}
export interface GetOrgLLMCredentialsRequestParams {
}

export interface GetOrgRequest {
}
export interface GetOrgRequestParams {
}

export interface GetPageTemplateRequest {
}
export interface GetPageTemplateRequestParams {
}

export interface GetPlatformSettingsByCategoryRequest {
}
export interface GetPlatformSettingsByCategoryRequestParams {
}

export interface GetPlatformSettingsResponse {
	settings: Array<PlatformSettingInfo>
}

export interface GetProductBySlugRequest {
}
export interface GetProductBySlugRequestParams {
}

export interface GetQuizBySlugRequest {
}
export interface GetQuizBySlugRequestParams {
}

export interface GetQuizRequest {
}
export interface GetQuizRequestParams {
}

export interface GetRevenueStatsRequest {
}
export interface GetRevenueStatsRequestParams {
	start_date?: string // RFC3339
	end_date?: string // RFC3339
	group_by?: string // day, week, month
}

export interface GetRevenueStatsResponse {
	stats: Array<RevenueStatsPoint>
	// Totals for the period
	total_revenue: number
	total_orders: number
	total_subscriptions: number
	total_churned: number
	mrr: number // Monthly recurring revenue
}

export interface GetRuleRequest {
}
export interface GetRuleRequestParams {
}

export interface GetSDKAuthorRequest {
}
export interface GetSDKAuthorRequestParams {
}

export interface GetSDKContentPageRequest {
}
export interface GetSDKContentPageRequestParams {
}

export interface GetSDKContentPostRequest {
}
export interface GetSDKContentPostRequestParams {
}

export interface GetSDKNavigationMenuRequest {
}
export interface GetSDKNavigationMenuRequestParams {
}

export interface GetSDKSiteSettingsRequest {
}

export interface GetSequenceEnrollmentRequest {
}
export interface GetSequenceEnrollmentRequestParams {
	email: string
	sequence_slug?: string // If not provided, returns all
}

export interface GetSequenceRequest {
}
export interface GetSequenceRequestParams {
}

export interface GetStatsOverviewRequest {
}
export interface GetStatsOverviewRequestParams {
	start_date?: string // RFC3339
	end_date?: string // RFC3339
}

export interface GetTicketRequest {
}
export interface GetTicketRequestParams {
}

export interface GetTransactionalEmailRequest {
}
export interface GetTransactionalEmailRequestParams {
}

export interface GetUserRequest {
}
export interface GetUserRequestParams {
}

export interface GetWebhookRequest {
}
export interface GetWebhookRequestParams {
}

export interface GetWorkshopByProductSlugRequest {
}
export interface GetWorkshopByProductSlugRequestParams {
}

export interface GetWorkshopBySlugRequest {
}
export interface GetWorkshopBySlugRequestParams {
}

export interface GetWorkshopEventRequest {
}
export interface GetWorkshopEventRequestParams {
}

export interface GetWorkshopRegistrationRequest {
}
export interface GetWorkshopRegistrationRequestParams {
}

export interface GlobalUnsubscribeRequest {
	email: string
	reason?: string
}

export interface HealthResponse {
	status: string
	version?: string
}

export interface InvoiceInfo {
	id: string
	stripe_invoice_id: string
	status: string
	amount_due_cents: number
	amount_paid_cents: number
	currency: string
	invoice_pdf_url?: string
	hosted_invoice_url?: string
	due_date?: string
	paid_at?: string
	created_at: string
}

export interface LLMChatRequest {
	messages: Array<LLMMessage>
	system_prompt?: string
	model?: string // "haiku", "sonnet", "opus" (default: sonnet)
	max_tokens?: number // Default: 2048
	temperature?: number // 0.0-1.0, default: 0.7
}

export interface LLMChatResponse {
	content: string
	model: string
	input_tokens: number
	output_tokens: number
	cost_usd: number
	latency_ms: number
	stop_reason: string
}

export interface LLMConfigResponse {
	available: boolean // Whether LLM is configured
	default_provider: string // anthropic, openai, azure
	configured_providers: Array<string> // List of available providers
	grpc_port: number // Port for streaming connections
}

export interface LLMMessage {
	role: string // "user", "assistant", "system"
	content: string
}

export interface LLMModelPricingInfo {
	id: string
	provider: string // anthropic, openai, azure
	model: string // Full model ID
	model_tier?: string // haiku, sonnet, opus
	input_price_per_million_micros: number // Actual cost
	output_price_per_million_micros: number // Actual cost
	credit_multiplier: number // 1.0=1:1, 2.0=2:1, etc.
	display_name?: string
	display_order?: number
	is_default: boolean
	active: boolean
	// Complexity routing fields
	min_complexity: number // 0-100 scale
	max_complexity: number // 0-100 scale
	max_context_tokens?: number
	supports_vision: boolean
	supports_function_calling: boolean
	created_at?: string
	updated_at?: string
}

export interface LLMRequestLogInfo {
	id: string
	provider: string
	model: string
	model_tier?: string
	input_tokens: number
	output_tokens: number
	total_tokens: number
	credits_used: number
	total_cost_micros: number
	latency_ms: number
	status: string
	error_message?: string
	created_at: string
}

export interface LeadEvaluationRequest {
	name: string
	email: string
	company: string
	employees: string
	message: string
	source?: string
	utm_source?: string
	utm_medium?: string
	utm_campaign?: string
}

export interface LeadEvaluationResponse {
	lead_id: string
	score: number
	qualified: boolean
	reasoning: string
	next_steps: string
}

export interface LeadInfo {
	id: string
	name: string
	email: string
	phone?: string
	company: string
	employees: string
	message: string
	score: number
	qualified: boolean
	status: string
	source?: string
	notes?: string
	assigned_agent_id?: string
	qualification_score?: number
	created_at: string
	updated_at: string
}

export interface LeadListResponse {
	leads: Array<LeadInfo>
	total: number
	page: number
	page_size: number
}

export interface LeadTagsRequest {
}
export interface LeadTagsRequestParams {
}

export interface LeadTagsResponse {
	tags: Array<string>
}

export interface ListAgentActionsRequest {
}
export interface ListAgentActionsRequestParams {
	domain?: string
	status?: string
	page: number
	page_size: number
}

export interface ListAgentActionsResponse {
	actions: Array<AgentActionLogEntry>
	total: number
	page: number
	pages: number
}

export interface ListAgentPromptsRequest {
}
export interface ListAgentPromptsRequestParams {
	category?: string
}

export interface ListAgentPromptsResponse {
	prompts: Array<AgentPromptInfo>
}

export interface ListAuthorProfilesRequest {
}
export interface ListAuthorProfilesRequestParams {
	public_only?: boolean
}

export interface ListAuthorProfilesResponse {
	authors: Array<AuthorProfileInfo>
}

export interface ListAutomationLogRequest {
}
export interface ListAutomationLogRequestParams {
	event_type?: string
	rule_id?: string
	success?: string
	page: number
	page_size: number
}

export interface ListAutomationLogResponse {
	entries: Array<AutomationLogEntry>
	total: number
	page: number
	pages: number
}

export interface ListBillingPricesRequest {
}
export interface ListBillingPricesRequestParams {
	product_id?: string
	price_type?: string
}

export interface ListBillingPricesResponse {
	prices: Array<BillingPriceInfo>
	total: number
}

export interface ListBillingProductsRequest {
}
export interface ListBillingProductsRequestParams {
	category?: string
	active?: string
}

export interface ListBillingProductsResponse {
	products: Array<BillingProductInfo>
	total: number
}

export interface ListCampaignsRequest {
}
export interface ListCampaignsRequestParams {
	status?: string
	page?: number
	limit?: number
}

export interface ListCampaignsResponse {
	campaigns: Array<CampaignInfo>
	total: number
	page: number
	limit: number
}

export interface ListCapabilitiesRequest {
}

export interface ListCapabilitiesResponse {
	capabilities: Array<OrgCapability>
}

export interface ListContactActivityRequest {
}
export interface ListContactActivityRequestParams {
	limit?: number
}

export interface ListContactActivityResponse {
	activities: Array<ContactActivityInfo>
}

export interface ListContentCategoriesRequest {
}

export interface ListContentCategoriesResponse {
	categories: Array<ContentCategoryInfo>
}

export interface ListContentPagesRequest {
}
export interface ListContentPagesRequestParams {
	status?: string
	page?: number
	page_size?: number
}

export interface ListContentPagesResponse {
	pages: Array<ContentPageInfo>
	total: number
}

export interface ListContentPostsRequest {
}
export interface ListContentPostsRequestParams {
	status?: string
	category_id?: string
	page?: number
	page_size?: number
}

export interface ListContentPostsResponse {
	posts: Array<ContentPostInfo>
	total: number
}

export interface ListCustomQuotesRequest {
}
export interface ListCustomQuotesRequestParams {
	status?: string
	customer_id?: string
}

export interface ListCustomQuotesResponse {
	quotes: Array<CustomQuoteInfo>
	total: number
}

export interface ListCustomerActivitiesRequest {
}
export interface ListCustomerActivitiesRequestParams {
	page?: number
	page_size?: number
}

export interface ListCustomerActivitiesResponse {
	activities: Array<CustomerActivityInfo>
	total: number
}

export interface ListCustomerEmailsRequest {
}
export interface ListCustomerEmailsRequestParams {
	page?: number
	page_size?: number
}

export interface ListCustomerEmailsResponse {
	emails: Array<CustomerEmailInfo>
	total: number
}

export interface ListCustomerInvoicesRequest {
}
export interface ListCustomerInvoicesRequestParams {
	limit?: number
}

export interface ListCustomerInvoicesResponse {
	invoices: Array<SDKInvoiceInfo>
	total: number
}

export interface ListCustomerNotesRequest {
}
export interface ListCustomerNotesRequestParams {
}

export interface ListCustomerNotesResponse {
	notes: Array<CustomerNoteInfo>
}

export interface ListCustomerOrdersRequest {
}
export interface ListCustomerOrdersRequestParams {
	limit?: number
}

export interface ListCustomerOrdersResponse {
	orders: Array<SDKOrderInfo>
	total: number
}

export interface ListCustomerPaymentsRequest {
}
export interface ListCustomerPaymentsRequestParams {
	limit?: number
}

export interface ListCustomerPaymentsResponse {
	payments: Array<SDKPaymentInfo>
	total: number
}

export interface ListCustomerSubscriptionsRequest {
}
export interface ListCustomerSubscriptionsRequestParams {
}

export interface ListCustomerSubscriptionsResponse {
	subscriptions: Array<SDKSubscriptionInfo>
}

export interface ListCustomerTagsRequest {
}

export interface ListCustomerTagsResponse {
	tags: Array<CustomerTagWithCountInfo>
}

export interface ListCustomerTicketsRequest {
}
export interface ListCustomerTicketsRequestParams {
	page?: number
	page_size?: number
}

export interface ListCustomerTicketsResponse {
	tickets: Array<SupportTicketInfo>
	total: number
}

export interface ListCustomersRequest {
}
export interface ListCustomersRequestParams {
	page?: number
	page_size?: number
	status?: string
	search?: string
	from?: string
	to?: string
}

export interface ListEmailDesignsRequest {
}
export interface ListEmailDesignsRequestParams {
	category?: string
}

export interface ListEmailDesignsResponse {
	designs: Array<EmailDesignInfo>
	total: number
}

export interface ListEmailEventsRequest {
}
export interface ListEmailEventsRequestParams {
}

export interface ListEmailEventsResponse {
	events: Array<EmailEventInfo>
}

export interface ListEmailListsResponse {
	lists: Array<EmailListInfo>
}

export interface ListFunnelStepsRequest {
}
export interface ListFunnelStepsRequestParams {
	funnel_id: string
}

export interface ListFunnelStepsResponse {
	steps: Array<FunnelStepInfo>
	total: number
}

export interface ListFunnelSubscribersRequest {
}
export interface ListFunnelSubscribersRequestParams {
	page?: number
	page_size?: number
}

export interface ListFunnelsRequest {
}

export interface ListFunnelsResponse {
	funnels: Array<FunnelInfo>
	total: number
}

export interface ListLLMModelsRequest {
}
export interface ListLLMModelsRequestParams {
	provider?: string
	active_only?: boolean
}

export interface ListLLMModelsResponse {
	models: Array<LLMModelPricingInfo>
}

export interface ListLLMRequestsRequest {
}
export interface ListLLMRequestsRequestParams {
	provider?: string
	status?: string
	limit?: number
	offset?: number
}

export interface ListLLMRequestsResponse {
	requests: Array<LLMRequestLogInfo>
	total: number
	total_credits: number
}

export interface ListMCPAPIKeysResponse {
	keys: Array<MCPAPIKeyInfo>
	total: number
}

export interface ListNavigationItemsRequest {
}
export interface ListNavigationItemsRequestParams {
	menu_id: string
}

export interface ListNavigationItemsResponse {
	items: Array<NavigationItemInfo>
}

export interface ListNavigationMenusRequest {
}
export interface ListNavigationMenusRequestParams {
	location?: string
}

export interface ListNavigationMenusResponse {
	menus: Array<NavigationMenuInfo>
}

export interface ListOrdersRequest {
}
export interface ListOrdersRequestParams {
	status?: string
	payment_status?: string
	email?: string
	funnel_id?: string
	limit?: number
	offset?: number
}

export interface ListOrdersResponse {
	orders: Array<OrderInfo>
	total: number
}

export interface ListPageTemplatesRequest {
}

export interface ListPageTemplatesResponse {
	templates: Array<PageTemplateInfo>
}

export interface ListPriceCurrenciesRequest {
}
export interface ListPriceCurrenciesRequestParams {
	price_id: string
}

export interface ListPriceCurrenciesResponse {
	currencies: Array<PriceCurrencyInfo>
	total: number
}

export interface ListPriceTiersRequest {
}
export interface ListPriceTiersRequestParams {
	price_id: string
}

export interface ListPriceTiersResponse {
	tiers: Array<PriceTierInfo>
	total: number
}

export interface ListProductBundlesRequest {
}
export interface ListProductBundlesRequestParams {
	parent_product_id: string
}

export interface ListProductBundlesResponse {
	bundles: Array<ProductBundleInfo>
	total: number
}

export interface ListProductCustomFieldsRequest {
}
export interface ListProductCustomFieldsRequestParams {
	product_id: string
}

export interface ListProductCustomFieldsResponse {
	fields: Array<ProductCustomFieldInfo>
	total: number
}

export interface ListRuleTemplatesRequest {
}
export interface ListRuleTemplatesRequestParams {
	category?: string
}

export interface ListRuleTemplatesResponse {
	templates: Array<RuleTemplateInfo>
}

export interface ListRulesRequest {
}
export interface ListRulesRequestParams {
	category?: string
	entity_type?: string
	entity_id?: string
	enabled?: string
}

export interface ListRulesResponse {
	rules: Array<RuleInfo>
	total: number
}

export interface ListSDKAuthorsRequest {
}

export interface ListSDKAuthorsResponse {
	authors: Array<SDKAuthorInfo>
}

export interface ListSDKContentCategoriesRequest {
}

export interface ListSDKContentCategoriesResponse {
	categories: Array<SDKContentCategoryInfo>
}

export interface ListSDKContentPagesRequest {
}
export interface ListSDKContentPagesRequestParams {
	page?: number
	page_size?: number
}

export interface ListSDKContentPagesResponse {
	pages: Array<SDKContentPageInfo>
	total: number
}

export interface ListSDKContentPostsRequest {
}
export interface ListSDKContentPostsRequestParams {
	page?: number
	page_size?: number
	category?: string
}

export interface ListSDKContentPostsResponse {
	posts: Array<SDKContentPostInfo>
	total: number
}

export interface ListSDKNavigationMenusRequest {
}
export interface ListSDKNavigationMenusRequestParams {
	location?: string
}

export interface ListSDKNavigationMenusResponse {
	menus: Array<SDKNavigationMenu>
}

export interface ListSequenceEnrollmentsResponse {
	enrollments: Array<SequenceEnrollmentInfo>
}

export interface ListSubscriberInfo {
	contact_id: string
	email: string
	name: string
	status: string
	subscribed_at: string
	unsubscribed_at?: string
}

export interface ListSubscribersRequest {
}
export interface ListSubscribersRequestParams {
	page?: number
	limit?: number
	status?: string
}

export interface ListSubscribersResponse {
	subscribers: Array<ListSubscriberInfo>
	total: number
	page: number
	limit: number
}

export interface ListTicketsRequest {
}
export interface ListTicketsRequestParams {
	page?: number
	page_size?: number
	status?: string
	priority?: string
	assigned_to?: string
	customer_id?: string
}

export interface ListTicketsResponse {
	tickets: Array<SupportTicketInfo>
	total: number
	page: number
	page_size: number
}

export interface ListTransactionalEmailsRequest {
}

export interface ListTransactionalEmailsResponse {
	templates: Array<TransactionalEmailInfo>
	total: number
}

export interface ListWebhookLogsRequest {
}
export interface ListWebhookLogsRequestParams {
	limit?: number
}

export interface ListWebhookLogsResponse {
	logs: Array<WebhookLogInfo>
}

export interface ListWebhooksResponse {
	webhooks: Array<WebhookInfo>
}

export interface ListWorkshopEventsRequest {
}
export interface ListWorkshopEventsRequestParams {
	limit?: number
	offset?: number
}

export interface ListWorkshopEventsResponse {
	events: Array<WorkshopEventInfo>
	total: number
}

export interface ListWorkshopRegistrationsRequest {
}
export interface ListWorkshopRegistrationsRequestParams {
	event_id?: string
	limit?: number
	offset?: number
}

export interface ListWorkshopRegistrationsResponse {
	registrations: Array<WorkshopRegistrationInfo>
	total: number
}

export interface LoginRequest {
	email: string
	password: string
}

export interface LoginResponse {
	token: string
	refresh_token: string
	expires_at: string
	user: UserInfo
}

export interface MCPAPIKeyInfo {
	id: string
	name: string
	key_prefix: string // First 8 chars for identification
	scopes: string
	last_used?: string
	expires_at?: string
	created_at: string
}

export interface MarkContactReadRequest {
}
export interface MarkContactReadRequestParams {
}

export interface MarkContactReadResponse {
	success: boolean
}

export interface NavigationItemInfo {
	id: string
	menu_id: string
	parent_id?: string
	label: string
	url?: string
	target?: string
	icon?: string
	sort_order: number
	is_active: boolean
	children?: Array<NavigationItemInfo>
	created_at: string
	updated_at: string
}

export interface NavigationMenuInfo {
	id: string
	name: string
	slug: string
	location: string
	item_count?: number
	items?: Array<NavigationItemInfo>
	created_at: string
	updated_at: string
}

export interface NewsletterResponse {
	success: boolean
	message: string
}

export interface NewsletterSubscribeRequest {
	email: string
	name?: string
	source?: string
	interests?: string
}

export interface OAuthConnectResponse {
	auth_url: string
}

export interface OAuthStatusResponse {
	connected: boolean
	email?: string
	scopes?: string
}

export interface OfferRequest {
	session_id: string // From original checkout
	step_slug: string // Offer step
	accept: boolean // Accept or decline
}

export interface OfferResponse {
	success: boolean
	next_url?: string
	order_item_id?: number
	message?: string
}

export interface OperatorInfo {
	id: string
	symbol: string
	name: string
	description: string
	applies_to: Array<string>
}

export interface OrderInfo {
	id: number
	order_number: string
	contact_id?: string
	email: string
	name: string
	company?: string
	funnel_id?: number
	funnel_step_id?: number
	subtotal_cents: number
	discount_cents: number
	total_cents: number
	currency: string
	stripe_checkout_session_id?: string
	stripe_payment_intent_id?: string
	stripe_customer_id?: string
	payment_status: string
	paid_at?: string
	status: string
	google_calendar_event_id?: string
	google_meet_link?: string
	confirmation_email_sent: boolean
	items?: Array<OrderItemInfo>
	created_at: string
	updated_at: string
}

export interface OrderItemInfo {
	id: number
	order_id: number
	product_id?: number
	item_type: string
	quantity: number
	unit_price_cents: number
	total_cents: number
	product_name: string
	product_config?: { [key: string]: any }
	fulfillment_status: string
	fulfilled_at?: string
	created_at: string
}

export interface OrderRequest {
	email: string
	name?: string
	company?: string
	product_slug?: string // Direct product purchase
	funnel_step_slug?: string // Funnel checkout
	workshop_id?: number // Workshop registration
	include_bump?: boolean // Include order bump product
	amount_cents?: number // Override price (0 = use product price)
	currency?: string // Default: USD
	success_url?: string // Redirect after payment
	cancel_url?: string // Redirect on cancel
	meta?: { [key: string]: string }
}

export interface OrderResponse {
	success: boolean
	order_id?: string
	order_number?: string
	checkout_url?: string // Stripe checkout URL if payment needed
	session_id?: string // Stripe session ID
	message?: string
}

export interface OrgCapability {
	id: string
	domain: string
	capability: string
	name: string
	description?: string
	level_1_behavior?: string
	level_2_behavior?: string
	level_3_behavior?: string
	level_4_behavior?: string
	has_amount_threshold: boolean
	threshold_label?: string
	requires_ai: boolean
	display_order: number
	icon?: string
	autonomy_level: number // 0-4 (or 0-1 for non-AI)
	threshold_amount_cents?: number
}

export interface OrgInfo {
	id: string
	name: string
	slug: string
	api_key: string
	billing_status: string
	plan: string
	max_contacts: number
	stripe_configured: boolean
	from_name?: string
	from_email?: string
	reply_to?: string
	app_url?: string
	created_at: string
}

export interface OrgLLMCredentialsResponse {
	has_anthropic_key: boolean
	has_openai_key: boolean
	has_azure_key: boolean
	azure_endpoint?: string
	default_provider?: string
	anthropic_key_masked?: string
	openai_key_masked?: string
	azure_key_masked?: string
	// Provider enable flags (use platform keys when enabled + no org key)
	anthropic_enabled: boolean
	openai_enabled: boolean
	azure_enabled: boolean
	// Platform provider availability (only show these in UI)
	platform_anthropic_available: boolean
	platform_openai_available: boolean
	platform_azure_available: boolean
	// Complexity routing config
	use_platform_routing: boolean
	default_tier?: string
	complexity_thresholds?: Array<ComplexityThreshold>
	// Available models by provider
	available_models?: Array<AvailableLLMModel>
	// Models enabled for this org
	enabled_models?: Array<string>
}

export interface OrgListResponse {
	organizations: Array<OrgInfo>
	total: number
}

export interface PageTemplateInfo {
	id: string
	name: string
	slug: string
	description?: string
	page_count?: number
	created_at: string
	updated_at: string
}

export interface PauseSequenceRequest {
	email: string
	sequence_slug: string
}

export interface PaymentInfo {
	id: string
	stripe_payment_intent_id: string
	amount_cents: number
	currency: string
	status: string
	description?: string
	receipt_email?: string
	receipt_url?: string
	created_at: string
}

export interface PlatformSettingInfo {
	key: string
	value: string // Decrypted value for display (masked for sensitive)
	category: string
	description?: string
	is_sensitive: boolean
}

export interface PortalRequest {
	customer_id: string
	return_url: string
}

export interface PortalResponse {
	portal_url: string
}

export interface PriceCurrencyInfo {
	id: string
	price_id: string
	currency: string
	unit_amount_cents: number
	compare_at_cents?: number
	created_at: string
}

export interface PriceTierInfo {
	id: string
	price_id: string
	tier_type: string
	up_to?: number
	unit_amount_cents: number
	flat_amount_cents: number
	created_at: string
}

export interface ProcessOfferRequest {
	session_id: string
	step_slug: string
	accept: boolean
}

export interface ProcessOfferResponse {
	success: boolean
	next_url?: string
	order_item_id?: number
	error_message?: string
}

export interface ProductBundleInfo {
	id: string
	org_id: string
	parent_product_id: string
	parent_product_name?: string
	child_product_id: string
	child_product_name?: string
	bundle_type: string
	quantity: number
	discount_percent: number
	required: boolean
	display_order: number
	created_at: string
}

export interface ProductCustomFieldInfo {
	id: string
	org_id: string
	product_id: string
	field_key: string
	field_value?: string
	field_type: string
	created_at: string
	updated_at: string
}

export interface ProductFeature {
	name: string
	description?: string
	included: boolean
}

export interface QuizInfo {
	slug: string
	title: string
	description?: string
	questions: Array<QuizQuestion>
}

export interface QuizOption {
	id: string
	label: string
	value: string
	segments?: Array<string> // Which segments this answer maps to
}

export interface QuizQuestion {
	id: string
	question: string
	type: string // single, multiple, scale
	options?: Array<QuizOption>
	required: boolean
}

export interface QuizSubmitRequest {
	quiz_slug: string
	answers: { [key: string]: string } // question_id -> answer_id
	name?: string
	email?: string
}
export interface QuizSubmitRequestParams {
}

export interface QuizSubmitResponse {
	success: boolean
	segments: Array<string>
	redirect_url?: string
	lead_id?: string
}

export interface RefreshTokenRequest {
	refresh_token: string
}

export interface RefundOrderRequest {
	reason?: string
}
export interface RefundOrderRequestParams {
}

export interface RefundPaymentRequest {
	payment_id: string
	amount_cents?: number
	reason?: string
}
export interface RefundPaymentRequestParams {
}

export interface RefundPaymentResponse {
	success: boolean
	refund_id?: string
	message: string
}

export interface RegenerateApiKeyRequest {
}
export interface RegenerateApiKeyRequestParams {
}

export interface RegisterRequest {
	email: string
	password: string
	first_name: string
	last_name: string
	phone?: string
	token?: string // Optional invitation token (required for agents/partners, not for homeowners)
}

export interface RegisterResponse {
	token: string
	user: UserInfo
}

export interface RegisterWebhookRequest {
	url: string // Webhook endpoint URL
	events: Array<string> // Events to subscribe to
	secret?: string // Shared secret for signature verification
	active?: boolean // Default: true
}

export interface RegisterWebhookResponse {
	success: boolean
	webhook_id: string
	secret: string // Generated if not provided
	message?: string
}

export interface RejectAgentActionRequest {
	reason?: string
}
export interface RejectAgentActionRequestParams {
}

export interface RemoveContactTagsRequest {
	tags: Array<string>
}
export interface RemoveContactTagsRequestParams {
}

export interface RemoveLeadTagRequest {
}
export interface RemoveLeadTagRequestParams {
}

export interface RemoveSubscriberRequest {
}
export interface RemoveSubscriberRequestParams {
}

export interface RemoveTagFromCustomerRequest {
	customer_id: string
	tag_id: string
}

export interface ResetPasswordRequest {
	token: string
	new_password: string
	confirm_password: string
}

export interface ResetPasswordResponse {
	message: string
}

export interface Response {
	success: boolean
	message?: string
}

export interface RestoreDefaultRulesResponse {
	rules_restored: number
	message: string
}

export interface ResumeSequenceRequest {
	email: string
	sequence_slug: string
}

export interface RevenueStatsPoint {
	date: string
	revenue: number // In cents
	order_count: number
	new_subscriptions: number
	churned: number
}

export interface RevokeMCPAPIKeyRequest {
}
export interface RevokeMCPAPIKeyRequestParams {
}

export interface RevokeMCPAPIKeyResponse {
	success: boolean
	message: string
}

export interface RuleAction {
	type: string
	params?: string
}

export interface RuleInfo {
	id: string
	org_id: string
	name: string
	description?: string
	category: string // billing, support, email, customer
	rule_json: string
	entity_type?: string
	entity_id?: string
	enabled: boolean
	salience: number
	compiled_hash?: string
	validation_errors?: Array<ValidationError>
	last_validated_at?: string
	created_at: string
	updated_at: string
}

export interface RuleTemplateInfo {
	id: string
	name: string
	description?: string
	category: string
	rule_json: string
	configurable_params?: Array<string>
	is_recommended: boolean
}

export interface RulesSchemaResponse {
	fact_categories: Array<FactCategoryInfo>
	action_types: Array<ActionTypeInfo>
	operators: Array<OperatorInfo>
}

export interface SDKAuthCustomerInfo {
	id: string
	email: string
	name?: string
	email_verified: boolean
	created_at: string
}

export interface SDKAuthResponse {
	token: string
	refresh_token: string
	expires_at: string
	customer: SDKAuthCustomerInfo
	checkout_url?: string // Stripe checkout URL for paid plans
}

export interface SDKAuthorInfo {
	id: string
	display_name: string
	bio?: string
	avatar_url?: string
	website_url?: string
	twitter_handle?: string
	linkedin_url?: string
	github_handle?: string
}

export interface SDKChangePasswordRequest {
	email: string
	current_password: string
	new_password: string
}

export interface SDKContactInfo {
	id: string
	email: string
	name: string
	phone?: string
	company?: string
	status: string // active, unsubscribed, bounced, complained
	email_verified: boolean
	tags: Array<string>
	lists: Array<string> // List slugs subscribed to
	custom_fields?: { [key: string]: string }
	lead_score?: number
	source?: string
	// Email engagement stats
	emails_sent: number
	emails_opened: number
	emails_clicked: number
	last_email_at?: string
	last_open_at?: string
	last_click_at?: string
	// Dates
	created_at: string
	updated_at: string
}

export interface SDKContentCategoryInfo {
	id: string
	name: string
	slug: string
	description?: string
}

export interface SDKContentPageInfo {
	id: string
	title: string
	slug: string
	content: string
	status: string
	meta_title?: string
	meta_description?: string
	featured_image?: string
	template_name?: string
	template_slug?: string
	created_at: string
	published_at?: string
}

export interface SDKContentPostInfo {
	id: string
	title: string
	slug: string
	content: string
	excerpt?: string
	status: string
	meta_title?: string
	meta_description?: string
	featured_image?: string
	category_name?: string
	category_slug?: string
	author_id?: string
	created_at: string
	published_at?: string
}

export interface SDKCustomerInfo {
	id: string
	email: string
	name: string
	phone?: string
	stripe_customer_id?: string
	status: string // active, inactive
	// Billing summary
	total_spent: number // In cents
	order_count: number
	subscription_count: number
	created_at: string
}

export interface SDKDeleteCustomerRequest {
}
export interface SDKDeleteCustomerRequestParams {
}

export interface SDKForgotPasswordRequest {
	email: string
}

export interface SDKInvoiceInfo {
	id: string
	stripe_invoice_id?: string
	number: string
	status: string // draft, open, paid, void, uncollectible
	amount_due: number // In cents
	amount_paid: number // In cents
	currency: string
	description?: string
	invoice_pdf_url?: string
	hosted_url?: string // Stripe hosted invoice page
	due_date?: string
	paid_at?: string
	created_at: string
}

export interface SDKLoginRequest {
	email: string
	password: string
}

export interface SDKNavigationItem {
	id: string
	label: string
	url?: string
	target?: string
	icon?: string
	is_active: boolean
	children?: Array<SDKNavigationItem>
}

export interface SDKNavigationMenu {
	id: string
	name: string
	slug: string
	location: string
	items: Array<SDKNavigationItem>
}

export interface SDKOrderInfo {
	id: string
	order_number: string
	status: string // pending, paid, fulfilled, refunded, cancelled
	total_cents: number
	currency: string
	items: Array<SDKOrderItem>
	payment_method?: string
	paid_at?: string
	fulfilled_at?: string
	created_at: string
}

export interface SDKOrderItem {
	product_name: string
	quantity: number
	unit_price: number // In cents
	total_price: number // In cents
}

export interface SDKPaymentInfo {
	id: string
	stripe_payment_id?: string
	amount_cents: number
	currency: string
	status: string // succeeded, pending, failed, refunded
	description?: string
	payment_method?: string // card ending, etc.
	receipt_url?: string
	refunded_at?: string
	created_at: string
}

export interface SDKRefreshTokenRequest {
	refresh_token: string
}

export interface SDKRegisterRequest {
	email: string
	password: string
	name?: string
	price_nickname?: string // e.g., "pro", "free", "team-yearly"
	success_url?: string // Redirect after successful payment
	cancel_url?: string // Redirect if checkout cancelled
}

export interface SDKResetPasswordRequest {
	token: string
	password: string
	confirm_password: string
}

export interface SDKSiteSettings {
	site_name?: string
	tagline?: string
	logo_url?: string
	favicon_url?: string
	contact_email?: string
	contact_phone?: string
	contact_address?: string
	social_links?: { [key: string]: string }
	meta_title_template?: string
	meta_description?: string
	og_image_url?: string
}

export interface SDKSubscriptionInfo {
	id: string
	stripe_subscription_id?: string
	product_name: string
	price_name?: string
	status: string // active, past_due, cancelled, trialing, paused
	amount_cents: number
	currency: string
	interval: string // month, year
	current_period_start: string
	current_period_end: string
	cancel_at_period_end: boolean
	trial_end?: string
	created_at: string
}

export interface SDKUpdateCustomerRequest {
	name?: string
	phone?: string
	avatar_url?: string
	status?: string // active, inactive
	metadata?: string // JSON string
}
export interface SDKUpdateCustomerRequestParams {
}

export interface SDKVerifyEmailRequest {
	token: string
}

export interface ScheduleCampaignRequest {
	scheduled_at: string // ISO8601 timestamp
}
export interface ScheduleCampaignRequestParams {
}

export interface ScrollDepthStats {
	page: string
	total_views: number
	avg_scroll_depth: number
	reached_25: number
	reached_50: number
	reached_75: number
	reached_100: number
}

export interface SendCampaignNowRequest {
}
export interface SendCampaignNowRequestParams {
}

export interface SendCustomerEmailRequest {
	subject: string
	body: string
}
export interface SendCustomerEmailRequestParams {
}

export interface SendCustomerEmailResponse {
	success: boolean
	message: string
}

export interface SendEmailRequest {
	to: string // Email address
	template_slug?: string // Use design template
	subject?: string // Required if no template
	body?: string // HTML body, required if no template
	text_body?: string // Plain text fallback
	from_name?: string // Override org default
	from_email?: string // Override org default
	reply_to?: string
	variables?: { [key: string]: string } // Template variables
	tags?: Array<string> // For tracking/filtering
	meta?: { [key: string]: string } // Custom metadata
}

export interface SendEmailResponse {
	success: boolean
	message_id: string // For tracking
	status: string // queued, sent, failed
	message?: string
}

export interface SendPasswordResetRequest {
}
export interface SendPasswordResetRequestParams {
}

export interface SendPasswordResetResponse {
	success: boolean
	message: string
}

export interface SequenceDetailResponse {
	sequence: SequenceInfo
	templates: Array<TemplateInfo>
}

export interface SequenceEnrollmentInfo {
	enrollment_id: string
	sequence_slug: string
	sequence_name: string
	status: string // active, completed, paused, cancelled
	current_step: number
	total_steps: number
	enrolled_at: string
	next_email_at?: string
	completed_at?: string
	emails_sent: number
	emails_opened: number
	emails_clicked: number
}

export interface SequenceInfo {
	id: number
	list_id?: number
	list_slug?: string
	list_name?: string
	slug: string
	name: string
	trigger_event: string
	sequence_type: string // lifecycle or transactional
	is_active: boolean
	send_hour: number // Hour of day (0-23) to send emails, null = use delay from opt-in
	send_timezone: string // Timezone for send_hour (e.g., America/New_York)
	entry_rules?: Array<EntryRuleInfo>
	created_at: string
}

export interface SequenceListResponse {
	sequences: Array<SequenceInfo>
}

export interface SequenceStatsRequest {
}
export interface SequenceStatsRequestParams {
}

export interface SequenceStatsResponse {
	total_subscribers: number
	completed: number
	unsubscribed: number
	emails_sent: number
	emails_pending: number
}

export interface StatsOverviewResponse {
	// Contacts
	total_contacts: number
	new_contacts: number // In period
	active_contacts: number // Engaged recently
	// Email
	emails_sent: number
	emails_delivered: number
	emails_opened: number
	emails_clicked: number
	emails_bounced: number
	open_rate: number // Percentage
	click_rate: number // Percentage
	bounce_rate: number // Percentage
	// Revenue
	total_revenue: number // In cents
	order_count: number
	avg_order_value: number // In cents
	new_subscriptions: number
}

export interface StripeWebhookPath {
}
export interface StripeWebhookPathParams {
}

export interface SubscribeRequest {
	email: string
	name?: string
}
export interface SubscribeRequestParams {
}

export interface SubscriberActionRequest {
}
export interface SubscriberActionRequestParams {
}

export interface SubscriptionInfo {
	id: string
	stripe_subscription_id?: string
	status: string
	current_period_start?: string
	current_period_end?: string
	cancel_at?: string
	canceled_at?: string
	trial_start?: string
	trial_end?: string
	created_at: string
}

export interface SubscriptionRequest {
	customer_id: string
	price_ids: Array<string>
}

export interface SubscriptionResponse {
	id: string
	stripe_subscription_id: string
	status: string
}

export interface SupportTicketInfo {
	id: string
	customer_id: string
	subject: string
	description?: string
	status: string
	priority: string
	assigned_to?: string
	created_at: string
	updated_at: string
	resolved_at?: string
	closed_at?: string
}

export interface SyncBillingResponse {
	products_synced: number
	prices_synced: number
	errors?: Array<string>
}

export interface TagOperationResponse {
	success: boolean
	message: string
}

export interface TemplateInfo {
	id: number
	sequence_id: number
	position: number
	delay_hours: number
	subject: string
	html_body: string
	plain_text?: string
	template_type: string // none, simple, branded
	is_active: boolean
	design_id?: number // Optional reference to email design
	created_at: string
}

export interface TestAIConnectionRequest {
	provider: string // anthropic, openai, or custom
	api_key?: string // Use this key if provided, otherwise use stored key
	base_url?: string // For custom providers
}

export interface TestAIConnectionResponse {
	success: boolean
	provider: string
	latency_ms: number
	models?: Array<string> // List of available models
	message?: string
	error?: string
}

export interface TestOrgLLMConnectionRequest {
	provider: string // anthropic, openai, azure
}
export interface TestOrgLLMConnectionRequestParams {
}

export interface TestOrgLLMConnectionResponse {
	success: boolean
	message: string
	latency?: number // ms
}

export interface TestRuleRequest {
	test_data: string // JSON facts to test against
}
export interface TestRuleRequestParams {
}

export interface TestRuleResponse {
	rules_evaluated: number
	rules_fired: number
	actions: Array<RuleAction>
	errors?: Array<string>
	duration_ms: number
}

export interface TestWebhookRequest {
}
export interface TestWebhookRequestParams {
}

export interface TestWebhookResponse {
	success: boolean
	status_code: number
	response?: string
	error?: string
}

export interface TicketDetailResponse {
	ticket: SupportTicketInfo
	messages: Array<TicketMessageInfo>
	customer: CustomerInfo
}

export interface TicketMessageInfo {
	id: string
	ticket_id: string
	sender_type: string
	sender_id?: string
	message: string
	attachments: Array<string>
	created_at: string
}

export interface TicketStatsResponse {
	total: number
	open: number
	in_progress: number
	waiting: number
	resolved: number
	closed: number
	urgent: number
	high_priority: number
}

export interface TimeSlot {
	time: string
	available: boolean
}

export interface ToggleRuleRequest {
}
export interface ToggleRuleRequestParams {
}

export interface TrackClickRequest {
	token: string
	url: string
}

export interface TrackConfirmRequest {
	token: string
}

export interface TrackConfirmResponse {
	success: boolean
	message?: string
	redirect_url?: string
}

export interface TrackOpenRequest {
	token: string
}

export interface TrackUnsubscribeRequest {
	token: string
}

export interface TransactionalEmailInfo {
	id: number
	org_id: string
	design_id?: number
	name: string
	slug: string
	description?: string
	subject: string
	html_body: string
	plain_text?: string
	from_name?: string
	from_email?: string
	reply_to?: string
	is_active: boolean
	created_at: string
	updated_at: string
}

export interface TransactionalStatsResponse {
	total: number
	sent: number
	delivered: number
	opened: number
	clicked: number
	bounced: number
	failed: number
}

export interface UnenrollSequenceRequest {
	email: string
	sequence_slug?: string // If not provided, unenroll from all
}

export interface UpdateAISettingsRequest {
	claude?: AIProviderConfig
	openai?: AIProviderConfig
	custom_providers?: Array<AIProviderConfig>
}

export interface UpdateAgentConfigRequest {
	enabled?: boolean
	global_autonomy_level?: number
	domain_configs?: Array<AgentDomainConfig>
	system_prompt?: string
	max_actions_per_hour?: number
	require_approval?: Array<string>
	notify_on_action?: boolean
	model_tier?: string // LLM model tier (standard, advanced, fast)
}

export interface UpdateAgentPromptRequest {
	name?: string
	description?: string
	prompt?: string
	is_active?: boolean
}
export interface UpdateAgentPromptRequestParams {
}

export interface UpdateAuthorProfileRequest {
	display_name: string
	bio?: string
	avatar_url?: string
	website_url?: string
	twitter_handle?: string
	linkedin_url?: string
	github_handle?: string
	is_public: boolean
}
export interface UpdateAuthorProfileRequestParams {
}

export interface UpdateBillingPriceRequest {
	nickname?: string
	display_name?: string
	unit_amount_cents?: number
	compare_at_cents?: number
	active?: boolean
	// Provider
	provider?: string
	provider_price_id?: string
	// Billing model
	price_type?: string
	billing_model?: string
	minimum_quantity?: number
	maximum_quantity?: number
	// Trials
	trial_period_days?: number
	// Usage/metered
	included_units?: number
	overage_unit_amount_cents?: number
	// Feature limits
	feature_limits?: { [key: string]: any }
	// Display
	display_order?: number
	highlighted?: boolean
}
export interface UpdateBillingPriceRequestParams {
}

export interface UpdateBillingProductRequest {
	slug?: string
	name?: string
	description?: string
	tagline?: string
	type?: string
	category?: string
	delivery_method?: string
	active?: boolean
	// Provider
	provider?: string
	provider_product_id?: string
	// Marketing
	features?: Array<ProductFeature>
	whats_included?: Array<string>
	who_its_for?: Array<string>
	// Stripe/Tax
	tax_code?: string
	unit_label?: string
	shippable?: boolean
	images?: Array<string>
	// Inventory
	inventory_type?: string
	inventory_count?: number
	low_stock_threshold?: number
	// Display
	display_order?: number
	highlighted?: boolean
	cta_text?: string
	// Related
	email_sequence_id?: number
}
export interface UpdateBillingProductRequestParams {
}

export interface UpdateCampaignRequest {
	name?: string
	subject?: string
	preview_text?: string
	from_name?: string
	from_email?: string
	reply_to?: string
	html_body?: string
	plain_text?: string
	list_ids?: Array<number>
	exclude_list_ids?: Array<number>
	track_opens?: boolean
	track_clicks?: boolean
}
export interface UpdateCampaignRequestParams {
}

export interface UpdateCapabilitiesRequest {
	capabilities: Array<UpdateCapabilityRequest>
}

export interface UpdateCapabilitiesResponse {
	updated: number
}

export interface UpdateCapabilityRequest {
	domain: string
	capability: string
	autonomy_level: number
	threshold_amount_cents?: number
}

export interface UpdateContactRequest {
	name?: string
	phone?: string
	company?: string
	custom_fields?: { [key: string]: string }
}
export interface UpdateContactRequestParams {
}

export interface UpdateContentCategoryRequest {
	name: string
	slug: string
	description?: string
}
export interface UpdateContentCategoryRequestParams {
}

export interface UpdateContentPageRequest {
	template_id?: string
	title: string
	slug: string
	content?: string
	status?: string
	meta_title?: string
	meta_description?: string
	featured_image?: string
}
export interface UpdateContentPageRequestParams {
}

export interface UpdateContentPostRequest {
	category_id?: string
	title: string
	slug: string
	content?: string
	excerpt?: string
	status?: string
	scheduled_at?: string
	meta_title?: string
	meta_description?: string
	featured_image?: string
}
export interface UpdateContentPostRequestParams {
}

export interface UpdateCustomQuoteRequest {
	customer_id?: string
	customer_email?: string
	company_name?: string
	name?: string
	status?: string
	valid_until?: string
	base_product_id?: string
	custom_amount_cents?: number
	currency?: string
	billing_type?: string
	recurring_interval?: string
	recurring_interval_count?: number
	contract_term_months?: number
	custom_features?: Array<string>
	custom_terms?: string
	notes?: string
}
export interface UpdateCustomQuoteRequestParams {
}

export interface UpdateCustomerRequest {
	name?: string
	phone?: string
	status?: string
	metadata?: string
}
export interface UpdateCustomerRequestParams {
}

export interface UpdateCustomerTagRequest {
	name?: string
	color?: string
	description?: string
}
export interface UpdateCustomerTagRequestParams {
}

export interface UpdateEmailDesignRequest {
	name?: string
	slug?: string
	description?: string
	category?: string
	html_body?: string
	plain_text?: string
	is_active?: boolean
}
export interface UpdateEmailDesignRequestParams {
}

export interface UpdateEmailListRequest {
	name?: string
	description?: string
	double_optin?: boolean
	confirmation_subject?: string
	confirmation_body?: string
	confirmation_design_id?: number
}
export interface UpdateEmailListRequestParams {
}

export interface UpdateEmailSettingsRequest {
	smtp_host?: string
	smtp_port?: number
	smtp_user?: string
	smtp_password?: string
}

export interface UpdateEntryRuleRequest {
	priority?: number
	is_active?: boolean
}
export interface UpdateEntryRuleRequestParams {
}

export interface UpdateFunnelRequest {
	slug?: string
	name?: string
	description?: string
	list_id?: number // Email list to subscribe opt-ins to
}
export interface UpdateFunnelRequestParams {
}

export interface UpdateFunnelStepRequest {
	slug?: string
	step_type?: string
	position?: number
	title?: string
	headline?: string
	subheadline?: string
	content?: { [key: string]: any }
	product_id?: string
	order_bump_product_id?: string
	order_bump_headline?: string
	order_bump_description?: string
	next_step_id?: number
	decline_step_id?: number
	success_redirect?: string
	email_sequence_id?: number
	trigger_event?: string
	is_active?: boolean
}
export interface UpdateFunnelStepRequestParams {
}

export interface UpdateGoogleSettingsRequest {
	client_id?: string
	client_secret?: string
}

export interface UpdateLLMModelRequest {
	model_tier?: string
	input_price_per_million_micros?: number
	output_price_per_million_micros?: number
	credit_multiplier?: number
	display_name?: string
	display_order?: number
	is_default?: boolean
	active?: boolean
	// Complexity routing fields
	min_complexity?: number
	max_complexity?: number
	max_context_tokens?: number
	supports_vision?: boolean
	supports_function_calling?: boolean
}
export interface UpdateLLMModelRequestParams {
}

export interface UpdateLeadRequest {
	name?: string
	email?: string
	phone?: string
	company?: string
	status?: string
	assigned_agent_id?: string
	notes?: string
	qualification_score?: number
}
export interface UpdateLeadRequestParams {
}

export interface UpdateLeadStatusRequest {
	status: string
}
export interface UpdateLeadStatusRequestParams {
}

export interface UpdateNavigationItemRequest {
	parent_id?: string
	label: string
	url?: string
	target?: string
	icon?: string
	sort_order: number
	is_active: boolean
}
export interface UpdateNavigationItemRequestParams {
}

export interface UpdateNavigationMenuRequest {
	name: string
	slug: string
	location: string
}
export interface UpdateNavigationMenuRequestParams {
}

export interface UpdateOrgEmailSettingsRequest {
	from_name?: string
	from_email?: string
	reply_to?: string
}
export interface UpdateOrgEmailSettingsRequestParams {
}

export interface UpdateOrgLLMCredentialsRequest {
	anthropic_api_key?: string
	openai_api_key?: string
	azure_api_key?: string
	azure_endpoint?: string
	default_provider?: string
	// Provider enable flags (use platform keys when enabled + no org key)
	anthropic_enabled?: boolean
	openai_enabled?: boolean
	azure_enabled?: boolean
	// Model selection
	enabled_models?: Array<string>
	// Complexity routing config
	use_platform_routing?: boolean
	default_tier?: string
	complexity_thresholds?: Array<ComplexityThreshold>
}
export interface UpdateOrgLLMCredentialsRequestParams {
}

export interface UpdateOrgLLMPricingRequest {
	credit_overrides: { [key: string]: number } // model_id -> credit_multiplier
}
export interface UpdateOrgLLMPricingRequestParams {
}

export interface UpdateOrgRequest {
	name?: string
	plan?: string
	max_contacts?: number
	app_url?: string
}
export interface UpdateOrgRequestParams {
}

export interface UpdateOrgStripeRequest {
	secret_key?: string // Optional for partial updates
	webhook_secret?: string // Optional for partial updates
	publishable_key?: string
}
export interface UpdateOrgStripeRequestParams {
}

export interface UpdatePageTemplateRequest {
	name: string
	slug: string
	description?: string
}
export interface UpdatePageTemplateRequestParams {
}

export interface UpdatePriceCurrencyRequest {
	unit_amount_cents?: number
	compare_at_cents?: number
}
export interface UpdatePriceCurrencyRequestParams {
}

export interface UpdatePriceTierRequest {
	tier_type?: string
	up_to?: number
	unit_amount_cents?: number
	flat_amount_cents?: number
}
export interface UpdatePriceTierRequestParams {
}

export interface UpdateProductBundleRequest {
	bundle_type?: string
	quantity?: number
	discount_percent?: number
	required?: boolean
	display_order?: number
}
export interface UpdateProductBundleRequestParams {
}

export interface UpdateProductCustomFieldRequest {
	field_value?: string
	field_type?: string
}
export interface UpdateProductCustomFieldRequestParams {
}

export interface UpdateQuoteItemRequest {
	product_id?: string
	price_id?: string
	description?: string
	quantity?: number
	unit_amount_cents?: number
	discount_percent?: number
	display_order?: number
}
export interface UpdateQuoteItemRequestParams {
}

export interface UpdateRuleRequest {
	name?: string
	description?: string
	rule_json?: string
	enabled?: boolean
	salience?: number
}
export interface UpdateRuleRequestParams {
}

export interface UpdateSequenceRequest {
	name?: string
	trigger_event?: string
	sequence_type?: string // lifecycle or transactional
	is_active?: boolean
	send_hour?: number // Hour of day (0-23) to send emails
	send_timezone?: string // Timezone for send_hour
}
export interface UpdateSequenceRequestParams {
}

export interface UpdateSettingsResponse {
	success: boolean
	message?: string
}

export interface UpdateTemplateRequest {
	position?: number
	delay_hours?: number
	subject?: string
	html_body?: string
	plain_text?: string
	template_type?: string // none, simple, branded
	is_active?: boolean
	design_id?: number // Optional reference to email design
}
export interface UpdateTemplateRequestParams {
}

export interface UpdateTicketRequest {
	subject?: string
	description?: string
	status?: string
	priority?: string
	assigned_to?: string
}
export interface UpdateTicketRequestParams {
}

export interface UpdateTransactionalEmailRequest {
	name?: string
	slug?: string
	description?: string
	subject?: string
	html_body?: string
	plain_text?: string
	from_name?: string
	from_email?: string
	reply_to?: string
	is_active?: boolean
}
export interface UpdateTransactionalEmailRequestParams {
}

export interface UpdateUserRequest {
	email?: string
	name?: string
	role?: string
	password?: string
}
export interface UpdateUserRequestParams {
}

export interface UpdateWebhookRequest {
	url?: string
	events?: Array<string>
	active?: boolean
}
export interface UpdateWebhookRequestParams {
}

export interface UpdateWorkshopEventRequest {
	product_id?: string
	title?: string
	description?: string
	start_date?: string
	end_date?: string
	start_time?: string
	end_time?: string
	timezone?: string
	location_type?: string
	location_details?: string
	price_cents?: number
	max_seats?: number
	allow_waitlist?: boolean
	waitlist_limit?: number
	whats_included?: Array<string>
	who_its_for?: Array<string>
	agenda?: Array<WorkshopAgendaDay>
	// Funnel integration
	funnel_id?: number
	confirmation_sequence_id?: number
	reminder_sequence_id?: number
	order_bump_product_ids?: Array<string>
}
export interface UpdateWorkshopEventRequestParams {
}

export interface UpdateWorkshopStatusRequest {
	status: string
}
export interface UpdateWorkshopStatusRequestParams {
}

export interface UsageRequest {
	subscription_item_id: string
	quantity: number
}

export interface UserInfo {
	id: string
	email: string
	name: string
	role: string
	active: boolean
	created_at: string
}

export interface UserListResponse {
	users: Array<UserInfo>
	total: number
}

export interface ValidateInvitationRequest {
}
export interface ValidateInvitationRequestParams {
	token: string
}

export interface ValidateInvitationResponse {
	email: string
	first_name: string
	last_name: string
	phone: string
	role: string
	valid: boolean
	message?: string
}

export interface ValidationError {
	line?: number
	column?: number
	message: string
}

export interface VerifyEmailRequest {
}
export interface VerifyEmailRequestParams {
	token: string
}

export interface VerifyEmailResponse {
	message: string
}

export interface WebhookInfo {
	id: string
	url: string
	events: Array<string>
	active: boolean
	created_at: string
	// Stats
	deliveries_total: number
	deliveries_success: number
	deliveries_failed: number
	last_delivery_at?: string
	last_status?: number // HTTP status code
}

export interface WebhookLogInfo {
	id: string
	event: string
	payload: string // JSON string
	status_code: number
	response?: string
	error?: string
	duration_ms: number
	delivered_at: string
}

export interface WorkshopAgendaDay {
	day: string
	title: string
	items: Array<string>
}

export interface WorkshopCheckoutRequest {
	event_slug: string
	name: string
	email: string
	company?: string
	role?: string
}

export interface WorkshopCheckoutResponse {
	success: boolean
	checkout_url?: string
	session_id?: string
	error_message?: string
}

export interface WorkshopEventInfo {
	id: number
	slug: string
	title: string
	description?: string
	start_date: string
	end_date: string
	start_time: string
	end_time: string
	timezone: string
	location_type: string
	location_details?: string
	price_cents: number
	currency: string
	max_seats: number
	seats_remaining: number
	status: string
	whats_included: Array<string>
	who_its_for: Array<string>
	agenda: Array<WorkshopAgendaDay>
	// Product link (workshop is a scheduled instance of a product)
	product_id?: string
	product_slug?: string
	product_name?: string
	// Capacity
	allow_waitlist: boolean
	waitlist_limit?: number
	waitlist_count?: number
	// Funnel integration
	funnel_id?: number
	funnel_slug?: string
	confirmation_sequence_id?: number
	reminder_sequence_id?: number
	order_bump_product_ids?: Array<string>
}

export interface WorkshopQuestionnaireRequest {
	email: string
	company_name: string
	industry: string
	company_size: string
	ai_tools_used: string
	ai_experience: string
	top_challenges: string
	specific_pain_points: string
	desired_outcomes: string
	success_metrics: string
	additional_context?: string
}

export interface WorkshopQuestionnaireResponse {
	success: boolean
	message: string
}

export interface WorkshopRegistrationInfo {
	id: number
	event_id: number
	event_title?: string
	event_start_date?: string
	name: string
	email: string
	company?: string
	role?: string
	amount_cents: number
	currency: string
	payment_status: string
	paid_at?: string
	status: string
	confirmation_email_sent: boolean
	calendar_invite_sent: boolean
	google_meet_link?: string
	created_at: string
}

