#!/bin/bash
# Outlet Setup Script
# Usage: ./setup.sh
#
# This script sets up a fresh Outlet installation:
# - Checks prerequisites (Go, pnpm)
# - Creates configuration files from examples
# - Generates secure secrets
# - Installs dependencies
# - Builds the project

set -e

echo "========================================="
echo "  Outlet Setup Script"
echo "========================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Helper functions
check_command() {
  if command -v "$1" &> /dev/null; then
    echo -e "  ${GREEN}✓${NC} $1 found"
    return 0
  else
    echo -e "  ${RED}✗${NC} $1 not found"
    return 1
  fi
}

generate_secret() {
  openssl rand -hex 32
}

# Step 1: Check prerequisites
echo "Step 1/5: Checking prerequisites..."
MISSING=0

if ! check_command "go"; then
  echo "    Install Go from https://go.dev/dl/"
  MISSING=1
fi

if ! check_command "pnpm"; then
  echo "    Install pnpm: npm install -g pnpm"
  MISSING=1
fi

if ! check_command "openssl"; then
  echo "    openssl is required for generating secrets"
  MISSING=1
fi

if [ $MISSING -eq 1 ]; then
  echo ""
  echo -e "${RED}Please install missing prerequisites and run this script again.${NC}"
  exit 1
fi

echo ""

# Step 2: Create configuration files
echo "Step 2/5: Creating configuration files..."

# Create etc directory if it doesn't exist
mkdir -p etc

# Create .env from example if it doesn't exist
if [ ! -f ".env" ]; then
  if [ -f ".env.example" ]; then
    cp .env.example .env
    echo -e "  ${GREEN}✓${NC} Created .env from .env.example"
  else
    # Create a basic .env file
    cat > .env << 'EOF'
# Outlet Configuration
# See CLAUDE.md for full documentation

# Database
DATABASE_PATH=./data/outlet.db

# JWT Secrets (auto-generated by setup.sh)
JWT_SECRET=
JWT_REFRESH_SECRET=

# Production Mode (set to true for HTTPS/Let's Encrypt)
PRODUCTION_MODE=false

# Domain (required for production mode)
# APP_DOMAIN=yourdomain.com
EOF
    echo -e "  ${GREEN}✓${NC} Created .env with defaults"
  fi
else
  echo -e "  ${YELLOW}→${NC} .env already exists, skipping"
fi

# Create etc/outlet.yaml if it doesn't exist
if [ ! -f "etc/outlet.yaml" ]; then
  cat > etc/outlet.yaml << 'EOF'
Name: outlet
Host: 0.0.0.0
Port: 8888

App:
  ProductionMode: false
  # Domain: yourdomain.com

Database:
  Path: ./data/outlet.db

Auth:
  AccessSecret: REPLACE_WITH_ACCESS_SECRET
  RefreshSecret: REPLACE_WITH_REFRESH_SECRET
  AccessExpire: 3600
  RefreshExpire: 604800
EOF
  echo -e "  ${GREEN}✓${NC} Created etc/outlet.yaml"
else
  echo -e "  ${YELLOW}→${NC} etc/outlet.yaml already exists, skipping"
fi

echo ""

# Step 3: Generate secrets
echo "Step 3/5: Generating secure secrets..."

ACCESS_SECRET=$(generate_secret)
REFRESH_SECRET=$(generate_secret)

# Update .env with secrets if they're empty
if grep -q "^JWT_SECRET=$" .env 2>/dev/null; then
  sed -i '' "s/^JWT_SECRET=$/JWT_SECRET=${ACCESS_SECRET}/" .env
  echo -e "  ${GREEN}✓${NC} Generated JWT_SECRET"
else
  echo -e "  ${YELLOW}→${NC} JWT_SECRET already set"
fi

if grep -q "^JWT_REFRESH_SECRET=$" .env 2>/dev/null; then
  sed -i '' "s/^JWT_REFRESH_SECRET=$/JWT_REFRESH_SECRET=${REFRESH_SECRET}/" .env
  echo -e "  ${GREEN}✓${NC} Generated JWT_REFRESH_SECRET"
else
  echo -e "  ${YELLOW}→${NC} JWT_REFRESH_SECRET already set"
fi

# Update etc/outlet.yaml with secrets if they have placeholder values
if grep -q "REPLACE_WITH_ACCESS_SECRET" etc/outlet.yaml 2>/dev/null; then
  sed -i '' "s/REPLACE_WITH_ACCESS_SECRET/${ACCESS_SECRET}/" etc/outlet.yaml
  echo -e "  ${GREEN}✓${NC} Updated AccessSecret in outlet.yaml"
fi

if grep -q "REPLACE_WITH_REFRESH_SECRET" etc/outlet.yaml 2>/dev/null; then
  sed -i '' "s/REPLACE_WITH_REFRESH_SECRET/${REFRESH_SECRET}/" etc/outlet.yaml
  echo -e "  ${GREEN}✓${NC} Updated RefreshSecret in outlet.yaml"
fi

echo ""

# Step 4: Install dependencies
echo "Step 4/5: Installing dependencies..."

echo "  Installing Go dependencies..."
go mod tidy
echo -e "  ${GREEN}✓${NC} Go dependencies installed"

echo "  Installing frontend dependencies..."
cd app && pnpm install && cd ..
echo -e "  ${GREEN}✓${NC} Frontend dependencies installed"

echo ""

# Step 5: Build the project
echo "Step 5/5: Building project..."

echo "  Building backend..."
make build
echo -e "  ${GREEN}✓${NC} Backend built"

echo "  Building frontend..."
cd app && pnpm build && cd ..
echo -e "  ${GREEN}✓${NC} Frontend built"

# Create data directory
mkdir -p data
echo -e "  ${GREEN}✓${NC} Data directory created"

echo ""
echo "========================================="
echo -e "  ${GREEN}✅ Outlet setup complete!${NC}"
echo "========================================="
echo ""
echo "To start Outlet:"
echo ""
echo "  Development mode (with hot reload):"
echo "    Terminal 1: make run"
echo "    Terminal 2: cd app && pnpm dev"
echo "    Open http://localhost:5173"
echo ""
echo "  Production mode:"
echo "    ./bin/outlet"
echo "    Open http://localhost:8888"
echo ""
echo "On first launch, you'll be redirected to /setup to:"
echo "  1. Create your admin account"
echo "  2. Configure email settings"
echo ""
