// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	adminapikeys "github.com/outlet-sh/outlet/internal/handler/admin/apikeys"
	adminauth "github.com/outlet-sh/outlet/internal/handler/admin/auth"
	adminbackup "github.com/outlet-sh/outlet/internal/handler/admin/backup"
	adminblocklist "github.com/outlet-sh/outlet/internal/handler/admin/blocklist"
	admincampaigns "github.com/outlet-sh/outlet/internal/handler/admin/campaigns"
	admindesigns "github.com/outlet-sh/outlet/internal/handler/admin/designs"
	adminemailconfig "github.com/outlet-sh/outlet/internal/handler/admin/emailconfig"
	admingdpr "github.com/outlet-sh/outlet/internal/handler/admin/gdpr"
	adminhousekeeping "github.com/outlet-sh/outlet/internal/handler/admin/housekeeping"
	adminimports "github.com/outlet-sh/outlet/internal/handler/admin/imports"
	adminlists "github.com/outlet-sh/outlet/internal/handler/admin/lists"
	adminorganizations "github.com/outlet-sh/outlet/internal/handler/admin/organizations"
	adminsequences "github.com/outlet-sh/outlet/internal/handler/admin/sequences"
	adminsettings "github.com/outlet-sh/outlet/internal/handler/admin/settings"
	adminsubscribers "github.com/outlet-sh/outlet/internal/handler/admin/subscribers"
	adminsystem "github.com/outlet-sh/outlet/internal/handler/admin/system"
	admintransactional "github.com/outlet-sh/outlet/internal/handler/admin/transactional"
	adminusers "github.com/outlet-sh/outlet/internal/handler/admin/users"
	adminwebhooks "github.com/outlet-sh/outlet/internal/handler/admin/webhooks"
	auth "github.com/outlet-sh/outlet/internal/handler/auth"
	public "github.com/outlet-sh/outlet/internal/handler/public"
	sdk "github.com/outlet-sh/outlet/internal/handler/sdk"
	sdkcontacts "github.com/outlet-sh/outlet/internal/handler/sdk/contacts"
	sdkemails "github.com/outlet-sh/outlet/internal/handler/sdk/emails"
	sdksequences "github.com/outlet-sh/outlet/internal/handler/sdk/sequences"
	sdkstats "github.com/outlet-sh/outlet/internal/handler/sdk/stats"
	sdktracking "github.com/outlet-sh/outlet/internal/handler/sdk/tracking"
	sdkwebhooks "github.com/outlet-sh/outlet/internal/handler/sdk/webhooks"
	"github.com/outlet-sh/outlet/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api-keys",
					Handler: adminapikeys.ListMCPAPIKeysHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/api-keys",
					Handler: adminapikeys.CreateMCPAPIKeyHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api-keys/:id",
					Handler: adminapikeys.RevokeMCPAPIKeyHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/auth/logout",
					Handler: adminauth.LogoutHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/auth/me",
					Handler: adminauth.GetCurrentUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: adminbackup.CreateBackupHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: adminbackup.ListBackupsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: adminbackup.GetBackupHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: adminbackup.DeleteBackupHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/download",
					Handler: adminbackup.DownloadBackupHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/settings",
					Handler: adminbackup.GetBackupSettingsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/settings",
					Handler: adminbackup.UpdateBackupSettingsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin/backup"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/blocked-domains",
					Handler: adminblocklist.ListBlockedDomainsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/blocked-domains",
					Handler: adminblocklist.CreateBlockedDomainHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/blocked-domains/:id",
					Handler: adminblocklist.DeleteBlockedDomainHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/blocked-domains/bulk",
					Handler: adminblocklist.BulkBlockDomainsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/suppression-list",
					Handler: adminblocklist.ListSuppressedEmailsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/suppression-list",
					Handler: adminblocklist.AddSuppressedEmailHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/suppression-list",
					Handler: adminblocklist.ClearSuppressionListHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/suppression-list/:id",
					Handler: adminblocklist.DeleteSuppressedEmailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/suppression-list/bulk",
					Handler: adminblocklist.BulkSuppressEmailsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/campaigns",
					Handler: admincampaigns.ListCampaignsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/campaigns",
					Handler: admincampaigns.CreateCampaignHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/campaigns/:id",
					Handler: admincampaigns.GetCampaignHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/campaigns/:id",
					Handler: admincampaigns.UpdateCampaignHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/campaigns/:id",
					Handler: admincampaigns.DeleteCampaignHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/campaigns/:id/schedule",
					Handler: admincampaigns.ScheduleCampaignHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/campaigns/:id/send",
					Handler: admincampaigns.SendCampaignNowHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/campaigns/:id/stats",
					Handler: admincampaigns.GetCampaignStatsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/email-designs",
					Handler: admindesigns.ListEmailDesignsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/email-designs",
					Handler: admindesigns.CreateEmailDesignHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/email-designs/:id",
					Handler: admindesigns.GetEmailDesignHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/email-designs/:id",
					Handler: admindesigns.UpdateEmailDesignHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/email-designs/:id",
					Handler: admindesigns.DeleteEmailDesignHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:org_id/domain-identities",
					Handler: adminemailconfig.ListDomainIdentitiesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:org_id/domain-identities",
					Handler: adminemailconfig.CreateDomainIdentityHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:org_id/domain-identities/:id",
					Handler: adminemailconfig.GetDomainIdentityHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:org_id/domain-identities/:id",
					Handler: adminemailconfig.DeleteDomainIdentityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:org_id/domain-identities/:id/refresh",
					Handler: adminemailconfig.RefreshDomainIdentityHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:org_id/email-config",
					Handler: adminemailconfig.GetOrgEmailConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:org_id/email-config",
					Handler: adminemailconfig.UpdateOrgEmailConfigHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:org_id/email-config/detect-quota",
					Handler: adminemailconfig.DetectSESQuotaHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin/organizations"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/contacts/:contact_id",
					Handler: admingdpr.DeleteContactDataHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/contacts/:contact_id/consent",
					Handler: admingdpr.GetContactConsentHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/contacts/:contact_id/consent",
					Handler: admingdpr.UpdateContactConsentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/contacts/:contact_id/export",
					Handler: admingdpr.ExportContactDataHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/contacts/lookup",
					Handler: admingdpr.LookupContactHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin/gdpr"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/inactive",
					Handler: adminhousekeeping.HousekeepingInactiveHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/unconfirmed",
					Handler: adminhousekeeping.HousekeepingUnconfirmedHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin/housekeeping"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/import-jobs",
					Handler: adminimports.ListImportJobsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/import-jobs/:id",
					Handler: adminimports.GetImportJobHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/import-jobs/:id/cancel",
					Handler: adminimports.CancelImportJobHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/email-stats",
					Handler: adminlists.GetEmailDashboardStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/lists",
					Handler: adminlists.ListListsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/lists",
					Handler: adminlists.CreateListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/lists/:id",
					Handler: adminlists.GetListHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/lists/:id",
					Handler: adminlists.UpdateListHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/lists/:id",
					Handler: adminlists.DeleteListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/lists/:id/embed-code",
					Handler: adminlists.GetListEmbedCodeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/lists/:id/stats",
					Handler: adminlists.GetListStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/lists/:id/subscribers",
					Handler: adminlists.ListListSubscribersHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/lists/:id/subscribers/:subscriberId",
					Handler: adminlists.RemoveListSubscriberHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/lists/:id/subscribers/:subscriberId",
					Handler: adminlists.GetSubscriberDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/lists/:listId/custom-fields",
					Handler: adminlists.ListCustomFieldsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/lists/:listId/custom-fields",
					Handler: adminlists.CreateCustomFieldHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/lists/:listId/custom-fields/:fieldId",
					Handler: adminlists.GetCustomFieldHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/lists/:listId/custom-fields/:fieldId",
					Handler: adminlists.UpdateCustomFieldHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/lists/:listId/custom-fields/:fieldId",
					Handler: adminlists.DeleteCustomFieldHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/organizations",
					Handler: adminorganizations.ListOrganizationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/organizations",
					Handler: adminorganizations.CreateOrganizationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/organizations/:id",
					Handler: adminorganizations.GetOrganizationHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/organizations/:id",
					Handler: adminorganizations.UpdateOrganizationHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/organizations/:id",
					Handler: adminorganizations.DeleteOrganizationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/organizations/:id/dashboard-stats",
					Handler: adminorganizations.GetDashboardStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/organizations/:id/email",
					Handler: adminorganizations.UpdateOrgEmailSettingsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/organizations/:id/regenerate-key",
					Handler: adminorganizations.RegenerateOrgApiKeyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/organizations/slug/:slug",
					Handler: adminorganizations.GetOrganizationBySlugHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/email-queue",
					Handler: adminsequences.ListEmailQueueHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/email-queue/:id/cancel",
					Handler: adminsequences.CancelEmailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/entry-rules",
					Handler: adminsequences.CreateEntryRuleHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/entry-rules/:id",
					Handler: adminsequences.UpdateEntryRuleHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/entry-rules/:id",
					Handler: adminsequences.DeleteEntryRuleHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/sequences",
					Handler: adminsequences.ListSequencesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/sequences",
					Handler: adminsequences.CreateSequenceHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/sequences/:id",
					Handler: adminsequences.GetSequenceHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/sequences/:id",
					Handler: adminsequences.UpdateSequenceHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/sequences/:id",
					Handler: adminsequences.DeleteSequenceHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/sequences/:id/stats",
					Handler: adminsequences.GetSequenceStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/templates",
					Handler: adminsequences.CreateTemplateHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/templates/:id",
					Handler: adminsequences.UpdateTemplateHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/templates/:id",
					Handler: adminsequences.DeleteTemplateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: adminsettings.GetPlatformSettingsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:category",
					Handler: adminsettings.GetPlatformSettingsByCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/email",
					Handler: adminsettings.UpdateEmailSettingsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/ses-quota",
					Handler: adminsettings.GetPlatformSESQuotaHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/setup-status",
					Handler: adminsettings.GetSetupStatusHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin/settings"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/subscribers/:id/block",
					Handler: adminsubscribers.BlockSubscriberHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/subscribers/:id/resubscribe",
					Handler: adminsubscribers.ResubscribeSubscriberHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/subscribers/:id/unblock",
					Handler: adminsubscribers.UnblockSubscriberHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/subscribers/:id/unsubscribe",
					Handler: adminsubscribers.UnsubscribeSubscriberHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/subscribers/:id/verify",
					Handler: adminsubscribers.VerifySubscriberHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/updates/check",
					Handler: adminsystem.CheckForUpdatesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/version",
					Handler: adminsystem.GetVersionHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin/system"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/transactional-emails",
					Handler: admintransactional.ListTransactionalEmailsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/transactional-emails",
					Handler: admintransactional.CreateTransactionalEmailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/transactional-emails/:id",
					Handler: admintransactional.GetTransactionalEmailHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/transactional-emails/:id",
					Handler: admintransactional.UpdateTransactionalEmailHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/transactional-emails/:id",
					Handler: admintransactional.DeleteTransactionalEmailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/transactional-emails/:id/stats",
					Handler: admintransactional.GetTransactionalEmailStatsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/users",
					Handler: adminusers.ListUsersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/users",
					Handler: adminusers.CreateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/:id",
					Handler: adminusers.GetUserHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/users/:id",
					Handler: adminusers.UpdateUserHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/users/:id",
					Handler: adminusers.DeleteUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: adminwebhooks.AdminListWebhooksHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: adminwebhooks.AdminCreateWebhookHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: adminwebhooks.AdminGetWebhookHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: adminwebhooks.AdminUpdateWebhookHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: adminwebhooks.AdminDeleteWebhookHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/logs",
					Handler: adminwebhooks.AdminListWebhookLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/test",
					Handler: adminwebhooks.AdminTestWebhookHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/admin/webhooks"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthRateLimit},
			[]rest.Route{
				{
					// Request password reset
					Method:  http.MethodPost,
					Path:    "/auth/forgot-password",
					Handler: auth.ForgotPasswordHandler(serverCtx),
				},
				{
					// User login
					Method:  http.MethodPost,
					Path:    "/auth/login",
					Handler: auth.LoginHandler(serverCtx),
				},
				{
					// Refresh access token using refresh token
					Method:  http.MethodPost,
					Path:    "/auth/refresh",
					Handler: auth.RefreshTokenHandler(serverCtx),
				},
				{
					// User registration
					Method:  http.MethodPost,
					Path:    "/auth/register",
					Handler: auth.RegisterHandler(serverCtx),
				},
				{
					// Reset password with token
					Method:  http.MethodPost,
					Path:    "/auth/reset-password",
					Handler: auth.ResetPasswordHandler(serverCtx),
				},
				{
					// Validate invitation token and get user details
					Method:  http.MethodGet,
					Path:    "/auth/validate-invitation",
					Handler: auth.ValidateInvitationHandler(serverCtx),
				},
				{
					// Verify email address
					Method:  http.MethodGet,
					Path:    "/auth/verify-email",
					Handler: auth.VerifyEmailHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: public.HealthHandler(serverCtx),
			},
			{
				// Create initial admin account (only works when no admin exists)
				Method:  http.MethodPost,
				Path:    "/setup/admin",
				Handler: public.CreateInitialAdminHandler(serverCtx),
			},
			{
				// Check if initial setup is required
				Method:  http.MethodGet,
				Path:    "/setup/status",
				Handler: public.GetPublicSetupStatusHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.APIKeyAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/contacts",
					Handler: sdk.CreateContactHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/lists/:slug/subscribe",
					Handler: sdk.SubscribeToListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/lists/:slug/unsubscribe",
					Handler: sdk.UnsubscribeFromListHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sdk/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.APIKeyAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: sdkcontacts.GetContactHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: sdkcontacts.UpdateContactHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/activity",
					Handler: sdkcontacts.ListContactActivityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/tags",
					Handler: sdkcontacts.AddContactTagsHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/tags",
					Handler: sdkcontacts.RemoveContactTagsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/unsubscribe",
					Handler: sdkcontacts.GlobalUnsubscribeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sdk/v1/contacts"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.APIKeyAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: sdkemails.SendEmailHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:messageId",
					Handler: sdkemails.GetEmailStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:messageId/events",
					Handler: sdkemails.ListEmailEventsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sdk/v1/emails"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.APIKeyAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/enroll",
					Handler: sdksequences.EnrollInSequenceHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/enrollments",
					Handler: sdksequences.GetSequenceEnrollmentsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/pause",
					Handler: sdksequences.PauseSequenceEnrollmentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/resume",
					Handler: sdksequences.ResumeSequenceEnrollmentHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/unenroll",
					Handler: sdksequences.UnenrollFromSequenceHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sdk/v1/sequences"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.APIKeyAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/contacts",
					Handler: sdkstats.GetContactStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/emails",
					Handler: sdkstats.GetEmailStatsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/overview",
					Handler: sdkstats.GetStatsOverviewHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sdk/v1/stats"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.APIKeyAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/click",
					Handler: sdktracking.TrackClickHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/confirm",
					Handler: sdktracking.TrackConfirmHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/open",
					Handler: sdktracking.TrackOpenHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/unsubscribe",
					Handler: sdktracking.TrackUnsubscribeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sdk/v1/tracking"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.APIKeyAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: sdkwebhooks.RegisterWebhookHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: sdkwebhooks.ListWebhooksHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: sdkwebhooks.GetWebhookHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: sdkwebhooks.UpdateWebhookHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: sdkwebhooks.DeleteWebhookHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id/logs",
					Handler: sdkwebhooks.ListWebhookLogsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id/test",
					Handler: sdkwebhooks.TestWebhookHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/sdk/v1/webhooks"),
	)
}
