// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact_tags.sql

package db

import (
	"context"
	"database/sql"
)

const addContactTag = `-- name: AddContactTag :one
INSERT INTO contact_tags (contact_id, tag, created_at)
VALUES (?1, ?2, datetime('now'))
ON CONFLICT (contact_id, tag) DO NOTHING
RETURNING id, contact_id, tag, created_at
`

type AddContactTagParams struct {
	ContactID sql.NullString `json:"contact_id"`
	Tag       string         `json:"tag"`
}

func (q *Queries) AddContactTag(ctx context.Context, arg AddContactTagParams) (ContactTag, error) {
	row := q.db.QueryRowContext(ctx, addContactTag, arg.ContactID, arg.Tag)
	var i ContactTag
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Tag,
		&i.CreatedAt,
	)
	return i, err
}

const countContactsByTag = `-- name: CountContactsByTag :one
SELECT COUNT(DISTINCT contact_id) as count
FROM contact_tags
WHERE tag = ?1
`

func (q *Queries) CountContactsByTag(ctx context.Context, tag string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContactsByTag, tag)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getContactTags = `-- name: GetContactTags :many
SELECT id, contact_id, tag, created_at
FROM contact_tags
WHERE contact_id = ?1
ORDER BY created_at
`

func (q *Queries) GetContactTags(ctx context.Context, contactID sql.NullString) ([]ContactTag, error) {
	rows, err := q.db.QueryContext(ctx, getContactTags, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactTag
	for rows.Next() {
		var i ContactTag
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.Tag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactsByTag = `-- name: GetContactsByTag :many
SELECT c.id, c.org_id, c.name, c.email, c.source, c.created_at, c.updated_at, c.email_verified, c.verification_token, c.verification_sent_at, c.verified_at, c.unsubscribed_at, c.blocked_at, c.status, c.gdpr_consent, c.gdpr_consent_at
FROM contacts c
JOIN contact_tags ct ON ct.contact_id = c.id
WHERE ct.tag = ?1
ORDER BY c.created_at DESC
LIMIT ?3 OFFSET ?2
`

type GetContactsByTagParams struct {
	Tag        string `json:"tag"`
	PageOffset int64  `json:"page_offset"`
	PageSize   int64  `json:"page_size"`
}

func (q *Queries) GetContactsByTag(ctx context.Context, arg GetContactsByTagParams) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, getContactsByTag, arg.Tag, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Email,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmailVerified,
			&i.VerificationToken,
			&i.VerificationSentAt,
			&i.VerifiedAt,
			&i.UnsubscribedAt,
			&i.BlockedAt,
			&i.Status,
			&i.GdprConsent,
			&i.GdprConsentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasContactTag = `-- name: HasContactTag :one
SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END as has_tag
FROM contact_tags WHERE contact_id = ?1 AND tag = ?2
`

type HasContactTagParams struct {
	ContactID sql.NullString `json:"contact_id"`
	Tag       string         `json:"tag"`
}

func (q *Queries) HasContactTag(ctx context.Context, arg HasContactTagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasContactTag, arg.ContactID, arg.Tag)
	var has_tag int64
	err := row.Scan(&has_tag)
	return has_tag, err
}

const listAllContactTags = `-- name: ListAllContactTags :many
SELECT tag, COUNT(*) as count
FROM contact_tags
GROUP BY tag
ORDER BY count DESC
`

type ListAllContactTagsRow struct {
	Tag   string `json:"tag"`
	Count int64  `json:"count"`
}

func (q *Queries) ListAllContactTags(ctx context.Context) ([]ListAllContactTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllContactTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllContactTagsRow
	for rows.Next() {
		var i ListAllContactTagsRow
		if err := rows.Scan(&i.Tag, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeContactTag = `-- name: RemoveContactTag :exec
DELETE FROM contact_tags
WHERE contact_id = ?1 AND tag = ?2
`

type RemoveContactTagParams struct {
	ContactID sql.NullString `json:"contact_id"`
	Tag       string         `json:"tag"`
}

func (q *Queries) RemoveContactTag(ctx context.Context, arg RemoveContactTagParams) error {
	_, err := q.db.ExecContext(ctx, removeContactTag, arg.ContactID, arg.Tag)
	return err
}
