// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: custom_fields.sql

package db

import (
	"context"
	"database/sql"
)

const bulkCreateCustomFieldValues = `-- name: BulkCreateCustomFieldValues :exec
INSERT INTO custom_field_values (id, subscriber_id, field_id, value, created_at, updated_at)
SELECT
    lower(hex(randomblob(16))),
    ?1,
    cf.id,
    json_extract(?2, '$.' || cf.field_key),
    datetime('now'),
    datetime('now')
FROM custom_fields cf
WHERE cf.list_id = ?3
  AND json_extract(?2, '$.' || cf.field_key) IS NOT NULL
ON CONFLICT(subscriber_id, field_id) DO UPDATE SET
    value = excluded.value,
    updated_at = datetime('now')
`

type BulkCreateCustomFieldValuesParams struct {
	SubscriberID string      `json:"subscriber_id"`
	ValuesJson   interface{} `json:"values_json"`
	ListID       int64       `json:"list_id"`
}

// Used when subscribing with multiple field values at once
func (q *Queries) BulkCreateCustomFieldValues(ctx context.Context, arg BulkCreateCustomFieldValuesParams) error {
	_, err := q.db.ExecContext(ctx, bulkCreateCustomFieldValues, arg.SubscriberID, arg.ValuesJson, arg.ListID)
	return err
}

const countCustomFieldsByList = `-- name: CountCustomFieldsByList :one
SELECT COUNT(*) FROM custom_fields WHERE list_id = ?1
`

func (q *Queries) CountCustomFieldsByList(ctx context.Context, listID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCustomFieldsByList, listID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomField = `-- name: CreateCustomField :one
INSERT INTO custom_fields (id, list_id, name, field_key, field_type, options, required, default_value, placeholder, sort_order, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, datetime('now'), datetime('now'))
RETURNING id, list_id, name, field_key, field_type, options, required, default_value, placeholder, sort_order, created_at, updated_at
`

type CreateCustomFieldParams struct {
	ID           string         `json:"id"`
	ListID       int64          `json:"list_id"`
	Name         string         `json:"name"`
	FieldKey     string         `json:"field_key"`
	FieldType    string         `json:"field_type"`
	Options      sql.NullString `json:"options"`
	Required     int64          `json:"required"`
	DefaultValue sql.NullString `json:"default_value"`
	Placeholder  sql.NullString `json:"placeholder"`
	SortOrder    int64          `json:"sort_order"`
}

func (q *Queries) CreateCustomField(ctx context.Context, arg CreateCustomFieldParams) (CustomField, error) {
	row := q.db.QueryRowContext(ctx, createCustomField,
		arg.ID,
		arg.ListID,
		arg.Name,
		arg.FieldKey,
		arg.FieldType,
		arg.Options,
		arg.Required,
		arg.DefaultValue,
		arg.Placeholder,
		arg.SortOrder,
	)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Name,
		&i.FieldKey,
		&i.FieldType,
		&i.Options,
		&i.Required,
		&i.DefaultValue,
		&i.Placeholder,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomFieldValue = `-- name: CreateCustomFieldValue :one

INSERT INTO custom_field_values (id, subscriber_id, field_id, value, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, datetime('now'), datetime('now'))
RETURNING id, subscriber_id, field_id, value, created_at, updated_at
`

type CreateCustomFieldValueParams struct {
	ID           string         `json:"id"`
	SubscriberID string         `json:"subscriber_id"`
	FieldID      string         `json:"field_id"`
	Value        sql.NullString `json:"value"`
}

// Custom Field Values
func (q *Queries) CreateCustomFieldValue(ctx context.Context, arg CreateCustomFieldValueParams) (CustomFieldValue, error) {
	row := q.db.QueryRowContext(ctx, createCustomFieldValue,
		arg.ID,
		arg.SubscriberID,
		arg.FieldID,
		arg.Value,
	)
	var i CustomFieldValue
	err := row.Scan(
		&i.ID,
		&i.SubscriberID,
		&i.FieldID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomField = `-- name: DeleteCustomField :exec
DELETE FROM custom_fields WHERE id = ?1
`

func (q *Queries) DeleteCustomField(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomField, id)
	return err
}

const deleteCustomFieldValue = `-- name: DeleteCustomFieldValue :exec
DELETE FROM custom_field_values WHERE subscriber_id = ?1 AND field_id = ?2
`

type DeleteCustomFieldValueParams struct {
	SubscriberID string `json:"subscriber_id"`
	FieldID      string `json:"field_id"`
}

func (q *Queries) DeleteCustomFieldValue(ctx context.Context, arg DeleteCustomFieldValueParams) error {
	_, err := q.db.ExecContext(ctx, deleteCustomFieldValue, arg.SubscriberID, arg.FieldID)
	return err
}

const deleteCustomFieldValuesBySubscriber = `-- name: DeleteCustomFieldValuesBySubscriber :exec
DELETE FROM custom_field_values WHERE subscriber_id = ?1
`

func (q *Queries) DeleteCustomFieldValuesBySubscriber(ctx context.Context, subscriberID string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomFieldValuesBySubscriber, subscriberID)
	return err
}

const deleteCustomFieldsByList = `-- name: DeleteCustomFieldsByList :exec
DELETE FROM custom_fields WHERE list_id = ?1
`

func (q *Queries) DeleteCustomFieldsByList(ctx context.Context, listID int64) error {
	_, err := q.db.ExecContext(ctx, deleteCustomFieldsByList, listID)
	return err
}

const getCustomField = `-- name: GetCustomField :one
SELECT id, list_id, name, field_key, field_type, options, required, default_value, placeholder, sort_order, created_at, updated_at FROM custom_fields WHERE id = ?1
`

func (q *Queries) GetCustomField(ctx context.Context, id string) (CustomField, error) {
	row := q.db.QueryRowContext(ctx, getCustomField, id)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Name,
		&i.FieldKey,
		&i.FieldType,
		&i.Options,
		&i.Required,
		&i.DefaultValue,
		&i.Placeholder,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomFieldByKey = `-- name: GetCustomFieldByKey :one
SELECT id, list_id, name, field_key, field_type, options, required, default_value, placeholder, sort_order, created_at, updated_at FROM custom_fields WHERE list_id = ?1 AND field_key = ?2
`

type GetCustomFieldByKeyParams struct {
	ListID   int64  `json:"list_id"`
	FieldKey string `json:"field_key"`
}

func (q *Queries) GetCustomFieldByKey(ctx context.Context, arg GetCustomFieldByKeyParams) (CustomField, error) {
	row := q.db.QueryRowContext(ctx, getCustomFieldByKey, arg.ListID, arg.FieldKey)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Name,
		&i.FieldKey,
		&i.FieldType,
		&i.Options,
		&i.Required,
		&i.DefaultValue,
		&i.Placeholder,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomFieldValue = `-- name: GetCustomFieldValue :one
SELECT id, subscriber_id, field_id, value, created_at, updated_at FROM custom_field_values WHERE subscriber_id = ?1 AND field_id = ?2
`

type GetCustomFieldValueParams struct {
	SubscriberID string `json:"subscriber_id"`
	FieldID      string `json:"field_id"`
}

func (q *Queries) GetCustomFieldValue(ctx context.Context, arg GetCustomFieldValueParams) (CustomFieldValue, error) {
	row := q.db.QueryRowContext(ctx, getCustomFieldValue, arg.SubscriberID, arg.FieldID)
	var i CustomFieldValue
	err := row.Scan(
		&i.ID,
		&i.SubscriberID,
		&i.FieldID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriberCustomFieldsForMerge = `-- name: GetSubscriberCustomFieldsForMerge :many
SELECT cf.field_key, cfv.value
FROM custom_field_values cfv
JOIN custom_fields cf ON cf.id = cfv.field_id
WHERE cfv.subscriber_id = ?1
`

type GetSubscriberCustomFieldsForMergeRow struct {
	FieldKey string         `json:"field_key"`
	Value    sql.NullString `json:"value"`
}

// Returns field_key -> value pairs for use in email merge tags
func (q *Queries) GetSubscriberCustomFieldsForMerge(ctx context.Context, subscriberID string) ([]GetSubscriberCustomFieldsForMergeRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriberCustomFieldsForMerge, subscriberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubscriberCustomFieldsForMergeRow
	for rows.Next() {
		var i GetSubscriberCustomFieldsForMergeRow
		if err := rows.Scan(&i.FieldKey, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomFieldValuesBySubscriber = `-- name: ListCustomFieldValuesBySubscriber :many
SELECT cfv.id, cfv.subscriber_id, cfv.field_id, cfv.value, cfv.created_at, cfv.updated_at, cf.name, cf.field_key, cf.field_type
FROM custom_field_values cfv
JOIN custom_fields cf ON cf.id = cfv.field_id
WHERE cfv.subscriber_id = ?1
ORDER BY cf.sort_order ASC
`

type ListCustomFieldValuesBySubscriberRow struct {
	ID           string         `json:"id"`
	SubscriberID string         `json:"subscriber_id"`
	FieldID      string         `json:"field_id"`
	Value        sql.NullString `json:"value"`
	CreatedAt    sql.NullString `json:"created_at"`
	UpdatedAt    sql.NullString `json:"updated_at"`
	Name         string         `json:"name"`
	FieldKey     string         `json:"field_key"`
	FieldType    string         `json:"field_type"`
}

func (q *Queries) ListCustomFieldValuesBySubscriber(ctx context.Context, subscriberID string) ([]ListCustomFieldValuesBySubscriberRow, error) {
	rows, err := q.db.QueryContext(ctx, listCustomFieldValuesBySubscriber, subscriberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomFieldValuesBySubscriberRow
	for rows.Next() {
		var i ListCustomFieldValuesBySubscriberRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriberID,
			&i.FieldID,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.FieldKey,
			&i.FieldType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomFieldsByList = `-- name: ListCustomFieldsByList :many
SELECT id, list_id, name, field_key, field_type, options, required, default_value, placeholder, sort_order, created_at, updated_at FROM custom_fields WHERE list_id = ?1 ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListCustomFieldsByList(ctx context.Context, listID int64) ([]CustomField, error) {
	rows, err := q.db.QueryContext(ctx, listCustomFieldsByList, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomField
	for rows.Next() {
		var i CustomField
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.Name,
			&i.FieldKey,
			&i.FieldType,
			&i.Options,
			&i.Required,
			&i.DefaultValue,
			&i.Placeholder,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomField = `-- name: UpdateCustomField :one
UPDATE custom_fields
SET name = ?1,
    field_key = ?2,
    field_type = ?3,
    options = ?4,
    required = ?5,
    default_value = ?6,
    placeholder = ?7,
    sort_order = ?8,
    updated_at = datetime('now')
WHERE id = ?9
RETURNING id, list_id, name, field_key, field_type, options, required, default_value, placeholder, sort_order, created_at, updated_at
`

type UpdateCustomFieldParams struct {
	Name         string         `json:"name"`
	FieldKey     string         `json:"field_key"`
	FieldType    string         `json:"field_type"`
	Options      sql.NullString `json:"options"`
	Required     int64          `json:"required"`
	DefaultValue sql.NullString `json:"default_value"`
	Placeholder  sql.NullString `json:"placeholder"`
	SortOrder    int64          `json:"sort_order"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateCustomField(ctx context.Context, arg UpdateCustomFieldParams) (CustomField, error) {
	row := q.db.QueryRowContext(ctx, updateCustomField,
		arg.Name,
		arg.FieldKey,
		arg.FieldType,
		arg.Options,
		arg.Required,
		arg.DefaultValue,
		arg.Placeholder,
		arg.SortOrder,
		arg.ID,
	)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.Name,
		&i.FieldKey,
		&i.FieldType,
		&i.Options,
		&i.Required,
		&i.DefaultValue,
		&i.Placeholder,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCustomFieldValue = `-- name: UpsertCustomFieldValue :one
INSERT INTO custom_field_values (id, subscriber_id, field_id, value, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, datetime('now'), datetime('now'))
ON CONFLICT(subscriber_id, field_id) DO UPDATE SET
    value = excluded.value,
    updated_at = datetime('now')
RETURNING id, subscriber_id, field_id, value, created_at, updated_at
`

type UpsertCustomFieldValueParams struct {
	ID           string         `json:"id"`
	SubscriberID string         `json:"subscriber_id"`
	FieldID      string         `json:"field_id"`
	Value        sql.NullString `json:"value"`
}

func (q *Queries) UpsertCustomFieldValue(ctx context.Context, arg UpsertCustomFieldValueParams) (CustomFieldValue, error) {
	row := q.db.QueryRowContext(ctx, upsertCustomFieldValue,
		arg.ID,
		arg.SubscriberID,
		arg.FieldID,
		arg.Value,
	)
	var i CustomFieldValue
	err := row.Scan(
		&i.ID,
		&i.SubscriberID,
		&i.FieldID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
