// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domain_identities.sql

package db

import (
	"context"
	"database/sql"
)

const createDomainIdentity = `-- name: CreateDomainIdentity :one
INSERT INTO domain_identities (
    id, org_id, domain, verification_status, dkim_status,
    verification_token, dkim_tokens, dns_records, mail_from_domain
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, org_id, domain, verification_status, dkim_status, verification_token, dkim_tokens, dns_records, mail_from_domain, mail_from_status, last_checked_at, created_at, updated_at
`

type CreateDomainIdentityParams struct {
	ID                 string         `json:"id"`
	OrgID              string         `json:"org_id"`
	Domain             string         `json:"domain"`
	VerificationStatus sql.NullString `json:"verification_status"`
	DkimStatus         sql.NullString `json:"dkim_status"`
	VerificationToken  sql.NullString `json:"verification_token"`
	DkimTokens         sql.NullString `json:"dkim_tokens"`
	DnsRecords         sql.NullString `json:"dns_records"`
	MailFromDomain     sql.NullString `json:"mail_from_domain"`
}

func (q *Queries) CreateDomainIdentity(ctx context.Context, arg CreateDomainIdentityParams) (DomainIdentity, error) {
	row := q.db.QueryRowContext(ctx, createDomainIdentity,
		arg.ID,
		arg.OrgID,
		arg.Domain,
		arg.VerificationStatus,
		arg.DkimStatus,
		arg.VerificationToken,
		arg.DkimTokens,
		arg.DnsRecords,
		arg.MailFromDomain,
	)
	var i DomainIdentity
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Domain,
		&i.VerificationStatus,
		&i.DkimStatus,
		&i.VerificationToken,
		&i.DkimTokens,
		&i.DnsRecords,
		&i.MailFromDomain,
		&i.MailFromStatus,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDomainIdentity = `-- name: DeleteDomainIdentity :exec
DELETE FROM domain_identities
WHERE id = ?
`

func (q *Queries) DeleteDomainIdentity(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDomainIdentity, id)
	return err
}

const deleteDomainIdentityByOrg = `-- name: DeleteDomainIdentityByOrg :exec
DELETE FROM domain_identities
WHERE org_id = ? AND domain = ?
`

type DeleteDomainIdentityByOrgParams struct {
	OrgID  string `json:"org_id"`
	Domain string `json:"domain"`
}

func (q *Queries) DeleteDomainIdentityByOrg(ctx context.Context, arg DeleteDomainIdentityByOrgParams) error {
	_, err := q.db.ExecContext(ctx, deleteDomainIdentityByOrg, arg.OrgID, arg.Domain)
	return err
}

const getDomainIdentity = `-- name: GetDomainIdentity :one
SELECT id, org_id, domain, verification_status, dkim_status, verification_token, dkim_tokens, dns_records, mail_from_domain, mail_from_status, last_checked_at, created_at, updated_at FROM domain_identities
WHERE id = ?
`

func (q *Queries) GetDomainIdentity(ctx context.Context, id string) (DomainIdentity, error) {
	row := q.db.QueryRowContext(ctx, getDomainIdentity, id)
	var i DomainIdentity
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Domain,
		&i.VerificationStatus,
		&i.DkimStatus,
		&i.VerificationToken,
		&i.DkimTokens,
		&i.DnsRecords,
		&i.MailFromDomain,
		&i.MailFromStatus,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainIdentityByDomain = `-- name: GetDomainIdentityByDomain :one
SELECT id, org_id, domain, verification_status, dkim_status, verification_token, dkim_tokens, dns_records, mail_from_domain, mail_from_status, last_checked_at, created_at, updated_at FROM domain_identities
WHERE org_id = ? AND domain = ?
`

type GetDomainIdentityByDomainParams struct {
	OrgID  string `json:"org_id"`
	Domain string `json:"domain"`
}

func (q *Queries) GetDomainIdentityByDomain(ctx context.Context, arg GetDomainIdentityByDomainParams) (DomainIdentity, error) {
	row := q.db.QueryRowContext(ctx, getDomainIdentityByDomain, arg.OrgID, arg.Domain)
	var i DomainIdentity
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Domain,
		&i.VerificationStatus,
		&i.DkimStatus,
		&i.VerificationToken,
		&i.DkimTokens,
		&i.DnsRecords,
		&i.MailFromDomain,
		&i.MailFromStatus,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDomainIdentitiesByOrg = `-- name: ListDomainIdentitiesByOrg :many
SELECT id, org_id, domain, verification_status, dkim_status, verification_token, dkim_tokens, dns_records, mail_from_domain, mail_from_status, last_checked_at, created_at, updated_at FROM domain_identities
WHERE org_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListDomainIdentitiesByOrg(ctx context.Context, orgID string) ([]DomainIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listDomainIdentitiesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainIdentity
	for rows.Next() {
		var i DomainIdentity
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Domain,
			&i.VerificationStatus,
			&i.DkimStatus,
			&i.VerificationToken,
			&i.DkimTokens,
			&i.DnsRecords,
			&i.MailFromDomain,
			&i.MailFromStatus,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDomainIdentities = `-- name: ListPendingDomainIdentities :many
SELECT id, org_id, domain, verification_status, dkim_status, verification_token, dkim_tokens, dns_records, mail_from_domain, mail_from_status, last_checked_at, created_at, updated_at FROM domain_identities
WHERE verification_status IN ('pending', 'Pending', 'not_started')
   OR dkim_status IN ('pending', 'Pending', 'not_started')
ORDER BY created_at ASC
`

func (q *Queries) ListPendingDomainIdentities(ctx context.Context) ([]DomainIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDomainIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DomainIdentity
	for rows.Next() {
		var i DomainIdentity
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Domain,
			&i.VerificationStatus,
			&i.DkimStatus,
			&i.VerificationToken,
			&i.DkimTokens,
			&i.DnsRecords,
			&i.MailFromDomain,
			&i.MailFromStatus,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDomainIdentityDNSRecords = `-- name: UpdateDomainIdentityDNSRecords :one
UPDATE domain_identities
SET dns_records = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, org_id, domain, verification_status, dkim_status, verification_token, dkim_tokens, dns_records, mail_from_domain, mail_from_status, last_checked_at, created_at, updated_at
`

type UpdateDomainIdentityDNSRecordsParams struct {
	DnsRecords sql.NullString `json:"dns_records"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateDomainIdentityDNSRecords(ctx context.Context, arg UpdateDomainIdentityDNSRecordsParams) (DomainIdentity, error) {
	row := q.db.QueryRowContext(ctx, updateDomainIdentityDNSRecords, arg.DnsRecords, arg.ID)
	var i DomainIdentity
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Domain,
		&i.VerificationStatus,
		&i.DkimStatus,
		&i.VerificationToken,
		&i.DkimTokens,
		&i.DnsRecords,
		&i.MailFromDomain,
		&i.MailFromStatus,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDomainIdentityFull = `-- name: UpdateDomainIdentityFull :one
UPDATE domain_identities
SET verification_status = ?,
    dkim_status = ?,
    verification_token = ?,
    dns_records = ?,
    last_checked_at = datetime('now'),
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, org_id, domain, verification_status, dkim_status, verification_token, dkim_tokens, dns_records, mail_from_domain, mail_from_status, last_checked_at, created_at, updated_at
`

type UpdateDomainIdentityFullParams struct {
	VerificationStatus sql.NullString `json:"verification_status"`
	DkimStatus         sql.NullString `json:"dkim_status"`
	VerificationToken  sql.NullString `json:"verification_token"`
	DnsRecords         sql.NullString `json:"dns_records"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateDomainIdentityFull(ctx context.Context, arg UpdateDomainIdentityFullParams) (DomainIdentity, error) {
	row := q.db.QueryRowContext(ctx, updateDomainIdentityFull,
		arg.VerificationStatus,
		arg.DkimStatus,
		arg.VerificationToken,
		arg.DnsRecords,
		arg.ID,
	)
	var i DomainIdentity
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Domain,
		&i.VerificationStatus,
		&i.DkimStatus,
		&i.VerificationToken,
		&i.DkimTokens,
		&i.DnsRecords,
		&i.MailFromDomain,
		&i.MailFromStatus,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDomainIdentityMailFrom = `-- name: UpdateDomainIdentityMailFrom :one
UPDATE domain_identities
SET mail_from_domain = ?,
    mail_from_status = ?,
    dns_records = ?,
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, org_id, domain, verification_status, dkim_status, verification_token, dkim_tokens, dns_records, mail_from_domain, mail_from_status, last_checked_at, created_at, updated_at
`

type UpdateDomainIdentityMailFromParams struct {
	MailFromDomain sql.NullString `json:"mail_from_domain"`
	MailFromStatus sql.NullString `json:"mail_from_status"`
	DnsRecords     sql.NullString `json:"dns_records"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateDomainIdentityMailFrom(ctx context.Context, arg UpdateDomainIdentityMailFromParams) (DomainIdentity, error) {
	row := q.db.QueryRowContext(ctx, updateDomainIdentityMailFrom,
		arg.MailFromDomain,
		arg.MailFromStatus,
		arg.DnsRecords,
		arg.ID,
	)
	var i DomainIdentity
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Domain,
		&i.VerificationStatus,
		&i.DkimStatus,
		&i.VerificationToken,
		&i.DkimTokens,
		&i.DnsRecords,
		&i.MailFromDomain,
		&i.MailFromStatus,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDomainIdentityStatus = `-- name: UpdateDomainIdentityStatus :one
UPDATE domain_identities
SET verification_status = ?,
    dkim_status = ?,
    last_checked_at = datetime('now'),
    updated_at = datetime('now')
WHERE id = ?
RETURNING id, org_id, domain, verification_status, dkim_status, verification_token, dkim_tokens, dns_records, mail_from_domain, mail_from_status, last_checked_at, created_at, updated_at
`

type UpdateDomainIdentityStatusParams struct {
	VerificationStatus sql.NullString `json:"verification_status"`
	DkimStatus         sql.NullString `json:"dkim_status"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateDomainIdentityStatus(ctx context.Context, arg UpdateDomainIdentityStatusParams) (DomainIdentity, error) {
	row := q.db.QueryRowContext(ctx, updateDomainIdentityStatus, arg.VerificationStatus, arg.DkimStatus, arg.ID)
	var i DomainIdentity
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Domain,
		&i.VerificationStatus,
		&i.DkimStatus,
		&i.VerificationToken,
		&i.DkimTokens,
		&i.DnsRecords,
		&i.MailFromDomain,
		&i.MailFromStatus,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
