// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_designs.sql

package db

import (
	"context"
	"database/sql"
)

const countEmailDesigns = `-- name: CountEmailDesigns :one
SELECT COUNT(*) as count FROM email_designs
WHERE org_id = ?1
`

func (q *Queries) CountEmailDesigns(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailDesigns, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmailDesignsByCategory = `-- name: CountEmailDesignsByCategory :one
SELECT COUNT(*) as count FROM email_designs
WHERE org_id = ?1 AND category = ?2
`

type CountEmailDesignsByCategoryParams struct {
	OrgID    string         `json:"org_id"`
	Category sql.NullString `json:"category"`
}

func (q *Queries) CountEmailDesignsByCategory(ctx context.Context, arg CountEmailDesignsByCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEmailDesignsByCategory, arg.OrgID, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailDesign = `-- name: CreateEmailDesign :one

INSERT INTO email_designs (id, org_id, name, slug, description, category, html_body, plain_text, is_active, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, datetime('now'), datetime('now'))
RETURNING id, org_id, name, slug, description, category, html_body, plain_text, thumbnail_url, is_active, created_at, updated_at
`

type CreateEmailDesignParams struct {
	ID          int64          `json:"id"`
	OrgID       string         `json:"org_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	Category    sql.NullString `json:"category"`
	HtmlBody    string         `json:"html_body"`
	PlainText   sql.NullString `json:"plain_text"`
	IsActive    sql.NullInt64  `json:"is_active"`
}

// Email Designs (Global Templates)
// Reusable email designs at org level
func (q *Queries) CreateEmailDesign(ctx context.Context, arg CreateEmailDesignParams) (EmailDesign, error) {
	row := q.db.QueryRowContext(ctx, createEmailDesign,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Category,
		arg.HtmlBody,
		arg.PlainText,
		arg.IsActive,
	)
	var i EmailDesign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Category,
		&i.HtmlBody,
		&i.PlainText,
		&i.ThumbnailUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEmailDesign = `-- name: DeleteEmailDesign :exec
DELETE FROM email_designs
WHERE id = ?1 AND org_id = ?2
`

type DeleteEmailDesignParams struct {
	ID    int64  `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteEmailDesign(ctx context.Context, arg DeleteEmailDesignParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmailDesign, arg.ID, arg.OrgID)
	return err
}

const getEmailDesign = `-- name: GetEmailDesign :one
SELECT id, org_id, name, slug, description, category, html_body, plain_text, thumbnail_url, is_active, created_at, updated_at FROM email_designs
WHERE id = ?1 AND org_id = ?2
`

type GetEmailDesignParams struct {
	ID    int64  `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetEmailDesign(ctx context.Context, arg GetEmailDesignParams) (EmailDesign, error) {
	row := q.db.QueryRowContext(ctx, getEmailDesign, arg.ID, arg.OrgID)
	var i EmailDesign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Category,
		&i.HtmlBody,
		&i.PlainText,
		&i.ThumbnailUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailDesignBySlug = `-- name: GetEmailDesignBySlug :one
SELECT id, org_id, name, slug, description, category, html_body, plain_text, thumbnail_url, is_active, created_at, updated_at FROM email_designs
WHERE slug = ?1 AND org_id = ?2
`

type GetEmailDesignBySlugParams struct {
	Slug  string `json:"slug"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetEmailDesignBySlug(ctx context.Context, arg GetEmailDesignBySlugParams) (EmailDesign, error) {
	row := q.db.QueryRowContext(ctx, getEmailDesignBySlug, arg.Slug, arg.OrgID)
	var i EmailDesign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Category,
		&i.HtmlBody,
		&i.PlainText,
		&i.ThumbnailUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmailDesigns = `-- name: ListEmailDesigns :many
SELECT id, org_id, name, slug, description, category, html_body, plain_text, thumbnail_url, is_active, created_at, updated_at FROM email_designs
WHERE org_id = ?1
ORDER BY created_at DESC
`

func (q *Queries) ListEmailDesigns(ctx context.Context, orgID string) ([]EmailDesign, error) {
	rows, err := q.db.QueryContext(ctx, listEmailDesigns, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailDesign
	for rows.Next() {
		var i EmailDesign
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Category,
			&i.HtmlBody,
			&i.PlainText,
			&i.ThumbnailUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailDesignsByCategory = `-- name: ListEmailDesignsByCategory :many
SELECT id, org_id, name, slug, description, category, html_body, plain_text, thumbnail_url, is_active, created_at, updated_at FROM email_designs
WHERE org_id = ?1 AND category = ?2
ORDER BY created_at DESC
`

type ListEmailDesignsByCategoryParams struct {
	OrgID    string         `json:"org_id"`
	Category sql.NullString `json:"category"`
}

func (q *Queries) ListEmailDesignsByCategory(ctx context.Context, arg ListEmailDesignsByCategoryParams) ([]EmailDesign, error) {
	rows, err := q.db.QueryContext(ctx, listEmailDesignsByCategory, arg.OrgID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailDesign
	for rows.Next() {
		var i EmailDesign
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Category,
			&i.HtmlBody,
			&i.PlainText,
			&i.ThumbnailUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailDesign = `-- name: UpdateEmailDesign :one
UPDATE email_designs
SET name = COALESCE(NULLIF(?1, ''), name),
    slug = COALESCE(NULLIF(?2, ''), slug),
    description = COALESCE(NULLIF(?3, ''), description),
    category = COALESCE(NULLIF(?4, ''), category),
    html_body = COALESCE(NULLIF(?5, ''), html_body),
    plain_text = COALESCE(NULLIF(?6, ''), plain_text),
    is_active = COALESCE(?7, is_active),
    updated_at = datetime('now')
WHERE id = ?8 AND org_id = ?9
RETURNING id, org_id, name, slug, description, category, html_body, plain_text, thumbnail_url, is_active, created_at, updated_at
`

type UpdateEmailDesignParams struct {
	Name        interface{}   `json:"name"`
	Slug        interface{}   `json:"slug"`
	Description interface{}   `json:"description"`
	Category    interface{}   `json:"category"`
	HtmlBody    interface{}   `json:"html_body"`
	PlainText   interface{}   `json:"plain_text"`
	IsActive    sql.NullInt64 `json:"is_active"`
	ID          int64         `json:"id"`
	OrgID       string        `json:"org_id"`
}

func (q *Queries) UpdateEmailDesign(ctx context.Context, arg UpdateEmailDesignParams) (EmailDesign, error) {
	row := q.db.QueryRowContext(ctx, updateEmailDesign,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Category,
		arg.HtmlBody,
		arg.PlainText,
		arg.IsActive,
		arg.ID,
		arg.OrgID,
	)
	var i EmailDesign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Category,
		&i.HtmlBody,
		&i.PlainText,
		&i.ThumbnailUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
