// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_lists.sql

package db

import (
	"context"
	"database/sql"
)

const checkListSubscription = `-- name: CheckListSubscription :one
SELECT COUNT(*) as count FROM list_subscribers
WHERE list_id = ?1 AND contact_id = ?2
`

type CheckListSubscriptionParams struct {
	ListID    int64  `json:"list_id"`
	ContactID string `json:"contact_id"`
}

func (q *Queries) CheckListSubscription(ctx context.Context, arg CheckListSubscriptionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkListSubscription, arg.ListID, arg.ContactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const confirmListSubscription = `-- name: ConfirmListSubscription :one
UPDATE list_subscribers
SET status = 'active', verified_at = datetime('now'), verification_token = NULL
WHERE verification_token = ?1 AND status = 'pending'
RETURNING id, list_id, contact_id, status, verification_token, verification_sent_at, verified_at, subscribed_at, unsubscribed_at
`

func (q *Queries) ConfirmListSubscription(ctx context.Context, token sql.NullString) (ListSubscriber, error) {
	row := q.db.QueryRowContext(ctx, confirmListSubscription, token)
	var i ListSubscriber
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}

const countActiveSubscribers = `-- name: CountActiveSubscribers :one
SELECT COUNT(*) as count FROM list_subscribers
WHERE list_id = ?1 AND status = 'active'
`

func (q *Queries) CountActiveSubscribers(ctx context.Context, listID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSubscribers, listID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countListSubscribers = `-- name: CountListSubscribers :one
SELECT COUNT(*) as count FROM list_subscribers
WHERE list_id = ?1
  AND (?2 IS NULL OR ?2 = '' OR status = ?2)
`

type CountListSubscribersParams struct {
	ListID       int64       `json:"list_id"`
	FilterStatus interface{} `json:"filter_status"`
}

func (q *Queries) CountListSubscribers(ctx context.Context, arg CountListSubscribersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countListSubscribers, arg.ListID, arg.FilterStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailList = `-- name: CreateEmailList :one
INSERT INTO email_lists (
    org_id, name, slug, description, double_optin, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, datetime('now'), datetime('now')
) RETURNING id, org_id, name, slug, description, double_optin, confirmation_email_subject, confirmation_email_body, created_at, updated_at, public_page_enabled, thank_you_url, confirm_redirect_url, unsubscribe_redirect_url
`

type CreateEmailListParams struct {
	OrgID       string         `json:"org_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	DoubleOptin sql.NullInt64  `json:"double_optin"`
}

func (q *Queries) CreateEmailList(ctx context.Context, arg CreateEmailListParams) (EmailList, error) {
	row := q.db.QueryRowContext(ctx, createEmailList,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.DoubleOptin,
	)
	var i EmailList
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.DoubleOptin,
		&i.ConfirmationEmailSubject,
		&i.ConfirmationEmailBody,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPageEnabled,
		&i.ThankYouUrl,
		&i.ConfirmRedirectUrl,
		&i.UnsubscribeRedirectUrl,
	)
	return i, err
}

const createListSubscriber = `-- name: CreateListSubscriber :one
INSERT INTO list_subscribers (list_id, contact_id, status, subscribed_at)
VALUES (?1, ?2, ?3, datetime('now'))
ON CONFLICT (list_id, contact_id) DO NOTHING
RETURNING id, list_id, contact_id, status, verification_token, verification_sent_at, verified_at, subscribed_at, unsubscribed_at
`

type CreateListSubscriberParams struct {
	ListID    int64          `json:"list_id"`
	ContactID string         `json:"contact_id"`
	Status    sql.NullString `json:"status"`
}

func (q *Queries) CreateListSubscriber(ctx context.Context, arg CreateListSubscriberParams) (ListSubscriber, error) {
	row := q.db.QueryRowContext(ctx, createListSubscriber, arg.ListID, arg.ContactID, arg.Status)
	var i ListSubscriber
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}

const deleteEmailList = `-- name: DeleteEmailList :exec
DELETE FROM email_lists
WHERE id = ?1
`

func (q *Queries) DeleteEmailList(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEmailList, id)
	return err
}

const getEmailList = `-- name: GetEmailList :one
SELECT id, org_id, name, slug, description, double_optin, confirmation_email_subject, confirmation_email_body, created_at, updated_at, public_page_enabled, thank_you_url, confirm_redirect_url, unsubscribe_redirect_url FROM email_lists
WHERE id = ?1
`

func (q *Queries) GetEmailList(ctx context.Context, id int64) (EmailList, error) {
	row := q.db.QueryRowContext(ctx, getEmailList, id)
	var i EmailList
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.DoubleOptin,
		&i.ConfirmationEmailSubject,
		&i.ConfirmationEmailBody,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPageEnabled,
		&i.ThankYouUrl,
		&i.ConfirmRedirectUrl,
		&i.UnsubscribeRedirectUrl,
	)
	return i, err
}

const getEmailListByOrgAndSlug = `-- name: GetEmailListByOrgAndSlug :one
SELECT id, org_id, name, slug, description, double_optin, confirmation_email_subject, confirmation_email_body, created_at, updated_at, public_page_enabled, thank_you_url, confirm_redirect_url, unsubscribe_redirect_url FROM email_lists
WHERE org_id = ?1 AND slug = ?2
LIMIT 1
`

type GetEmailListByOrgAndSlugParams struct {
	OrgID string `json:"org_id"`
	Slug  string `json:"slug"`
}

func (q *Queries) GetEmailListByOrgAndSlug(ctx context.Context, arg GetEmailListByOrgAndSlugParams) (EmailList, error) {
	row := q.db.QueryRowContext(ctx, getEmailListByOrgAndSlug, arg.OrgID, arg.Slug)
	var i EmailList
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.DoubleOptin,
		&i.ConfirmationEmailSubject,
		&i.ConfirmationEmailBody,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPageEnabled,
		&i.ThankYouUrl,
		&i.ConfirmRedirectUrl,
		&i.UnsubscribeRedirectUrl,
	)
	return i, err
}

const getListSubscriber = `-- name: GetListSubscriber :one
SELECT id, list_id, contact_id, status, verification_token, verification_sent_at, verified_at, subscribed_at, unsubscribed_at FROM list_subscribers
WHERE list_id = ?1 AND contact_id = ?2
`

type GetListSubscriberParams struct {
	ListID    int64  `json:"list_id"`
	ContactID string `json:"contact_id"`
}

func (q *Queries) GetListSubscriber(ctx context.Context, arg GetListSubscriberParams) (ListSubscriber, error) {
	row := q.db.QueryRowContext(ctx, getListSubscriber, arg.ListID, arg.ContactID)
	var i ListSubscriber
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}

const getListSubscriberByID = `-- name: GetListSubscriberByID :one
SELECT ls.id, ls.list_id, ls.contact_id, ls.status, ls.verification_token, ls.verification_sent_at, ls.verified_at, ls.subscribed_at, ls.unsubscribed_at, c.email, c.name
FROM list_subscribers ls
JOIN contacts c ON c.id = ls.contact_id
WHERE ls.id = ?1
`

type GetListSubscriberByIDRow struct {
	ID                 string         `json:"id"`
	ListID             int64          `json:"list_id"`
	ContactID          string         `json:"contact_id"`
	Status             sql.NullString `json:"status"`
	VerificationToken  sql.NullString `json:"verification_token"`
	VerificationSentAt sql.NullString `json:"verification_sent_at"`
	VerifiedAt         sql.NullString `json:"verified_at"`
	SubscribedAt       sql.NullString `json:"subscribed_at"`
	UnsubscribedAt     sql.NullString `json:"unsubscribed_at"`
	Email              string         `json:"email"`
	Name               string         `json:"name"`
}

func (q *Queries) GetListSubscriberByID(ctx context.Context, id string) (GetListSubscriberByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getListSubscriberByID, id)
	var i GetListSubscriberByIDRow
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const getListSubscriberByToken = `-- name: GetListSubscriberByToken :one
SELECT ls.id, ls.list_id, ls.contact_id, ls.status, ls.verification_token, ls.verification_sent_at, ls.verified_at, ls.subscribed_at, ls.unsubscribed_at, el.name as list_name, el.org_id
FROM list_subscribers ls
JOIN email_lists el ON el.id = ls.list_id
WHERE ls.verification_token = ?1
`

type GetListSubscriberByTokenRow struct {
	ID                 string         `json:"id"`
	ListID             int64          `json:"list_id"`
	ContactID          string         `json:"contact_id"`
	Status             sql.NullString `json:"status"`
	VerificationToken  sql.NullString `json:"verification_token"`
	VerificationSentAt sql.NullString `json:"verification_sent_at"`
	VerifiedAt         sql.NullString `json:"verified_at"`
	SubscribedAt       sql.NullString `json:"subscribed_at"`
	UnsubscribedAt     sql.NullString `json:"unsubscribed_at"`
	ListName           string         `json:"list_name"`
	OrgID              string         `json:"org_id"`
}

func (q *Queries) GetListSubscriberByToken(ctx context.Context, token sql.NullString) (GetListSubscriberByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getListSubscriberByToken, token)
	var i GetListSubscriberByTokenRow
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.ListName,
		&i.OrgID,
	)
	return i, err
}

const listEmailLists = `-- name: ListEmailLists :many
SELECT id, org_id, name, slug, description, double_optin, confirmation_email_subject, confirmation_email_body, created_at, updated_at, public_page_enabled, thank_you_url, confirm_redirect_url, unsubscribe_redirect_url FROM email_lists
WHERE org_id = ?1
ORDER BY created_at DESC
`

func (q *Queries) ListEmailLists(ctx context.Context, orgID string) ([]EmailList, error) {
	rows, err := q.db.QueryContext(ctx, listEmailLists, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailList
	for rows.Next() {
		var i EmailList
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.DoubleOptin,
			&i.ConfirmationEmailSubject,
			&i.ConfirmationEmailBody,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicPageEnabled,
			&i.ThankYouUrl,
			&i.ConfirmRedirectUrl,
			&i.UnsubscribeRedirectUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListSubscribers = `-- name: ListListSubscribers :many
SELECT ls.id, ls.list_id, ls.contact_id, ls.status, ls.verification_token, ls.verification_sent_at, ls.verified_at, ls.subscribed_at, ls.unsubscribed_at, c.email, c.name
FROM list_subscribers ls
JOIN contacts c ON c.id = ls.contact_id
WHERE ls.list_id = ?1
  AND (?2 IS NULL OR ?2 = '' OR ls.status = ?2)
ORDER BY ls.subscribed_at DESC
LIMIT ?4 OFFSET ?3
`

type ListListSubscribersParams struct {
	ListID       int64       `json:"list_id"`
	FilterStatus interface{} `json:"filter_status"`
	PageOffset   int64       `json:"page_offset"`
	PageSize     int64       `json:"page_size"`
}

type ListListSubscribersRow struct {
	ID                 string         `json:"id"`
	ListID             int64          `json:"list_id"`
	ContactID          string         `json:"contact_id"`
	Status             sql.NullString `json:"status"`
	VerificationToken  sql.NullString `json:"verification_token"`
	VerificationSentAt sql.NullString `json:"verification_sent_at"`
	VerifiedAt         sql.NullString `json:"verified_at"`
	SubscribedAt       sql.NullString `json:"subscribed_at"`
	UnsubscribedAt     sql.NullString `json:"unsubscribed_at"`
	Email              string         `json:"email"`
	Name               string         `json:"name"`
}

func (q *Queries) ListListSubscribers(ctx context.Context, arg ListListSubscribersParams) ([]ListListSubscribersRow, error) {
	rows, err := q.db.QueryContext(ctx, listListSubscribers,
		arg.ListID,
		arg.FilterStatus,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListListSubscribersRow
	for rows.Next() {
		var i ListListSubscribersRow
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.ContactID,
			&i.Status,
			&i.VerificationToken,
			&i.VerificationSentAt,
			&i.VerifiedAt,
			&i.SubscribedAt,
			&i.UnsubscribedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSubscriberFromList = `-- name: RemoveSubscriberFromList :exec
DELETE FROM list_subscribers
WHERE list_id = ?1 AND contact_id = ?2
`

type RemoveSubscriberFromListParams struct {
	ListID    int64  `json:"list_id"`
	ContactID string `json:"contact_id"`
}

func (q *Queries) RemoveSubscriberFromList(ctx context.Context, arg RemoveSubscriberFromListParams) error {
	_, err := q.db.ExecContext(ctx, removeSubscriberFromList, arg.ListID, arg.ContactID)
	return err
}

const subscribeToList = `-- name: SubscribeToList :one
INSERT INTO list_subscribers (
    id, list_id, contact_id, status, subscribed_at
) VALUES (
    ?1, ?2, ?3, 'active', datetime('now')
)
ON CONFLICT (list_id, contact_id) DO UPDATE
SET status = 'active', unsubscribed_at = NULL
RETURNING id, list_id, contact_id, status, verification_token, verification_sent_at, verified_at, subscribed_at, unsubscribed_at
`

type SubscribeToListParams struct {
	ID        string `json:"id"`
	ListID    int64  `json:"list_id"`
	ContactID string `json:"contact_id"`
}

func (q *Queries) SubscribeToList(ctx context.Context, arg SubscribeToListParams) (ListSubscriber, error) {
	row := q.db.QueryRowContext(ctx, subscribeToList, arg.ID, arg.ListID, arg.ContactID)
	var i ListSubscriber
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}

const subscribeToListPending = `-- name: SubscribeToListPending :one
INSERT INTO list_subscribers (
    id, list_id, contact_id, status, verification_token, verification_sent_at
) VALUES (
    ?1, ?2, ?3, 'pending',
    ?4, datetime('now')
)
ON CONFLICT (list_id, contact_id) DO UPDATE
SET status = CASE
    WHEN list_subscribers.status = 'active' THEN 'active'
    ELSE 'pending'
END,
verification_token = CASE
    WHEN list_subscribers.status = 'active' THEN list_subscribers.verification_token
    ELSE EXCLUDED.verification_token
END,
verification_sent_at = CASE
    WHEN list_subscribers.status = 'active' THEN list_subscribers.verification_sent_at
    ELSE datetime('now')
END,
unsubscribed_at = NULL
RETURNING id, list_id, contact_id, status, verification_token, verification_sent_at, verified_at, subscribed_at, unsubscribed_at
`

type SubscribeToListPendingParams struct {
	ID                string         `json:"id"`
	ListID            int64          `json:"list_id"`
	ContactID         string         `json:"contact_id"`
	VerificationToken sql.NullString `json:"verification_token"`
}

func (q *Queries) SubscribeToListPending(ctx context.Context, arg SubscribeToListPendingParams) (ListSubscriber, error) {
	row := q.db.QueryRowContext(ctx, subscribeToListPending,
		arg.ID,
		arg.ListID,
		arg.ContactID,
		arg.VerificationToken,
	)
	var i ListSubscriber
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}

const unsubscribeFromList = `-- name: UnsubscribeFromList :exec
UPDATE list_subscribers
SET status = 'unsubscribed', unsubscribed_at = datetime('now')
WHERE list_id = ?1 AND contact_id = ?2
`

type UnsubscribeFromListParams struct {
	ListID    int64  `json:"list_id"`
	ContactID string `json:"contact_id"`
}

func (q *Queries) UnsubscribeFromList(ctx context.Context, arg UnsubscribeFromListParams) error {
	_, err := q.db.ExecContext(ctx, unsubscribeFromList, arg.ListID, arg.ContactID)
	return err
}

const updateEmailList = `-- name: UpdateEmailList :one
UPDATE email_lists
SET name = COALESCE(?1, name),
    description = COALESCE(?2, description),
    double_optin = COALESCE(?3, double_optin),
    confirmation_email_subject = COALESCE(NULLIF(?4, ''), confirmation_email_subject),
    confirmation_email_body = COALESCE(NULLIF(?5, ''), confirmation_email_body),
    updated_at = datetime('now')
WHERE id = ?6
RETURNING id, org_id, name, slug, description, double_optin, confirmation_email_subject, confirmation_email_body, created_at, updated_at, public_page_enabled, thank_you_url, confirm_redirect_url, unsubscribe_redirect_url
`

type UpdateEmailListParams struct {
	Name                string         `json:"name"`
	Description         sql.NullString `json:"description"`
	DoubleOptin         sql.NullInt64  `json:"double_optin"`
	ConfirmationSubject interface{}    `json:"confirmation_subject"`
	ConfirmationBody    interface{}    `json:"confirmation_body"`
	ID                  int64          `json:"id"`
}

func (q *Queries) UpdateEmailList(ctx context.Context, arg UpdateEmailListParams) (EmailList, error) {
	row := q.db.QueryRowContext(ctx, updateEmailList,
		arg.Name,
		arg.Description,
		arg.DoubleOptin,
		arg.ConfirmationSubject,
		arg.ConfirmationBody,
		arg.ID,
	)
	var i EmailList
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.DoubleOptin,
		&i.ConfirmationEmailSubject,
		&i.ConfirmationEmailBody,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPageEnabled,
		&i.ThankYouUrl,
		&i.ConfirmRedirectUrl,
		&i.UnsubscribeRedirectUrl,
	)
	return i, err
}
