// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_lists.sql

package db

import (
	"context"
	"database/sql"
)

const checkListSubscription = `-- name: CheckListSubscription :one
SELECT COUNT(*) as count FROM list_subscribers
WHERE list_id = ?1 AND contact_id = ?2
`

type CheckListSubscriptionParams struct {
	ListID    int64  `json:"list_id"`
	ContactID string `json:"contact_id"`
}

func (q *Queries) CheckListSubscription(ctx context.Context, arg CheckListSubscriptionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkListSubscription, arg.ListID, arg.ContactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const confirmListSubscription = `-- name: ConfirmListSubscription :one
UPDATE list_subscribers
SET status = 'active', verified_at = datetime('now'), verification_token = NULL
WHERE verification_token = ?1 AND status = 'pending'
RETURNING id, list_id, contact_id, status, verification_token, verification_sent_at, verified_at, subscribed_at, unsubscribed_at
`

func (q *Queries) ConfirmListSubscription(ctx context.Context, token sql.NullString) (ListSubscriber, error) {
	row := q.db.QueryRowContext(ctx, confirmListSubscription, token)
	var i ListSubscriber
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}

const countActiveSubscribers = `-- name: CountActiveSubscribers :one
SELECT COUNT(*) as count FROM list_subscribers
WHERE list_id = ?1 AND status = 'active'
`

func (q *Queries) CountActiveSubscribers(ctx context.Context, listID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveSubscribers, listID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countListSubscribers = `-- name: CountListSubscribers :one
SELECT COUNT(*) as count FROM list_subscribers
WHERE list_id = ?1
  AND (?2 IS NULL OR ?2 = '' OR status = ?2)
`

type CountListSubscribersParams struct {
	ListID       int64       `json:"list_id"`
	FilterStatus interface{} `json:"filter_status"`
}

func (q *Queries) CountListSubscribers(ctx context.Context, arg CountListSubscribersParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countListSubscribers, arg.ListID, arg.FilterStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailList = `-- name: CreateEmailList :one
INSERT INTO email_lists (
    public_id, org_id, name, slug, description, double_optin, created_at, updated_at
) VALUES (
    ?1, ?2, ?3, ?4, ?5,
    ?6, datetime('now'), datetime('now')
) RETURNING id, public_id, org_id, name, slug, description, double_optin, confirmation_email_subject, confirmation_email_body, created_at, updated_at, public_page_enabled, thank_you_url, confirm_redirect_url, unsubscribe_redirect_url, thank_you_email_enabled, thank_you_email_subject, thank_you_email_body, already_subscribed_url, goodbye_email_enabled, goodbye_email_subject, goodbye_email_body, unsubscribe_behavior, unsubscribe_scope
`

type CreateEmailListParams struct {
	PublicID    string         `json:"public_id"`
	OrgID       string         `json:"org_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	DoubleOptin sql.NullInt64  `json:"double_optin"`
}

func (q *Queries) CreateEmailList(ctx context.Context, arg CreateEmailListParams) (EmailList, error) {
	row := q.db.QueryRowContext(ctx, createEmailList,
		arg.PublicID,
		arg.OrgID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.DoubleOptin,
	)
	var i EmailList
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.DoubleOptin,
		&i.ConfirmationEmailSubject,
		&i.ConfirmationEmailBody,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPageEnabled,
		&i.ThankYouUrl,
		&i.ConfirmRedirectUrl,
		&i.UnsubscribeRedirectUrl,
		&i.ThankYouEmailEnabled,
		&i.ThankYouEmailSubject,
		&i.ThankYouEmailBody,
		&i.AlreadySubscribedUrl,
		&i.GoodbyeEmailEnabled,
		&i.GoodbyeEmailSubject,
		&i.GoodbyeEmailBody,
		&i.UnsubscribeBehavior,
		&i.UnsubscribeScope,
	)
	return i, err
}

const createListSubscriber = `-- name: CreateListSubscriber :one
INSERT INTO list_subscribers (list_id, contact_id, status, subscribed_at)
VALUES (?1, ?2, ?3, datetime('now'))
ON CONFLICT (list_id, contact_id) DO NOTHING
RETURNING id, list_id, contact_id, status, verification_token, verification_sent_at, verified_at, subscribed_at, unsubscribed_at
`

type CreateListSubscriberParams struct {
	ListID    int64          `json:"list_id"`
	ContactID string         `json:"contact_id"`
	Status    sql.NullString `json:"status"`
}

func (q *Queries) CreateListSubscriber(ctx context.Context, arg CreateListSubscriberParams) (ListSubscriber, error) {
	row := q.db.QueryRowContext(ctx, createListSubscriber, arg.ListID, arg.ContactID, arg.Status)
	var i ListSubscriber
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}

const deleteEmailList = `-- name: DeleteEmailList :exec
DELETE FROM email_lists
WHERE id = ?1
`

func (q *Queries) DeleteEmailList(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEmailList, id)
	return err
}

const getEmailList = `-- name: GetEmailList :one
SELECT id, public_id, org_id, name, slug, description, double_optin, confirmation_email_subject, confirmation_email_body, created_at, updated_at, public_page_enabled, thank_you_url, confirm_redirect_url, unsubscribe_redirect_url, thank_you_email_enabled, thank_you_email_subject, thank_you_email_body, already_subscribed_url, goodbye_email_enabled, goodbye_email_subject, goodbye_email_body, unsubscribe_behavior, unsubscribe_scope FROM email_lists
WHERE id = ?1
`

func (q *Queries) GetEmailList(ctx context.Context, id int64) (EmailList, error) {
	row := q.db.QueryRowContext(ctx, getEmailList, id)
	var i EmailList
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.DoubleOptin,
		&i.ConfirmationEmailSubject,
		&i.ConfirmationEmailBody,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPageEnabled,
		&i.ThankYouUrl,
		&i.ConfirmRedirectUrl,
		&i.UnsubscribeRedirectUrl,
		&i.ThankYouEmailEnabled,
		&i.ThankYouEmailSubject,
		&i.ThankYouEmailBody,
		&i.AlreadySubscribedUrl,
		&i.GoodbyeEmailEnabled,
		&i.GoodbyeEmailSubject,
		&i.GoodbyeEmailBody,
		&i.UnsubscribeBehavior,
		&i.UnsubscribeScope,
	)
	return i, err
}

const getEmailListByOrgAndSlug = `-- name: GetEmailListByOrgAndSlug :one
SELECT id, public_id, org_id, name, slug, description, double_optin, confirmation_email_subject, confirmation_email_body, created_at, updated_at, public_page_enabled, thank_you_url, confirm_redirect_url, unsubscribe_redirect_url, thank_you_email_enabled, thank_you_email_subject, thank_you_email_body, already_subscribed_url, goodbye_email_enabled, goodbye_email_subject, goodbye_email_body, unsubscribe_behavior, unsubscribe_scope FROM email_lists
WHERE org_id = ?1 AND slug = ?2
LIMIT 1
`

type GetEmailListByOrgAndSlugParams struct {
	OrgID string `json:"org_id"`
	Slug  string `json:"slug"`
}

func (q *Queries) GetEmailListByOrgAndSlug(ctx context.Context, arg GetEmailListByOrgAndSlugParams) (EmailList, error) {
	row := q.db.QueryRowContext(ctx, getEmailListByOrgAndSlug, arg.OrgID, arg.Slug)
	var i EmailList
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.DoubleOptin,
		&i.ConfirmationEmailSubject,
		&i.ConfirmationEmailBody,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPageEnabled,
		&i.ThankYouUrl,
		&i.ConfirmRedirectUrl,
		&i.UnsubscribeRedirectUrl,
		&i.ThankYouEmailEnabled,
		&i.ThankYouEmailSubject,
		&i.ThankYouEmailBody,
		&i.AlreadySubscribedUrl,
		&i.GoodbyeEmailEnabled,
		&i.GoodbyeEmailSubject,
		&i.GoodbyeEmailBody,
		&i.UnsubscribeBehavior,
		&i.UnsubscribeScope,
	)
	return i, err
}

const getEmailListByPublicID = `-- name: GetEmailListByPublicID :one
SELECT id, public_id, org_id, name, slug, description, double_optin, confirmation_email_subject, confirmation_email_body, created_at, updated_at, public_page_enabled, thank_you_url, confirm_redirect_url, unsubscribe_redirect_url, thank_you_email_enabled, thank_you_email_subject, thank_you_email_body, already_subscribed_url, goodbye_email_enabled, goodbye_email_subject, goodbye_email_body, unsubscribe_behavior, unsubscribe_scope FROM email_lists
WHERE public_id = ?1
`

func (q *Queries) GetEmailListByPublicID(ctx context.Context, publicID string) (EmailList, error) {
	row := q.db.QueryRowContext(ctx, getEmailListByPublicID, publicID)
	var i EmailList
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.DoubleOptin,
		&i.ConfirmationEmailSubject,
		&i.ConfirmationEmailBody,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPageEnabled,
		&i.ThankYouUrl,
		&i.ConfirmRedirectUrl,
		&i.UnsubscribeRedirectUrl,
		&i.ThankYouEmailEnabled,
		&i.ThankYouEmailSubject,
		&i.ThankYouEmailBody,
		&i.AlreadySubscribedUrl,
		&i.GoodbyeEmailEnabled,
		&i.GoodbyeEmailSubject,
		&i.GoodbyeEmailBody,
		&i.UnsubscribeBehavior,
		&i.UnsubscribeScope,
	)
	return i, err
}

const getListSubscriber = `-- name: GetListSubscriber :one
SELECT id, list_id, contact_id, status, verification_token, verification_sent_at, verified_at, subscribed_at, unsubscribed_at FROM list_subscribers
WHERE list_id = ?1 AND contact_id = ?2
`

type GetListSubscriberParams struct {
	ListID    int64  `json:"list_id"`
	ContactID string `json:"contact_id"`
}

func (q *Queries) GetListSubscriber(ctx context.Context, arg GetListSubscriberParams) (ListSubscriber, error) {
	row := q.db.QueryRowContext(ctx, getListSubscriber, arg.ListID, arg.ContactID)
	var i ListSubscriber
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}

const getListSubscriberByID = `-- name: GetListSubscriberByID :one
SELECT ls.id, ls.list_id, ls.contact_id, ls.status, ls.verification_token, ls.verification_sent_at, ls.verified_at, ls.subscribed_at, ls.unsubscribed_at, c.email, c.name
FROM list_subscribers ls
JOIN contacts c ON c.id = ls.contact_id
WHERE ls.id = ?1
`

type GetListSubscriberByIDRow struct {
	ID                 string         `json:"id"`
	ListID             int64          `json:"list_id"`
	ContactID          string         `json:"contact_id"`
	Status             sql.NullString `json:"status"`
	VerificationToken  sql.NullString `json:"verification_token"`
	VerificationSentAt sql.NullString `json:"verification_sent_at"`
	VerifiedAt         sql.NullString `json:"verified_at"`
	SubscribedAt       sql.NullString `json:"subscribed_at"`
	UnsubscribedAt     sql.NullString `json:"unsubscribed_at"`
	Email              string         `json:"email"`
	Name               string         `json:"name"`
}

func (q *Queries) GetListSubscriberByID(ctx context.Context, id string) (GetListSubscriberByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getListSubscriberByID, id)
	var i GetListSubscriberByIDRow
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.Email,
		&i.Name,
	)
	return i, err
}

const getListSubscriberByToken = `-- name: GetListSubscriberByToken :one
SELECT ls.id, ls.list_id, ls.contact_id, ls.status, ls.verification_token, ls.verification_sent_at, ls.verified_at, ls.subscribed_at, ls.unsubscribed_at, el.name as list_name, el.org_id
FROM list_subscribers ls
JOIN email_lists el ON el.id = ls.list_id
WHERE ls.verification_token = ?1
`

type GetListSubscriberByTokenRow struct {
	ID                 string         `json:"id"`
	ListID             int64          `json:"list_id"`
	ContactID          string         `json:"contact_id"`
	Status             sql.NullString `json:"status"`
	VerificationToken  sql.NullString `json:"verification_token"`
	VerificationSentAt sql.NullString `json:"verification_sent_at"`
	VerifiedAt         sql.NullString `json:"verified_at"`
	SubscribedAt       sql.NullString `json:"subscribed_at"`
	UnsubscribedAt     sql.NullString `json:"unsubscribed_at"`
	ListName           string         `json:"list_name"`
	OrgID              string         `json:"org_id"`
}

func (q *Queries) GetListSubscriberByToken(ctx context.Context, token sql.NullString) (GetListSubscriberByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getListSubscriberByToken, token)
	var i GetListSubscriberByTokenRow
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
		&i.ListName,
		&i.OrgID,
	)
	return i, err
}

const getListSubscriberDetail = `-- name: GetListSubscriberDetail :one
SELECT
    ls.id,
    ls.list_id,
    ls.contact_id,
    ls.status,
    ls.subscribed_at,
    ls.verified_at,
    ls.unsubscribed_at,
    c.email,
    c.name,
    c.source,
    c.created_at as contact_created_at,
    c.email_verified,
    c.gdpr_consent,
    c.gdpr_consent_at,
    c.blocked_at,
    -- Email stats: count from campaign_sends for this contact
    COALESCE((SELECT COUNT(*) FROM campaign_sends cs WHERE cs.contact_id = c.id), 0) as emails_sent,
    COALESCE((SELECT COUNT(*) FROM campaign_sends cs WHERE cs.contact_id = c.id AND cs.opened_at IS NOT NULL), 0) as emails_opened,
    COALESCE((SELECT COUNT(*) FROM campaign_sends cs WHERE cs.contact_id = c.id AND cs.clicked_at IS NOT NULL), 0) as emails_clicked,
    -- Last activity timestamps
    (SELECT MAX(sent_at) FROM campaign_sends cs WHERE cs.contact_id = c.id) as last_email_at,
    (SELECT MAX(opened_at) FROM campaign_sends cs WHERE cs.contact_id = c.id AND opened_at IS NOT NULL) as last_open_at,
    (SELECT MAX(clicked_at) FROM campaign_sends cs WHERE cs.contact_id = c.id AND clicked_at IS NOT NULL) as last_click_at
FROM list_subscribers ls
JOIN contacts c ON c.id = ls.contact_id
WHERE ls.id = ?1
`

type GetListSubscriberDetailRow struct {
	ID               string         `json:"id"`
	ListID           int64          `json:"list_id"`
	ContactID        string         `json:"contact_id"`
	Status           sql.NullString `json:"status"`
	SubscribedAt     sql.NullString `json:"subscribed_at"`
	VerifiedAt       sql.NullString `json:"verified_at"`
	UnsubscribedAt   sql.NullString `json:"unsubscribed_at"`
	Email            string         `json:"email"`
	Name             string         `json:"name"`
	Source           sql.NullString `json:"source"`
	ContactCreatedAt sql.NullString `json:"contact_created_at"`
	EmailVerified    int64          `json:"email_verified"`
	GdprConsent      sql.NullInt64  `json:"gdpr_consent"`
	GdprConsentAt    sql.NullString `json:"gdpr_consent_at"`
	BlockedAt        sql.NullString `json:"blocked_at"`
	EmailsSent       interface{}    `json:"emails_sent"`
	EmailsOpened     interface{}    `json:"emails_opened"`
	EmailsClicked    interface{}    `json:"emails_clicked"`
	LastEmailAt      interface{}    `json:"last_email_at"`
	LastOpenAt       interface{}    `json:"last_open_at"`
	LastClickAt      interface{}    `json:"last_click_at"`
}

func (q *Queries) GetListSubscriberDetail(ctx context.Context, id string) (GetListSubscriberDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getListSubscriberDetail, id)
	var i GetListSubscriberDetailRow
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.SubscribedAt,
		&i.VerifiedAt,
		&i.UnsubscribedAt,
		&i.Email,
		&i.Name,
		&i.Source,
		&i.ContactCreatedAt,
		&i.EmailVerified,
		&i.GdprConsent,
		&i.GdprConsentAt,
		&i.BlockedAt,
		&i.EmailsSent,
		&i.EmailsOpened,
		&i.EmailsClicked,
		&i.LastEmailAt,
		&i.LastOpenAt,
		&i.LastClickAt,
	)
	return i, err
}

const getSubscriberCampaignActivity = `-- name: GetSubscriberCampaignActivity :many
SELECT
    cs.id,
    cs.campaign_id,
    ec.name as campaign_name,
    ec.subject as campaign_subject,
    cs.status,
    cs.sent_at,
    cs.opened_at,
    cs.open_count,
    cs.clicked_at,
    cs.click_count
FROM campaign_sends cs
LEFT JOIN email_campaigns ec ON ec.id = cs.campaign_id
WHERE cs.contact_id = ?1
ORDER BY cs.sent_at DESC
LIMIT 50
`

type GetSubscriberCampaignActivityRow struct {
	ID              string         `json:"id"`
	CampaignID      string         `json:"campaign_id"`
	CampaignName    sql.NullString `json:"campaign_name"`
	CampaignSubject sql.NullString `json:"campaign_subject"`
	Status          sql.NullString `json:"status"`
	SentAt          sql.NullString `json:"sent_at"`
	OpenedAt        sql.NullString `json:"opened_at"`
	OpenCount       sql.NullInt64  `json:"open_count"`
	ClickedAt       sql.NullString `json:"clicked_at"`
	ClickCount      sql.NullInt64  `json:"click_count"`
}

func (q *Queries) GetSubscriberCampaignActivity(ctx context.Context, contactID string) ([]GetSubscriberCampaignActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriberCampaignActivity, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubscriberCampaignActivityRow
	for rows.Next() {
		var i GetSubscriberCampaignActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.CampaignName,
			&i.CampaignSubject,
			&i.Status,
			&i.SentAt,
			&i.OpenedAt,
			&i.OpenCount,
			&i.ClickedAt,
			&i.ClickCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriberSequenceEnrollments = `-- name: GetSubscriberSequenceEnrollments :many
SELECT
    css.id,
    css.sequence_id,
    es.name as sequence_name,
    css.current_position,
    css.is_active,
    css.started_at,
    css.completed_at,
    css.paused_at,
    css.unsubscribed_at
FROM contact_sequence_state css
LEFT JOIN email_sequences es ON es.id = css.sequence_id
WHERE css.contact_id = ?1
ORDER BY css.started_at DESC
`

type GetSubscriberSequenceEnrollmentsRow struct {
	ID              string         `json:"id"`
	SequenceID      sql.NullString `json:"sequence_id"`
	SequenceName    sql.NullString `json:"sequence_name"`
	CurrentPosition sql.NullInt64  `json:"current_position"`
	IsActive        sql.NullInt64  `json:"is_active"`
	StartedAt       sql.NullString `json:"started_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
	PausedAt        sql.NullString `json:"paused_at"`
	UnsubscribedAt  sql.NullString `json:"unsubscribed_at"`
}

func (q *Queries) GetSubscriberSequenceEnrollments(ctx context.Context, contactID sql.NullString) ([]GetSubscriberSequenceEnrollmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriberSequenceEnrollments, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubscriberSequenceEnrollmentsRow
	for rows.Next() {
		var i GetSubscriberSequenceEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SequenceID,
			&i.SequenceName,
			&i.CurrentPosition,
			&i.IsActive,
			&i.StartedAt,
			&i.CompletedAt,
			&i.PausedAt,
			&i.UnsubscribedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailLists = `-- name: ListEmailLists :many
SELECT id, public_id, org_id, name, slug, description, double_optin, confirmation_email_subject, confirmation_email_body, created_at, updated_at, public_page_enabled, thank_you_url, confirm_redirect_url, unsubscribe_redirect_url, thank_you_email_enabled, thank_you_email_subject, thank_you_email_body, already_subscribed_url, goodbye_email_enabled, goodbye_email_subject, goodbye_email_body, unsubscribe_behavior, unsubscribe_scope FROM email_lists
WHERE org_id = ?1
ORDER BY created_at DESC
`

func (q *Queries) ListEmailLists(ctx context.Context, orgID string) ([]EmailList, error) {
	rows, err := q.db.QueryContext(ctx, listEmailLists, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailList
	for rows.Next() {
		var i EmailList
		if err := rows.Scan(
			&i.ID,
			&i.PublicID,
			&i.OrgID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.DoubleOptin,
			&i.ConfirmationEmailSubject,
			&i.ConfirmationEmailBody,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublicPageEnabled,
			&i.ThankYouUrl,
			&i.ConfirmRedirectUrl,
			&i.UnsubscribeRedirectUrl,
			&i.ThankYouEmailEnabled,
			&i.ThankYouEmailSubject,
			&i.ThankYouEmailBody,
			&i.AlreadySubscribedUrl,
			&i.GoodbyeEmailEnabled,
			&i.GoodbyeEmailSubject,
			&i.GoodbyeEmailBody,
			&i.UnsubscribeBehavior,
			&i.UnsubscribeScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListSubscribers = `-- name: ListListSubscribers :many
SELECT ls.id, ls.list_id, ls.contact_id, ls.status, ls.verification_token, ls.verification_sent_at, ls.verified_at, ls.subscribed_at, ls.unsubscribed_at, c.email, c.name
FROM list_subscribers ls
JOIN contacts c ON c.id = ls.contact_id
WHERE ls.list_id = ?1
  AND (?2 IS NULL OR ?2 = '' OR ls.status = ?2)
ORDER BY ls.subscribed_at DESC
LIMIT ?4 OFFSET ?3
`

type ListListSubscribersParams struct {
	ListID       int64       `json:"list_id"`
	FilterStatus interface{} `json:"filter_status"`
	PageOffset   int64       `json:"page_offset"`
	PageSize     int64       `json:"page_size"`
}

type ListListSubscribersRow struct {
	ID                 string         `json:"id"`
	ListID             int64          `json:"list_id"`
	ContactID          string         `json:"contact_id"`
	Status             sql.NullString `json:"status"`
	VerificationToken  sql.NullString `json:"verification_token"`
	VerificationSentAt sql.NullString `json:"verification_sent_at"`
	VerifiedAt         sql.NullString `json:"verified_at"`
	SubscribedAt       sql.NullString `json:"subscribed_at"`
	UnsubscribedAt     sql.NullString `json:"unsubscribed_at"`
	Email              string         `json:"email"`
	Name               string         `json:"name"`
}

func (q *Queries) ListListSubscribers(ctx context.Context, arg ListListSubscribersParams) ([]ListListSubscribersRow, error) {
	rows, err := q.db.QueryContext(ctx, listListSubscribers,
		arg.ListID,
		arg.FilterStatus,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListListSubscribersRow
	for rows.Next() {
		var i ListListSubscribersRow
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.ContactID,
			&i.Status,
			&i.VerificationToken,
			&i.VerificationSentAt,
			&i.VerifiedAt,
			&i.SubscribedAt,
			&i.UnsubscribedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSubscriberFromList = `-- name: RemoveSubscriberFromList :exec
DELETE FROM list_subscribers
WHERE list_id = ?1 AND contact_id = ?2
`

type RemoveSubscriberFromListParams struct {
	ListID    int64  `json:"list_id"`
	ContactID string `json:"contact_id"`
}

func (q *Queries) RemoveSubscriberFromList(ctx context.Context, arg RemoveSubscriberFromListParams) error {
	_, err := q.db.ExecContext(ctx, removeSubscriberFromList, arg.ListID, arg.ContactID)
	return err
}

const subscribeToList = `-- name: SubscribeToList :one
INSERT INTO list_subscribers (
    id, list_id, contact_id, status, subscribed_at
) VALUES (
    ?1, ?2, ?3, 'active', datetime('now')
)
ON CONFLICT (list_id, contact_id) DO UPDATE
SET status = 'active', unsubscribed_at = NULL
RETURNING id, list_id, contact_id, status, verification_token, verification_sent_at, verified_at, subscribed_at, unsubscribed_at
`

type SubscribeToListParams struct {
	ID        string `json:"id"`
	ListID    int64  `json:"list_id"`
	ContactID string `json:"contact_id"`
}

func (q *Queries) SubscribeToList(ctx context.Context, arg SubscribeToListParams) (ListSubscriber, error) {
	row := q.db.QueryRowContext(ctx, subscribeToList, arg.ID, arg.ListID, arg.ContactID)
	var i ListSubscriber
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}

const subscribeToListPending = `-- name: SubscribeToListPending :one
INSERT INTO list_subscribers (
    id, list_id, contact_id, status, verification_token, verification_sent_at
) VALUES (
    ?1, ?2, ?3, 'pending',
    ?4, datetime('now')
)
ON CONFLICT (list_id, contact_id) DO UPDATE
SET status = CASE
    WHEN list_subscribers.status = 'active' THEN 'active'
    ELSE 'pending'
END,
verification_token = CASE
    WHEN list_subscribers.status = 'active' THEN list_subscribers.verification_token
    ELSE EXCLUDED.verification_token
END,
verification_sent_at = CASE
    WHEN list_subscribers.status = 'active' THEN list_subscribers.verification_sent_at
    ELSE datetime('now')
END,
unsubscribed_at = NULL
RETURNING id, list_id, contact_id, status, verification_token, verification_sent_at, verified_at, subscribed_at, unsubscribed_at
`

type SubscribeToListPendingParams struct {
	ID                string         `json:"id"`
	ListID            int64          `json:"list_id"`
	ContactID         string         `json:"contact_id"`
	VerificationToken sql.NullString `json:"verification_token"`
}

func (q *Queries) SubscribeToListPending(ctx context.Context, arg SubscribeToListPendingParams) (ListSubscriber, error) {
	row := q.db.QueryRowContext(ctx, subscribeToListPending,
		arg.ID,
		arg.ListID,
		arg.ContactID,
		arg.VerificationToken,
	)
	var i ListSubscriber
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ContactID,
		&i.Status,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.SubscribedAt,
		&i.UnsubscribedAt,
	)
	return i, err
}

const unsubscribeFromList = `-- name: UnsubscribeFromList :exec
UPDATE list_subscribers
SET status = 'unsubscribed', unsubscribed_at = datetime('now')
WHERE list_id = ?1 AND contact_id = ?2
`

type UnsubscribeFromListParams struct {
	ListID    int64  `json:"list_id"`
	ContactID string `json:"contact_id"`
}

func (q *Queries) UnsubscribeFromList(ctx context.Context, arg UnsubscribeFromListParams) error {
	_, err := q.db.ExecContext(ctx, unsubscribeFromList, arg.ListID, arg.ContactID)
	return err
}

const updateEmailList = `-- name: UpdateEmailList :one
UPDATE email_lists
SET name = COALESCE(?1, name),
    description = COALESCE(?2, description),
    double_optin = COALESCE(?3, double_optin),
    confirmation_email_subject = COALESCE(NULLIF(?4, ''), confirmation_email_subject),
    confirmation_email_body = COALESCE(NULLIF(?5, ''), confirmation_email_body),
    thank_you_url = COALESCE(NULLIF(?6, ''), thank_you_url),
    confirm_redirect_url = COALESCE(NULLIF(?7, ''), confirm_redirect_url),
    already_subscribed_url = COALESCE(NULLIF(?8, ''), already_subscribed_url),
    unsubscribe_redirect_url = COALESCE(NULLIF(?9, ''), unsubscribe_redirect_url),
    thank_you_email_enabled = COALESCE(?10, thank_you_email_enabled),
    thank_you_email_subject = COALESCE(NULLIF(?11, ''), thank_you_email_subject),
    thank_you_email_body = COALESCE(NULLIF(?12, ''), thank_you_email_body),
    goodbye_email_enabled = COALESCE(?13, goodbye_email_enabled),
    goodbye_email_subject = COALESCE(NULLIF(?14, ''), goodbye_email_subject),
    goodbye_email_body = COALESCE(NULLIF(?15, ''), goodbye_email_body),
    unsubscribe_behavior = COALESCE(NULLIF(?16, ''), unsubscribe_behavior),
    unsubscribe_scope = COALESCE(NULLIF(?17, ''), unsubscribe_scope),
    updated_at = datetime('now')
WHERE id = ?18
RETURNING id, public_id, org_id, name, slug, description, double_optin, confirmation_email_subject, confirmation_email_body, created_at, updated_at, public_page_enabled, thank_you_url, confirm_redirect_url, unsubscribe_redirect_url, thank_you_email_enabled, thank_you_email_subject, thank_you_email_body, already_subscribed_url, goodbye_email_enabled, goodbye_email_subject, goodbye_email_body, unsubscribe_behavior, unsubscribe_scope
`

type UpdateEmailListParams struct {
	Name                   string         `json:"name"`
	Description            sql.NullString `json:"description"`
	DoubleOptin            sql.NullInt64  `json:"double_optin"`
	ConfirmationSubject    interface{}    `json:"confirmation_subject"`
	ConfirmationBody       interface{}    `json:"confirmation_body"`
	ThankYouUrl            interface{}    `json:"thank_you_url"`
	ConfirmRedirectUrl     interface{}    `json:"confirm_redirect_url"`
	AlreadySubscribedUrl   interface{}    `json:"already_subscribed_url"`
	UnsubscribeRedirectUrl interface{}    `json:"unsubscribe_redirect_url"`
	ThankYouEmailEnabled   sql.NullInt64  `json:"thank_you_email_enabled"`
	ThankYouEmailSubject   interface{}    `json:"thank_you_email_subject"`
	ThankYouEmailBody      interface{}    `json:"thank_you_email_body"`
	GoodbyeEmailEnabled    sql.NullInt64  `json:"goodbye_email_enabled"`
	GoodbyeEmailSubject    interface{}    `json:"goodbye_email_subject"`
	GoodbyeEmailBody       interface{}    `json:"goodbye_email_body"`
	UnsubscribeBehavior    interface{}    `json:"unsubscribe_behavior"`
	UnsubscribeScope       interface{}    `json:"unsubscribe_scope"`
	ID                     int64          `json:"id"`
}

func (q *Queries) UpdateEmailList(ctx context.Context, arg UpdateEmailListParams) (EmailList, error) {
	row := q.db.QueryRowContext(ctx, updateEmailList,
		arg.Name,
		arg.Description,
		arg.DoubleOptin,
		arg.ConfirmationSubject,
		arg.ConfirmationBody,
		arg.ThankYouUrl,
		arg.ConfirmRedirectUrl,
		arg.AlreadySubscribedUrl,
		arg.UnsubscribeRedirectUrl,
		arg.ThankYouEmailEnabled,
		arg.ThankYouEmailSubject,
		arg.ThankYouEmailBody,
		arg.GoodbyeEmailEnabled,
		arg.GoodbyeEmailSubject,
		arg.GoodbyeEmailBody,
		arg.UnsubscribeBehavior,
		arg.UnsubscribeScope,
		arg.ID,
	)
	var i EmailList
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.DoubleOptin,
		&i.ConfirmationEmailSubject,
		&i.ConfirmationEmailBody,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublicPageEnabled,
		&i.ThankYouUrl,
		&i.ConfirmRedirectUrl,
		&i.UnsubscribeRedirectUrl,
		&i.ThankYouEmailEnabled,
		&i.ThankYouEmailSubject,
		&i.ThankYouEmailBody,
		&i.AlreadySubscribedUrl,
		&i.GoodbyeEmailEnabled,
		&i.GoodbyeEmailSubject,
		&i.GoodbyeEmailBody,
		&i.UnsubscribeBehavior,
		&i.UnsubscribeScope,
	)
	return i, err
}
