// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_campaigns.sql

package db

import (
	"context"
	"database/sql"
)

const checkCampaignSendExists = `-- name: CheckCampaignSendExists :one
SELECT COUNT(*) as count FROM campaign_sends
WHERE campaign_id = ?1 AND contact_id = ?2
`

type CheckCampaignSendExistsParams struct {
	CampaignID string `json:"campaign_id"`
	ContactID  string `json:"contact_id"`
}

func (q *Queries) CheckCampaignSendExists(ctx context.Context, arg CheckCampaignSendExistsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCampaignSendExists, arg.CampaignID, arg.ContactID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCampaignSendsByStatus = `-- name: CountCampaignSendsByStatus :one
SELECT COUNT(*) as count FROM campaign_sends
WHERE campaign_id = ?1 AND status = ?2
`

type CountCampaignSendsByStatusParams struct {
	CampaignID string         `json:"campaign_id"`
	Status     sql.NullString `json:"status"`
}

func (q *Queries) CountCampaignSendsByStatus(ctx context.Context, arg CountCampaignSendsByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCampaignSendsByStatus, arg.CampaignID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCampaigns = `-- name: CountCampaigns :one
SELECT COUNT(*) as count FROM email_campaigns
WHERE org_id = ?1
`

func (q *Queries) CountCampaigns(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCampaigns, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCampaignsByStatus = `-- name: CountCampaignsByStatus :one
SELECT COUNT(*) as count FROM email_campaigns
WHERE org_id = ?1 AND status = ?2
`

type CountCampaignsByStatusParams struct {
	OrgID  string         `json:"org_id"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) CountCampaignsByStatus(ctx context.Context, arg CountCampaignsByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCampaignsByStatus, arg.OrgID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingCampaignSends = `-- name: CountPendingCampaignSends :one
SELECT COUNT(*) as count FROM campaign_sends
WHERE campaign_id = ?1 AND status = 'pending'
`

func (q *Queries) CountPendingCampaignSends(ctx context.Context, campaignID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingCampaignSends, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSentCampaignSends = `-- name: CountSentCampaignSends :one
SELECT COUNT(*) as count FROM campaign_sends
WHERE campaign_id = ?1 AND status = 'sent'
`

func (q *Queries) CountSentCampaignSends(ctx context.Context, campaignID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSentCampaignSends, campaignID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCampaign = `-- name: CreateCampaign :one

INSERT INTO email_campaigns (
    id, org_id, design_id, name, subject, preview_text,
    from_name, from_email, reply_to,
    html_body, plain_text,
    list_ids, exclude_list_ids, segment_filter,
    status, scheduled_at, track_opens, track_clicks,
    created_at, updated_at
)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, datetime('now'), datetime('now'))
RETURNING id, org_id, design_id, name, subject, preview_text, from_name, from_email, reply_to, html_body, plain_text, list_ids, exclude_list_ids, segment_filter, status, scheduled_at, started_at, completed_at, track_opens, track_clicks, recipients_count, sent_count, delivered_count, opened_count, clicked_count, bounced_count, complained_count, unsubscribed_count, created_at, updated_at
`

type CreateCampaignParams struct {
	ID             string         `json:"id"`
	OrgID          string         `json:"org_id"`
	DesignID       sql.NullInt64  `json:"design_id"`
	Name           string         `json:"name"`
	Subject        string         `json:"subject"`
	PreviewText    sql.NullString `json:"preview_text"`
	FromName       sql.NullString `json:"from_name"`
	FromEmail      sql.NullString `json:"from_email"`
	ReplyTo        sql.NullString `json:"reply_to"`
	HtmlBody       string         `json:"html_body"`
	PlainText      sql.NullString `json:"plain_text"`
	ListIds        sql.NullString `json:"list_ids"`
	ExcludeListIds sql.NullString `json:"exclude_list_ids"`
	SegmentFilter  sql.NullString `json:"segment_filter"`
	Status         sql.NullString `json:"status"`
	ScheduledAt    sql.NullString `json:"scheduled_at"`
	TrackOpens     sql.NullInt64  `json:"track_opens"`
	TrackClicks    sql.NullInt64  `json:"track_clicks"`
}

// Email Campaigns (One-time Broadcasts)
// Campaign management
func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (EmailCampaign, error) {
	row := q.db.QueryRowContext(ctx, createCampaign,
		arg.ID,
		arg.OrgID,
		arg.DesignID,
		arg.Name,
		arg.Subject,
		arg.PreviewText,
		arg.FromName,
		arg.FromEmail,
		arg.ReplyTo,
		arg.HtmlBody,
		arg.PlainText,
		arg.ListIds,
		arg.ExcludeListIds,
		arg.SegmentFilter,
		arg.Status,
		arg.ScheduledAt,
		arg.TrackOpens,
		arg.TrackClicks,
	)
	var i EmailCampaign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DesignID,
		&i.Name,
		&i.Subject,
		&i.PreviewText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.HtmlBody,
		&i.PlainText,
		&i.ListIds,
		&i.ExcludeListIds,
		&i.SegmentFilter,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TrackOpens,
		&i.TrackClicks,
		&i.RecipientsCount,
		&i.SentCount,
		&i.DeliveredCount,
		&i.OpenedCount,
		&i.ClickedCount,
		&i.BouncedCount,
		&i.ComplainedCount,
		&i.UnsubscribedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCampaignClick = `-- name: CreateCampaignClick :one

INSERT INTO campaign_clicks (id, campaign_send_id, campaign_id, contact_id, link_url, link_name, clicked_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, datetime('now'))
RETURNING id, campaign_send_id, campaign_id, contact_id, link_url, link_name, clicked_at
`

type CreateCampaignClickParams struct {
	ID             string         `json:"id"`
	CampaignSendID string         `json:"campaign_send_id"`
	CampaignID     string         `json:"campaign_id"`
	ContactID      string         `json:"contact_id"`
	LinkUrl        string         `json:"link_url"`
	LinkName       sql.NullString `json:"link_name"`
}

// Campaign Clicks
func (q *Queries) CreateCampaignClick(ctx context.Context, arg CreateCampaignClickParams) (CampaignClick, error) {
	row := q.db.QueryRowContext(ctx, createCampaignClick,
		arg.ID,
		arg.CampaignSendID,
		arg.CampaignID,
		arg.ContactID,
		arg.LinkUrl,
		arg.LinkName,
	)
	var i CampaignClick
	err := row.Scan(
		&i.ID,
		&i.CampaignSendID,
		&i.CampaignID,
		&i.ContactID,
		&i.LinkUrl,
		&i.LinkName,
		&i.ClickedAt,
	)
	return i, err
}

const createCampaignSend = `-- name: CreateCampaignSend :one

INSERT INTO campaign_sends (id, campaign_id, contact_id, list_id, tracking_token, status, created_at)
VALUES (?1, ?2, ?3, ?4, ?5, 'pending', datetime('now'))
RETURNING id, campaign_id, contact_id, list_id, status, sent_at, delivered_at, tracking_token, opened_at, open_count, clicked_at, click_count, error_message, bounce_type, created_at, retry_count, failed_at
`

type CreateCampaignSendParams struct {
	ID            string         `json:"id"`
	CampaignID    string         `json:"campaign_id"`
	ContactID     string         `json:"contact_id"`
	ListID        sql.NullInt64  `json:"list_id"`
	TrackingToken sql.NullString `json:"tracking_token"`
}

// Campaign Sends
func (q *Queries) CreateCampaignSend(ctx context.Context, arg CreateCampaignSendParams) (CampaignSend, error) {
	row := q.db.QueryRowContext(ctx, createCampaignSend,
		arg.ID,
		arg.CampaignID,
		arg.ContactID,
		arg.ListID,
		arg.TrackingToken,
	)
	var i CampaignSend
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.ListID,
		&i.Status,
		&i.SentAt,
		&i.DeliveredAt,
		&i.TrackingToken,
		&i.OpenedAt,
		&i.OpenCount,
		&i.ClickedAt,
		&i.ClickCount,
		&i.ErrorMessage,
		&i.BounceType,
		&i.CreatedAt,
		&i.RetryCount,
		&i.FailedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM email_campaigns
WHERE id = ?1 AND org_id = ?2 AND status = 'draft'
`

type DeleteCampaignParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteCampaign(ctx context.Context, arg DeleteCampaignParams) error {
	_, err := q.db.ExecContext(ctx, deleteCampaign, arg.ID, arg.OrgID)
	return err
}

const getActiveSubscribersForList = `-- name: GetActiveSubscribersForList :many
SELECT c.id as contact_id, c.email, c.name, ls.list_id
FROM list_subscribers ls
JOIN contacts c ON c.id = ls.contact_id
WHERE ls.list_id = ?1
  AND ls.status = 'active'
  AND c.bounced_at IS NULL
  AND c.unsubscribed_at IS NULL
`

type GetActiveSubscribersForListRow struct {
	ContactID string `json:"contact_id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	ListID    int64  `json:"list_id"`
}

func (q *Queries) GetActiveSubscribersForList(ctx context.Context, listID int64) ([]GetActiveSubscribersForListRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSubscribersForList, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveSubscribersForListRow
	for rows.Next() {
		var i GetActiveSubscribersForListRow
		if err := rows.Scan(
			&i.ContactID,
			&i.Email,
			&i.Name,
			&i.ListID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOrgsEmailStats30Days = `-- name: GetAllOrgsEmailStats30Days :many
SELECT
    org_id,
    COALESCE(SUM(sent_count), 0) as emails_sent
FROM email_campaigns
WHERE status = 'sent'
  AND datetime(completed_at) > datetime('now', '-30 days')
GROUP BY org_id
`

type GetAllOrgsEmailStats30DaysRow struct {
	OrgID      string      `json:"org_id"`
	EmailsSent interface{} `json:"emails_sent"`
}

func (q *Queries) GetAllOrgsEmailStats30Days(ctx context.Context) ([]GetAllOrgsEmailStats30DaysRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllOrgsEmailStats30Days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllOrgsEmailStats30DaysRow
	for rows.Next() {
		var i GetAllOrgsEmailStats30DaysRow
		if err := rows.Scan(&i.OrgID, &i.EmailsSent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, org_id, design_id, name, subject, preview_text, from_name, from_email, reply_to, html_body, plain_text, list_ids, exclude_list_ids, segment_filter, status, scheduled_at, started_at, completed_at, track_opens, track_clicks, recipients_count, sent_count, delivered_count, opened_count, clicked_count, bounced_count, complained_count, unsubscribed_count, created_at, updated_at FROM email_campaigns
WHERE id = ?1 AND org_id = ?2
`

type GetCampaignParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetCampaign(ctx context.Context, arg GetCampaignParams) (EmailCampaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaign, arg.ID, arg.OrgID)
	var i EmailCampaign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DesignID,
		&i.Name,
		&i.Subject,
		&i.PreviewText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.HtmlBody,
		&i.PlainText,
		&i.ListIds,
		&i.ExcludeListIds,
		&i.SegmentFilter,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TrackOpens,
		&i.TrackClicks,
		&i.RecipientsCount,
		&i.SentCount,
		&i.DeliveredCount,
		&i.OpenedCount,
		&i.ClickedCount,
		&i.BouncedCount,
		&i.ComplainedCount,
		&i.UnsubscribedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignByID = `-- name: GetCampaignByID :one

SELECT id, org_id, design_id, name, subject, preview_text, from_name, from_email, reply_to, html_body, plain_text, list_ids, exclude_list_ids, segment_filter, status, scheduled_at, started_at, completed_at, track_opens, track_clicks, recipients_count, sent_count, delivered_count, opened_count, clicked_count, bounced_count, complained_count, unsubscribed_count, created_at, updated_at FROM email_campaigns
WHERE id = ?1
`

// Campaign Scheduler Queries
func (q *Queries) GetCampaignByID(ctx context.Context, id string) (EmailCampaign, error) {
	row := q.db.QueryRowContext(ctx, getCampaignByID, id)
	var i EmailCampaign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DesignID,
		&i.Name,
		&i.Subject,
		&i.PreviewText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.HtmlBody,
		&i.PlainText,
		&i.ListIds,
		&i.ExcludeListIds,
		&i.SegmentFilter,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TrackOpens,
		&i.TrackClicks,
		&i.RecipientsCount,
		&i.SentCount,
		&i.DeliveredCount,
		&i.OpenedCount,
		&i.ClickedCount,
		&i.BouncedCount,
		&i.ComplainedCount,
		&i.UnsubscribedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignLinkStats = `-- name: GetCampaignLinkStats :many
SELECT link_url, link_name, COUNT(*) as click_count
FROM campaign_clicks
WHERE campaign_id = ?1
GROUP BY link_url, link_name
ORDER BY click_count DESC
`

type GetCampaignLinkStatsRow struct {
	LinkUrl    string         `json:"link_url"`
	LinkName   sql.NullString `json:"link_name"`
	ClickCount int64          `json:"click_count"`
}

func (q *Queries) GetCampaignLinkStats(ctx context.Context, campaignID string) ([]GetCampaignLinkStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getCampaignLinkStats, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCampaignLinkStatsRow
	for rows.Next() {
		var i GetCampaignLinkStatsRow
		if err := rows.Scan(&i.LinkUrl, &i.LinkName, &i.ClickCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCampaignSend = `-- name: GetCampaignSend :one
SELECT id, campaign_id, contact_id, list_id, status, sent_at, delivered_at, tracking_token, opened_at, open_count, clicked_at, click_count, error_message, bounce_type, created_at, retry_count, failed_at FROM campaign_sends
WHERE id = ?1
`

func (q *Queries) GetCampaignSend(ctx context.Context, id string) (CampaignSend, error) {
	row := q.db.QueryRowContext(ctx, getCampaignSend, id)
	var i CampaignSend
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.ListID,
		&i.Status,
		&i.SentAt,
		&i.DeliveredAt,
		&i.TrackingToken,
		&i.OpenedAt,
		&i.OpenCount,
		&i.ClickedAt,
		&i.ClickCount,
		&i.ErrorMessage,
		&i.BounceType,
		&i.CreatedAt,
		&i.RetryCount,
		&i.FailedAt,
	)
	return i, err
}

const getCampaignSendByTracking = `-- name: GetCampaignSendByTracking :one
SELECT id, campaign_id, contact_id, list_id, status, sent_at, delivered_at, tracking_token, opened_at, open_count, clicked_at, click_count, error_message, bounce_type, created_at, retry_count, failed_at FROM campaign_sends
WHERE tracking_token = ?1
`

func (q *Queries) GetCampaignSendByTracking(ctx context.Context, trackingToken sql.NullString) (CampaignSend, error) {
	row := q.db.QueryRowContext(ctx, getCampaignSendByTracking, trackingToken)
	var i CampaignSend
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.ListID,
		&i.Status,
		&i.SentAt,
		&i.DeliveredAt,
		&i.TrackingToken,
		&i.OpenedAt,
		&i.OpenCount,
		&i.ClickedAt,
		&i.ClickCount,
		&i.ErrorMessage,
		&i.BounceType,
		&i.CreatedAt,
		&i.RetryCount,
		&i.FailedAt,
	)
	return i, err
}

const getDashboardEmailStats30Days = `-- name: GetDashboardEmailStats30Days :one

SELECT
    COALESCE(SUM(sent_count), 0) as emails_sent,
    COALESCE(SUM(opened_count), 0) as emails_opened,
    COALESCE(SUM(clicked_count), 0) as emails_clicked
FROM email_campaigns
WHERE org_id = ?1
  AND status = 'sent'
  AND datetime(completed_at) > datetime('now', '-30 days')
`

type GetDashboardEmailStats30DaysRow struct {
	EmailsSent    interface{} `json:"emails_sent"`
	EmailsOpened  interface{} `json:"emails_opened"`
	EmailsClicked interface{} `json:"emails_clicked"`
}

// Dashboard Stats
func (q *Queries) GetDashboardEmailStats30Days(ctx context.Context, orgID string) (GetDashboardEmailStats30DaysRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardEmailStats30Days, orgID)
	var i GetDashboardEmailStats30DaysRow
	err := row.Scan(&i.EmailsSent, &i.EmailsOpened, &i.EmailsClicked)
	return i, err
}

const getFailedCampaignSendsForRetry = `-- name: GetFailedCampaignSendsForRetry :many

SELECT cs.id, cs.campaign_id, cs.contact_id, cs.tracking_token, cs.retry_count, cs.failed_at,
       c.email, c.name,
       ec.subject, ec.html_body, ec.from_name, ec.from_email, ec.reply_to
FROM campaign_sends cs
JOIN contacts c ON c.id = cs.contact_id
JOIN email_campaigns ec ON ec.id = cs.campaign_id
WHERE cs.status = 'failed' AND cs.retry_count < 3
ORDER BY cs.failed_at ASC
LIMIT ?1
`

type GetFailedCampaignSendsForRetryRow struct {
	ID            string         `json:"id"`
	CampaignID    string         `json:"campaign_id"`
	ContactID     string         `json:"contact_id"`
	TrackingToken sql.NullString `json:"tracking_token"`
	RetryCount    sql.NullInt64  `json:"retry_count"`
	FailedAt      sql.NullString `json:"failed_at"`
	Email         string         `json:"email"`
	Name          string         `json:"name"`
	Subject       string         `json:"subject"`
	HtmlBody      string         `json:"html_body"`
	FromName      sql.NullString `json:"from_name"`
	FromEmail     sql.NullString `json:"from_email"`
	ReplyTo       sql.NullString `json:"reply_to"`
}

// Retry Worker Queries
func (q *Queries) GetFailedCampaignSendsForRetry(ctx context.Context, limitCount int64) ([]GetFailedCampaignSendsForRetryRow, error) {
	rows, err := q.db.QueryContext(ctx, getFailedCampaignSendsForRetry, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFailedCampaignSendsForRetryRow
	for rows.Next() {
		var i GetFailedCampaignSendsForRetryRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContactID,
			&i.TrackingToken,
			&i.RetryCount,
			&i.FailedAt,
			&i.Email,
			&i.Name,
			&i.Subject,
			&i.HtmlBody,
			&i.FromName,
			&i.FromEmail,
			&i.ReplyTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingCampaignSends = `-- name: GetPendingCampaignSends :many
SELECT cs.id, cs.campaign_id, cs.contact_id, cs.list_id, cs.tracking_token, cs.status,
       c.email, c.name,
       ec.subject, ec.html_body, ec.plain_text, ec.from_name, ec.from_email, ec.reply_to,
       ec.track_opens, ec.track_clicks, ec.org_id
FROM campaign_sends cs
JOIN contacts c ON c.id = cs.contact_id
JOIN email_campaigns ec ON ec.id = cs.campaign_id
WHERE cs.status = 'pending'
ORDER BY cs.created_at ASC
LIMIT ?1
`

type GetPendingCampaignSendsRow struct {
	ID            string         `json:"id"`
	CampaignID    string         `json:"campaign_id"`
	ContactID     string         `json:"contact_id"`
	ListID        sql.NullInt64  `json:"list_id"`
	TrackingToken sql.NullString `json:"tracking_token"`
	Status        sql.NullString `json:"status"`
	Email         string         `json:"email"`
	Name          string         `json:"name"`
	Subject       string         `json:"subject"`
	HtmlBody      string         `json:"html_body"`
	PlainText     sql.NullString `json:"plain_text"`
	FromName      sql.NullString `json:"from_name"`
	FromEmail     sql.NullString `json:"from_email"`
	ReplyTo       sql.NullString `json:"reply_to"`
	TrackOpens    sql.NullInt64  `json:"track_opens"`
	TrackClicks   sql.NullInt64  `json:"track_clicks"`
	OrgID         string         `json:"org_id"`
}

func (q *Queries) GetPendingCampaignSends(ctx context.Context, limitCount int64) ([]GetPendingCampaignSendsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingCampaignSends, limitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingCampaignSendsRow
	for rows.Next() {
		var i GetPendingCampaignSendsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContactID,
			&i.ListID,
			&i.TrackingToken,
			&i.Status,
			&i.Email,
			&i.Name,
			&i.Subject,
			&i.HtmlBody,
			&i.PlainText,
			&i.FromName,
			&i.FromEmail,
			&i.ReplyTo,
			&i.TrackOpens,
			&i.TrackClicks,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledCampaigns = `-- name: GetScheduledCampaigns :many
SELECT id, org_id, design_id, name, subject, preview_text, from_name, from_email, reply_to, html_body, plain_text, list_ids, exclude_list_ids, segment_filter, status, scheduled_at, started_at, completed_at, track_opens, track_clicks, recipients_count, sent_count, delivered_count, opened_count, clicked_count, bounced_count, complained_count, unsubscribed_count, created_at, updated_at FROM email_campaigns
WHERE status = 'scheduled' AND scheduled_at <= datetime('now')
ORDER BY scheduled_at ASC
`

func (q *Queries) GetScheduledCampaigns(ctx context.Context) ([]EmailCampaign, error) {
	rows, err := q.db.QueryContext(ctx, getScheduledCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailCampaign
	for rows.Next() {
		var i EmailCampaign
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DesignID,
			&i.Name,
			&i.Subject,
			&i.PreviewText,
			&i.FromName,
			&i.FromEmail,
			&i.ReplyTo,
			&i.HtmlBody,
			&i.PlainText,
			&i.ListIds,
			&i.ExcludeListIds,
			&i.SegmentFilter,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TrackOpens,
			&i.TrackClicks,
			&i.RecipientsCount,
			&i.SentCount,
			&i.DeliveredCount,
			&i.OpenedCount,
			&i.ClickedCount,
			&i.BouncedCount,
			&i.ComplainedCount,
			&i.UnsubscribedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementCampaignClicked = `-- name: IncrementCampaignClicked :exec
UPDATE email_campaigns
SET clicked_count = clicked_count + 1
WHERE id = ?1
`

func (q *Queries) IncrementCampaignClicked(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementCampaignClicked, id)
	return err
}

const incrementCampaignOpened = `-- name: IncrementCampaignOpened :exec
UPDATE email_campaigns
SET opened_count = opened_count + 1
WHERE id = ?1
`

func (q *Queries) IncrementCampaignOpened(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementCampaignOpened, id)
	return err
}

const incrementCampaignSendRetry = `-- name: IncrementCampaignSendRetry :exec
UPDATE campaign_sends
SET retry_count = retry_count + 1
WHERE id = ?1
`

func (q *Queries) IncrementCampaignSendRetry(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementCampaignSendRetry, id)
	return err
}

const incrementCampaignSent = `-- name: IncrementCampaignSent :exec
UPDATE email_campaigns
SET sent_count = sent_count + 1
WHERE id = ?1
`

func (q *Queries) IncrementCampaignSent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementCampaignSent, id)
	return err
}

const listCampaignClicks = `-- name: ListCampaignClicks :many
SELECT cc.id, cc.campaign_send_id, cc.campaign_id, cc.contact_id, cc.link_url, cc.link_name, cc.clicked_at, c.email
FROM campaign_clicks cc
JOIN contacts c ON cc.contact_id = c.id
WHERE cc.campaign_id = ?1
ORDER BY cc.clicked_at DESC
LIMIT ?3 OFFSET ?2
`

type ListCampaignClicksParams struct {
	CampaignID string `json:"campaign_id"`
	PageOffset int64  `json:"page_offset"`
	PageSize   int64  `json:"page_size"`
}

type ListCampaignClicksRow struct {
	ID             string         `json:"id"`
	CampaignSendID string         `json:"campaign_send_id"`
	CampaignID     string         `json:"campaign_id"`
	ContactID      string         `json:"contact_id"`
	LinkUrl        string         `json:"link_url"`
	LinkName       sql.NullString `json:"link_name"`
	ClickedAt      sql.NullString `json:"clicked_at"`
	Email          string         `json:"email"`
}

func (q *Queries) ListCampaignClicks(ctx context.Context, arg ListCampaignClicksParams) ([]ListCampaignClicksRow, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignClicks, arg.CampaignID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignClicksRow
	for rows.Next() {
		var i ListCampaignClicksRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignSendID,
			&i.CampaignID,
			&i.ContactID,
			&i.LinkUrl,
			&i.LinkName,
			&i.ClickedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignSends = `-- name: ListCampaignSends :many
SELECT cs.id, cs.campaign_id, cs.contact_id, cs.list_id, cs.status, cs.sent_at, cs.delivered_at, cs.tracking_token, cs.opened_at, cs.open_count, cs.clicked_at, cs.click_count, cs.error_message, cs.bounce_type, cs.created_at, cs.retry_count, cs.failed_at, c.email, c.name
FROM campaign_sends cs
JOIN contacts c ON cs.contact_id = c.id
WHERE cs.campaign_id = ?1
ORDER BY cs.created_at DESC
LIMIT ?3 OFFSET ?2
`

type ListCampaignSendsParams struct {
	CampaignID string `json:"campaign_id"`
	PageOffset int64  `json:"page_offset"`
	PageSize   int64  `json:"page_size"`
}

type ListCampaignSendsRow struct {
	ID            string         `json:"id"`
	CampaignID    string         `json:"campaign_id"`
	ContactID     string         `json:"contact_id"`
	ListID        sql.NullInt64  `json:"list_id"`
	Status        sql.NullString `json:"status"`
	SentAt        sql.NullString `json:"sent_at"`
	DeliveredAt   sql.NullString `json:"delivered_at"`
	TrackingToken sql.NullString `json:"tracking_token"`
	OpenedAt      sql.NullString `json:"opened_at"`
	OpenCount     sql.NullInt64  `json:"open_count"`
	ClickedAt     sql.NullString `json:"clicked_at"`
	ClickCount    sql.NullInt64  `json:"click_count"`
	ErrorMessage  sql.NullString `json:"error_message"`
	BounceType    sql.NullString `json:"bounce_type"`
	CreatedAt     sql.NullString `json:"created_at"`
	RetryCount    sql.NullInt64  `json:"retry_count"`
	FailedAt      sql.NullString `json:"failed_at"`
	Email         string         `json:"email"`
	Name          string         `json:"name"`
}

func (q *Queries) ListCampaignSends(ctx context.Context, arg ListCampaignSendsParams) ([]ListCampaignSendsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignSends, arg.CampaignID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignSendsRow
	for rows.Next() {
		var i ListCampaignSendsRow
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.ContactID,
			&i.ListID,
			&i.Status,
			&i.SentAt,
			&i.DeliveredAt,
			&i.TrackingToken,
			&i.OpenedAt,
			&i.OpenCount,
			&i.ClickedAt,
			&i.ClickCount,
			&i.ErrorMessage,
			&i.BounceType,
			&i.CreatedAt,
			&i.RetryCount,
			&i.FailedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, org_id, design_id, name, subject, preview_text, from_name, from_email, reply_to, html_body, plain_text, list_ids, exclude_list_ids, segment_filter, status, scheduled_at, started_at, completed_at, track_opens, track_clicks, recipients_count, sent_count, delivered_count, opened_count, clicked_count, bounced_count, complained_count, unsubscribed_count, created_at, updated_at FROM email_campaigns
WHERE org_id = ?1
ORDER BY created_at DESC
LIMIT ?3 OFFSET ?2
`

type ListCampaignsParams struct {
	OrgID      string `json:"org_id"`
	PageOffset int64  `json:"page_offset"`
	PageSize   int64  `json:"page_size"`
}

func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]EmailCampaign, error) {
	rows, err := q.db.QueryContext(ctx, listCampaigns, arg.OrgID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailCampaign
	for rows.Next() {
		var i EmailCampaign
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DesignID,
			&i.Name,
			&i.Subject,
			&i.PreviewText,
			&i.FromName,
			&i.FromEmail,
			&i.ReplyTo,
			&i.HtmlBody,
			&i.PlainText,
			&i.ListIds,
			&i.ExcludeListIds,
			&i.SegmentFilter,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TrackOpens,
			&i.TrackClicks,
			&i.RecipientsCount,
			&i.SentCount,
			&i.DeliveredCount,
			&i.OpenedCount,
			&i.ClickedCount,
			&i.BouncedCount,
			&i.ComplainedCount,
			&i.UnsubscribedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaignsByStatus = `-- name: ListCampaignsByStatus :many
SELECT id, org_id, design_id, name, subject, preview_text, from_name, from_email, reply_to, html_body, plain_text, list_ids, exclude_list_ids, segment_filter, status, scheduled_at, started_at, completed_at, track_opens, track_clicks, recipients_count, sent_count, delivered_count, opened_count, clicked_count, bounced_count, complained_count, unsubscribed_count, created_at, updated_at FROM email_campaigns
WHERE org_id = ?1 AND status = ?2
ORDER BY created_at DESC
LIMIT ?4 OFFSET ?3
`

type ListCampaignsByStatusParams struct {
	OrgID      string         `json:"org_id"`
	Status     sql.NullString `json:"status"`
	PageOffset int64          `json:"page_offset"`
	PageSize   int64          `json:"page_size"`
}

func (q *Queries) ListCampaignsByStatus(ctx context.Context, arg ListCampaignsByStatusParams) ([]EmailCampaign, error) {
	rows, err := q.db.QueryContext(ctx, listCampaignsByStatus,
		arg.OrgID,
		arg.Status,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailCampaign
	for rows.Next() {
		var i EmailCampaign
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DesignID,
			&i.Name,
			&i.Subject,
			&i.PreviewText,
			&i.FromName,
			&i.FromEmail,
			&i.ReplyTo,
			&i.HtmlBody,
			&i.PlainText,
			&i.ListIds,
			&i.ExcludeListIds,
			&i.SegmentFilter,
			&i.Status,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.TrackOpens,
			&i.TrackClicks,
			&i.RecipientsCount,
			&i.SentCount,
			&i.DeliveredCount,
			&i.OpenedCount,
			&i.ClickedCount,
			&i.BouncedCount,
			&i.ComplainedCount,
			&i.UnsubscribedCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCampaignSendFailed = `-- name: MarkCampaignSendFailed :exec
UPDATE campaign_sends
SET status = 'failed', error_message = ?1
WHERE id = ?2
`

type MarkCampaignSendFailedParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) MarkCampaignSendFailed(ctx context.Context, arg MarkCampaignSendFailedParams) error {
	_, err := q.db.ExecContext(ctx, markCampaignSendFailed, arg.ErrorMessage, arg.ID)
	return err
}

const markCampaignSendPermanentlyFailed = `-- name: MarkCampaignSendPermanentlyFailed :exec
UPDATE campaign_sends
SET status = 'permanent_failure'
WHERE id = ?1
`

func (q *Queries) MarkCampaignSendPermanentlyFailed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markCampaignSendPermanentlyFailed, id)
	return err
}

const markCampaignSendSent = `-- name: MarkCampaignSendSent :exec
UPDATE campaign_sends
SET status = 'sent', sent_at = datetime('now')
WHERE id = ?1
`

func (q *Queries) MarkCampaignSendSent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markCampaignSendSent, id)
	return err
}

const recordCampaignClick = `-- name: RecordCampaignClick :exec
UPDATE campaign_sends
SET clicked_at = COALESCE(clicked_at, datetime('now')),
    click_count = click_count + 1
WHERE id = ?1
`

func (q *Queries) RecordCampaignClick(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, recordCampaignClick, id)
	return err
}

const recordCampaignOpen = `-- name: RecordCampaignOpen :exec
UPDATE campaign_sends
SET opened_at = COALESCE(opened_at, datetime('now')),
    open_count = open_count + 1
WHERE id = ?1
`

func (q *Queries) RecordCampaignOpen(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, recordCampaignOpen, id)
	return err
}

const scheduleCampaign = `-- name: ScheduleCampaign :one
UPDATE email_campaigns
SET status = 'scheduled',
    scheduled_at = ?1,
    updated_at = datetime('now')
WHERE id = ?2 AND org_id = ?3 AND status = 'draft'
RETURNING id, org_id, design_id, name, subject, preview_text, from_name, from_email, reply_to, html_body, plain_text, list_ids, exclude_list_ids, segment_filter, status, scheduled_at, started_at, completed_at, track_opens, track_clicks, recipients_count, sent_count, delivered_count, opened_count, clicked_count, bounced_count, complained_count, unsubscribed_count, created_at, updated_at
`

type ScheduleCampaignParams struct {
	ScheduledAt sql.NullString `json:"scheduled_at"`
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
}

func (q *Queries) ScheduleCampaign(ctx context.Context, arg ScheduleCampaignParams) (EmailCampaign, error) {
	row := q.db.QueryRowContext(ctx, scheduleCampaign, arg.ScheduledAt, arg.ID, arg.OrgID)
	var i EmailCampaign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DesignID,
		&i.Name,
		&i.Subject,
		&i.PreviewText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.HtmlBody,
		&i.PlainText,
		&i.ListIds,
		&i.ExcludeListIds,
		&i.SegmentFilter,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TrackOpens,
		&i.TrackClicks,
		&i.RecipientsCount,
		&i.SentCount,
		&i.DeliveredCount,
		&i.OpenedCount,
		&i.ClickedCount,
		&i.BouncedCount,
		&i.ComplainedCount,
		&i.UnsubscribedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCampaignRecipientsCount = `-- name: SetCampaignRecipientsCount :exec
UPDATE email_campaigns
SET recipients_count = ?1,
    updated_at = datetime('now')
WHERE id = ?2
`

type SetCampaignRecipientsCountParams struct {
	RecipientsCount sql.NullInt64 `json:"recipients_count"`
	ID              string        `json:"id"`
}

func (q *Queries) SetCampaignRecipientsCount(ctx context.Context, arg SetCampaignRecipientsCountParams) error {
	_, err := q.db.ExecContext(ctx, setCampaignRecipientsCount, arg.RecipientsCount, arg.ID)
	return err
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE email_campaigns
SET name = COALESCE(NULLIF(?1, ''), name),
    subject = COALESCE(NULLIF(?2, ''), subject),
    preview_text = COALESCE(NULLIF(?3, ''), preview_text),
    from_name = COALESCE(NULLIF(?4, ''), from_name),
    from_email = COALESCE(NULLIF(?5, ''), from_email),
    reply_to = COALESCE(NULLIF(?6, ''), reply_to),
    html_body = COALESCE(NULLIF(?7, ''), html_body),
    plain_text = COALESCE(NULLIF(?8, ''), plain_text),
    list_ids = COALESCE(NULLIF(?9, ''), list_ids),
    exclude_list_ids = COALESCE(NULLIF(?10, ''), exclude_list_ids),
    segment_filter = COALESCE(NULLIF(?11, ''), segment_filter),
    track_opens = COALESCE(?12, track_opens),
    track_clicks = COALESCE(?13, track_clicks),
    updated_at = datetime('now')
WHERE id = ?14 AND org_id = ?15 AND status = 'draft'
RETURNING id, org_id, design_id, name, subject, preview_text, from_name, from_email, reply_to, html_body, plain_text, list_ids, exclude_list_ids, segment_filter, status, scheduled_at, started_at, completed_at, track_opens, track_clicks, recipients_count, sent_count, delivered_count, opened_count, clicked_count, bounced_count, complained_count, unsubscribed_count, created_at, updated_at
`

type UpdateCampaignParams struct {
	Name           interface{}   `json:"name"`
	Subject        interface{}   `json:"subject"`
	PreviewText    interface{}   `json:"preview_text"`
	FromName       interface{}   `json:"from_name"`
	FromEmail      interface{}   `json:"from_email"`
	ReplyTo        interface{}   `json:"reply_to"`
	HtmlBody       interface{}   `json:"html_body"`
	PlainText      interface{}   `json:"plain_text"`
	ListIds        interface{}   `json:"list_ids"`
	ExcludeListIds interface{}   `json:"exclude_list_ids"`
	SegmentFilter  interface{}   `json:"segment_filter"`
	TrackOpens     sql.NullInt64 `json:"track_opens"`
	TrackClicks    sql.NullInt64 `json:"track_clicks"`
	ID             string        `json:"id"`
	OrgID          string        `json:"org_id"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (EmailCampaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaign,
		arg.Name,
		arg.Subject,
		arg.PreviewText,
		arg.FromName,
		arg.FromEmail,
		arg.ReplyTo,
		arg.HtmlBody,
		arg.PlainText,
		arg.ListIds,
		arg.ExcludeListIds,
		arg.SegmentFilter,
		arg.TrackOpens,
		arg.TrackClicks,
		arg.ID,
		arg.OrgID,
	)
	var i EmailCampaign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DesignID,
		&i.Name,
		&i.Subject,
		&i.PreviewText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.HtmlBody,
		&i.PlainText,
		&i.ListIds,
		&i.ExcludeListIds,
		&i.SegmentFilter,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TrackOpens,
		&i.TrackClicks,
		&i.RecipientsCount,
		&i.SentCount,
		&i.DeliveredCount,
		&i.OpenedCount,
		&i.ClickedCount,
		&i.BouncedCount,
		&i.ComplainedCount,
		&i.UnsubscribedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignSendStatus = `-- name: UpdateCampaignSendStatus :exec
UPDATE campaign_sends
SET status = ?1,
    sent_at = CASE WHEN ?1 = 'sent' THEN datetime('now') ELSE sent_at END,
    delivered_at = CASE WHEN ?1 = 'delivered' THEN datetime('now') ELSE delivered_at END,
    error_message = ?2,
    bounce_type = ?3
WHERE id = ?4
`

type UpdateCampaignSendStatusParams struct {
	Status       sql.NullString `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
	BounceType   sql.NullString `json:"bounce_type"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateCampaignSendStatus(ctx context.Context, arg UpdateCampaignSendStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCampaignSendStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.BounceType,
		arg.ID,
	)
	return err
}

const updateCampaignStats = `-- name: UpdateCampaignStats :exec
UPDATE email_campaigns
SET recipients_count = ?1,
    sent_count = ?2,
    delivered_count = ?3,
    opened_count = ?4,
    clicked_count = ?5,
    bounced_count = ?6,
    complained_count = ?7,
    unsubscribed_count = ?8
WHERE id = ?9 AND org_id = ?10
`

type UpdateCampaignStatsParams struct {
	RecipientsCount   sql.NullInt64 `json:"recipients_count"`
	SentCount         sql.NullInt64 `json:"sent_count"`
	DeliveredCount    sql.NullInt64 `json:"delivered_count"`
	OpenedCount       sql.NullInt64 `json:"opened_count"`
	ClickedCount      sql.NullInt64 `json:"clicked_count"`
	BouncedCount      sql.NullInt64 `json:"bounced_count"`
	ComplainedCount   sql.NullInt64 `json:"complained_count"`
	UnsubscribedCount sql.NullInt64 `json:"unsubscribed_count"`
	ID                string        `json:"id"`
	OrgID             string        `json:"org_id"`
}

func (q *Queries) UpdateCampaignStats(ctx context.Context, arg UpdateCampaignStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateCampaignStats,
		arg.RecipientsCount,
		arg.SentCount,
		arg.DeliveredCount,
		arg.OpenedCount,
		arg.ClickedCount,
		arg.BouncedCount,
		arg.ComplainedCount,
		arg.UnsubscribedCount,
		arg.ID,
		arg.OrgID,
	)
	return err
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :one
UPDATE email_campaigns
SET status = ?1,
    started_at = CASE WHEN ?1 = 'sending' THEN datetime('now') ELSE started_at END,
    completed_at = CASE WHEN ?1 = 'sent' THEN datetime('now') ELSE completed_at END,
    updated_at = datetime('now')
WHERE id = ?2 AND org_id = ?3
RETURNING id, org_id, design_id, name, subject, preview_text, from_name, from_email, reply_to, html_body, plain_text, list_ids, exclude_list_ids, segment_filter, status, scheduled_at, started_at, completed_at, track_opens, track_clicks, recipients_count, sent_count, delivered_count, opened_count, clicked_count, bounced_count, complained_count, unsubscribed_count, created_at, updated_at
`

type UpdateCampaignStatusParams struct {
	Status sql.NullString `json:"status"`
	ID     string         `json:"id"`
	OrgID  string         `json:"org_id"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (EmailCampaign, error) {
	row := q.db.QueryRowContext(ctx, updateCampaignStatus, arg.Status, arg.ID, arg.OrgID)
	var i EmailCampaign
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DesignID,
		&i.Name,
		&i.Subject,
		&i.PreviewText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.HtmlBody,
		&i.PlainText,
		&i.ListIds,
		&i.ExcludeListIds,
		&i.SegmentFilter,
		&i.Status,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.TrackOpens,
		&i.TrackClicks,
		&i.RecipientsCount,
		&i.SentCount,
		&i.DeliveredCount,
		&i.OpenedCount,
		&i.ClickedCount,
		&i.BouncedCount,
		&i.ComplainedCount,
		&i.UnsubscribedCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCampaignStatusByID = `-- name: UpdateCampaignStatusByID :exec
UPDATE email_campaigns
SET status = ?1,
    started_at = CASE WHEN ?1 = 'sending' THEN datetime('now') ELSE started_at END,
    completed_at = CASE WHEN ?1 = 'sent' THEN datetime('now') ELSE completed_at END,
    updated_at = datetime('now')
WHERE id = ?2
`

type UpdateCampaignStatusByIDParams struct {
	Status sql.NullString `json:"status"`
	ID     string         `json:"id"`
}

func (q *Queries) UpdateCampaignStatusByID(ctx context.Context, arg UpdateCampaignStatusByIDParams) error {
	_, err := q.db.ExecContext(ctx, updateCampaignStatusByID, arg.Status, arg.ID)
	return err
}
