// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: public_pages.sql

package db

import (
	"context"
	"database/sql"
)

const getCampaignSendByTrackingToken = `-- name: GetCampaignSendByTrackingToken :one
SELECT
    cs.id,
    cs.campaign_id,
    cs.contact_id,
    cs.tracking_token,
    cs.status,
    c.email,
    c.name,
    ec.subject,
    ec.html_body,
    el.name as list_name,
    el.unsubscribe_redirect_url,
    o.name as org_name
FROM campaign_sends cs
JOIN contacts c ON c.id = cs.contact_id
JOIN email_campaigns ec ON ec.id = cs.campaign_id
LEFT JOIN email_lists el ON el.id = ec.list_id
LEFT JOIN organizations o ON o.id = ec.org_id
WHERE cs.tracking_token = ?1
LIMIT 1
`

type GetCampaignSendByTrackingTokenRow struct {
	ID                     string         `json:"id"`
	CampaignID             string         `json:"campaign_id"`
	ContactID              string         `json:"contact_id"`
	TrackingToken          sql.NullString `json:"tracking_token"`
	Status                 sql.NullString `json:"status"`
	Email                  string         `json:"email"`
	Name                   string         `json:"name"`
	Subject                string         `json:"subject"`
	HtmlBody               string         `json:"html_body"`
	ListName               sql.NullString `json:"list_name"`
	UnsubscribeRedirectUrl sql.NullString `json:"unsubscribe_redirect_url"`
	OrgName                sql.NullString `json:"org_name"`
}

func (q *Queries) GetCampaignSendByTrackingToken(ctx context.Context, token sql.NullString) (GetCampaignSendByTrackingTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getCampaignSendByTrackingToken, token)
	var i GetCampaignSendByTrackingTokenRow
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.ContactID,
		&i.TrackingToken,
		&i.Status,
		&i.Email,
		&i.Name,
		&i.Subject,
		&i.HtmlBody,
		&i.ListName,
		&i.UnsubscribeRedirectUrl,
		&i.OrgName,
	)
	return i, err
}

const getContactByEmailForPublicPage = `-- name: GetContactByEmailForPublicPage :one
SELECT c.id, c.org_id, c.name, c.email, c.source, c.created_at, c.updated_at, c.email_verified, c.verification_token, c.verification_sent_at, c.verified_at, c.unsubscribed_at, c.blocked_at, c.status, c.gdpr_consent, c.gdpr_consent_at, ls.status as subscription_status, ls.list_id
FROM contacts c
LEFT JOIN list_subscribers ls ON ls.contact_id = c.id AND ls.list_id = ?1
WHERE c.email = ?2 AND c.org_id = ?3
LIMIT 1
`

type GetContactByEmailForPublicPageParams struct {
	ListID int64          `json:"list_id"`
	Email  string         `json:"email"`
	OrgID  sql.NullString `json:"org_id"`
}

type GetContactByEmailForPublicPageRow struct {
	ID                 string         `json:"id"`
	OrgID              sql.NullString `json:"org_id"`
	Name               string         `json:"name"`
	Email              string         `json:"email"`
	Source             sql.NullString `json:"source"`
	CreatedAt          sql.NullString `json:"created_at"`
	UpdatedAt          sql.NullString `json:"updated_at"`
	EmailVerified      int64          `json:"email_verified"`
	VerificationToken  sql.NullString `json:"verification_token"`
	VerificationSentAt sql.NullString `json:"verification_sent_at"`
	VerifiedAt         sql.NullString `json:"verified_at"`
	UnsubscribedAt     sql.NullString `json:"unsubscribed_at"`
	BlockedAt          sql.NullString `json:"blocked_at"`
	Status             sql.NullString `json:"status"`
	GdprConsent        sql.NullInt64  `json:"gdpr_consent"`
	GdprConsentAt      sql.NullString `json:"gdpr_consent_at"`
	SubscriptionStatus sql.NullString `json:"subscription_status"`
	ListID             sql.NullInt64  `json:"list_id"`
}

func (q *Queries) GetContactByEmailForPublicPage(ctx context.Context, arg GetContactByEmailForPublicPageParams) (GetContactByEmailForPublicPageRow, error) {
	row := q.db.QueryRowContext(ctx, getContactByEmailForPublicPage, arg.ListID, arg.Email, arg.OrgID)
	var i GetContactByEmailForPublicPageRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerified,
		&i.VerificationToken,
		&i.VerificationSentAt,
		&i.VerifiedAt,
		&i.UnsubscribedAt,
		&i.BlockedAt,
		&i.Status,
		&i.GdprConsent,
		&i.GdprConsentAt,
		&i.SubscriptionStatus,
		&i.ListID,
	)
	return i, err
}

const getEmailQueueByTrackingToken = `-- name: GetEmailQueueByTrackingToken :one
SELECT
    eq.id,
    eq.tracking_token,
    eq.contact_id,
    eq.template_id,
    eq.status,
    c.email,
    c.name,
    et.subject,
    et.html_body,
    et.template_type,
    et.is_transactional,
    el.name as list_name,
    el.unsubscribe_redirect_url,
    o.name as org_name
FROM email_queue eq
JOIN contacts c ON c.id = eq.contact_id
LEFT JOIN email_templates et ON et.id = eq.template_id
LEFT JOIN email_sequences es ON es.id = et.sequence_id
LEFT JOIN email_lists el ON el.id = es.list_id
LEFT JOIN organizations o ON o.id = el.org_id
WHERE eq.tracking_token = ?1
LIMIT 1
`

type GetEmailQueueByTrackingTokenRow struct {
	ID                     string         `json:"id"`
	TrackingToken          sql.NullString `json:"tracking_token"`
	ContactID              sql.NullString `json:"contact_id"`
	TemplateID             sql.NullString `json:"template_id"`
	Status                 sql.NullString `json:"status"`
	Email                  string         `json:"email"`
	Name                   string         `json:"name"`
	Subject                sql.NullString `json:"subject"`
	HtmlBody               sql.NullString `json:"html_body"`
	TemplateType           sql.NullString `json:"template_type"`
	IsTransactional        sql.NullInt64  `json:"is_transactional"`
	ListName               sql.NullString `json:"list_name"`
	UnsubscribeRedirectUrl sql.NullString `json:"unsubscribe_redirect_url"`
	OrgName                sql.NullString `json:"org_name"`
}

func (q *Queries) GetEmailQueueByTrackingToken(ctx context.Context, token sql.NullString) (GetEmailQueueByTrackingTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getEmailQueueByTrackingToken, token)
	var i GetEmailQueueByTrackingTokenRow
	err := row.Scan(
		&i.ID,
		&i.TrackingToken,
		&i.ContactID,
		&i.TemplateID,
		&i.Status,
		&i.Email,
		&i.Name,
		&i.Subject,
		&i.HtmlBody,
		&i.TemplateType,
		&i.IsTransactional,
		&i.ListName,
		&i.UnsubscribeRedirectUrl,
		&i.OrgName,
	)
	return i, err
}

const getListByIDForPublicPage = `-- name: GetListByIDForPublicPage :one
SELECT
    el.id,
    el.org_id,
    el.name,
    el.slug,
    el.description,
    el.double_optin,
    el.public_page_enabled,
    el.thank_you_url,
    el.confirm_redirect_url,
    el.unsubscribe_redirect_url,
    el.confirmation_email_subject,
    el.confirmation_email_body,
    o.name as org_name,
    o.slug as org_slug,
    o.from_name,
    o.from_email,
    o.settings as org_settings
FROM email_lists el
JOIN organizations o ON o.id = el.org_id
WHERE el.id = ?1
  AND (el.public_page_enabled IS NULL OR el.public_page_enabled = 1)
LIMIT 1
`

type GetListByIDForPublicPageRow struct {
	ID                       int64          `json:"id"`
	OrgID                    string         `json:"org_id"`
	Name                     string         `json:"name"`
	Slug                     string         `json:"slug"`
	Description              sql.NullString `json:"description"`
	DoubleOptin              sql.NullInt64  `json:"double_optin"`
	PublicPageEnabled        sql.NullInt64  `json:"public_page_enabled"`
	ThankYouUrl              sql.NullString `json:"thank_you_url"`
	ConfirmRedirectUrl       sql.NullString `json:"confirm_redirect_url"`
	UnsubscribeRedirectUrl   sql.NullString `json:"unsubscribe_redirect_url"`
	ConfirmationEmailSubject sql.NullString `json:"confirmation_email_subject"`
	ConfirmationEmailBody    sql.NullString `json:"confirmation_email_body"`
	OrgName                  string         `json:"org_name"`
	OrgSlug                  string         `json:"org_slug"`
	FromName                 sql.NullString `json:"from_name"`
	FromEmail                sql.NullString `json:"from_email"`
	OrgSettings              sql.NullString `json:"org_settings"`
}

func (q *Queries) GetListByIDForPublicPage(ctx context.Context, id int64) (GetListByIDForPublicPageRow, error) {
	row := q.db.QueryRowContext(ctx, getListByIDForPublicPage, id)
	var i GetListByIDForPublicPageRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.DoubleOptin,
		&i.PublicPageEnabled,
		&i.ThankYouUrl,
		&i.ConfirmRedirectUrl,
		&i.UnsubscribeRedirectUrl,
		&i.ConfirmationEmailSubject,
		&i.ConfirmationEmailBody,
		&i.OrgName,
		&i.OrgSlug,
		&i.FromName,
		&i.FromEmail,
		&i.OrgSettings,
	)
	return i, err
}

const getListByPublicIDForPublicPage = `-- name: GetListByPublicIDForPublicPage :one
SELECT
    el.id,
    el.org_id,
    el.name,
    el.slug,
    el.public_id,
    el.description,
    el.double_optin,
    el.public_page_enabled,
    el.thank_you_url,
    el.confirm_redirect_url,
    el.unsubscribe_redirect_url,
    el.confirmation_email_subject,
    el.confirmation_email_body,
    o.name as org_name,
    o.slug as org_slug,
    o.from_name,
    o.from_email,
    o.settings as org_settings
FROM email_lists el
JOIN organizations o ON o.id = el.org_id
WHERE el.public_id = ?1
  AND (el.public_page_enabled IS NULL OR el.public_page_enabled = 1)
LIMIT 1
`

type GetListByPublicIDForPublicPageRow struct {
	ID                       int64          `json:"id"`
	OrgID                    string         `json:"org_id"`
	Name                     string         `json:"name"`
	Slug                     string         `json:"slug"`
	PublicID                 string         `json:"public_id"`
	Description              sql.NullString `json:"description"`
	DoubleOptin              sql.NullInt64  `json:"double_optin"`
	PublicPageEnabled        sql.NullInt64  `json:"public_page_enabled"`
	ThankYouUrl              sql.NullString `json:"thank_you_url"`
	ConfirmRedirectUrl       sql.NullString `json:"confirm_redirect_url"`
	UnsubscribeRedirectUrl   sql.NullString `json:"unsubscribe_redirect_url"`
	ConfirmationEmailSubject sql.NullString `json:"confirmation_email_subject"`
	ConfirmationEmailBody    sql.NullString `json:"confirmation_email_body"`
	OrgName                  string         `json:"org_name"`
	OrgSlug                  string         `json:"org_slug"`
	FromName                 sql.NullString `json:"from_name"`
	FromEmail                sql.NullString `json:"from_email"`
	OrgSettings              sql.NullString `json:"org_settings"`
}

func (q *Queries) GetListByPublicIDForPublicPage(ctx context.Context, publicID string) (GetListByPublicIDForPublicPageRow, error) {
	row := q.db.QueryRowContext(ctx, getListByPublicIDForPublicPage, publicID)
	var i GetListByPublicIDForPublicPageRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.PublicID,
		&i.Description,
		&i.DoubleOptin,
		&i.PublicPageEnabled,
		&i.ThankYouUrl,
		&i.ConfirmRedirectUrl,
		&i.UnsubscribeRedirectUrl,
		&i.ConfirmationEmailSubject,
		&i.ConfirmationEmailBody,
		&i.OrgName,
		&i.OrgSlug,
		&i.FromName,
		&i.FromEmail,
		&i.OrgSettings,
	)
	return i, err
}

const getListBySlugForPublicPage = `-- name: GetListBySlugForPublicPage :one

SELECT
    el.id,
    el.org_id,
    el.name,
    el.slug,
    el.description,
    el.double_optin,
    el.public_page_enabled,
    el.thank_you_url,
    el.confirm_redirect_url,
    el.unsubscribe_redirect_url,
    el.confirmation_email_subject,
    el.confirmation_email_body,
    o.name as org_name,
    o.slug as org_slug,
    o.from_name,
    o.from_email,
    o.settings as org_settings
FROM email_lists el
JOIN organizations o ON o.id = el.org_id
WHERE el.slug = ?1
  AND (el.public_page_enabled IS NULL OR el.public_page_enabled = 1)
LIMIT 1
`

type GetListBySlugForPublicPageRow struct {
	ID                       int64          `json:"id"`
	OrgID                    string         `json:"org_id"`
	Name                     string         `json:"name"`
	Slug                     string         `json:"slug"`
	Description              sql.NullString `json:"description"`
	DoubleOptin              sql.NullInt64  `json:"double_optin"`
	PublicPageEnabled        sql.NullInt64  `json:"public_page_enabled"`
	ThankYouUrl              sql.NullString `json:"thank_you_url"`
	ConfirmRedirectUrl       sql.NullString `json:"confirm_redirect_url"`
	UnsubscribeRedirectUrl   sql.NullString `json:"unsubscribe_redirect_url"`
	ConfirmationEmailSubject sql.NullString `json:"confirmation_email_subject"`
	ConfirmationEmailBody    sql.NullString `json:"confirmation_email_body"`
	OrgName                  string         `json:"org_name"`
	OrgSlug                  string         `json:"org_slug"`
	FromName                 sql.NullString `json:"from_name"`
	FromEmail                sql.NullString `json:"from_email"`
	OrgSettings              sql.NullString `json:"org_settings"`
}

// Public Pages Queries
// These support the server-side rendered public subscribe/confirm/unsubscribe pages
func (q *Queries) GetListBySlugForPublicPage(ctx context.Context, slug string) (GetListBySlugForPublicPageRow, error) {
	row := q.db.QueryRowContext(ctx, getListBySlugForPublicPage, slug)
	var i GetListBySlugForPublicPageRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.DoubleOptin,
		&i.PublicPageEnabled,
		&i.ThankYouUrl,
		&i.ConfirmRedirectUrl,
		&i.UnsubscribeRedirectUrl,
		&i.ConfirmationEmailSubject,
		&i.ConfirmationEmailBody,
		&i.OrgName,
		&i.OrgSlug,
		&i.FromName,
		&i.FromEmail,
		&i.OrgSettings,
	)
	return i, err
}

const getOrgEmailConfig = `-- name: GetOrgEmailConfig :one
SELECT id, settings FROM organizations WHERE id = ?1
`

type GetOrgEmailConfigRow struct {
	ID       string         `json:"id"`
	Settings sql.NullString `json:"settings"`
}

func (q *Queries) GetOrgEmailConfig(ctx context.Context, id string) (GetOrgEmailConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgEmailConfig, id)
	var i GetOrgEmailConfigRow
	err := row.Scan(&i.ID, &i.Settings)
	return i, err
}

const getTransactionalSendByTrackingToken = `-- name: GetTransactionalSendByTrackingToken :one
SELECT
    ts.id,
    ts.contact_id,
    ts.tracking_token,
    ts.status,
    ts.to_email as email,
    ts.to_name as name,
    te.subject,
    te.html_body,
    o.name as org_name
FROM transactional_sends ts
JOIN transactional_emails te ON te.id = ts.template_id
JOIN organizations o ON o.id = ts.org_id
WHERE ts.tracking_token = ?1
LIMIT 1
`

type GetTransactionalSendByTrackingTokenRow struct {
	ID            string         `json:"id"`
	ContactID     sql.NullString `json:"contact_id"`
	TrackingToken sql.NullString `json:"tracking_token"`
	Status        sql.NullString `json:"status"`
	Email         string         `json:"email"`
	Name          sql.NullString `json:"name"`
	Subject       string         `json:"subject"`
	HtmlBody      string         `json:"html_body"`
	OrgName       string         `json:"org_name"`
}

func (q *Queries) GetTransactionalSendByTrackingToken(ctx context.Context, token sql.NullString) (GetTransactionalSendByTrackingTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionalSendByTrackingToken, token)
	var i GetTransactionalSendByTrackingTokenRow
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.TrackingToken,
		&i.Status,
		&i.Email,
		&i.Name,
		&i.Subject,
		&i.HtmlBody,
		&i.OrgName,
	)
	return i, err
}

const updateListPublicPageSettings = `-- name: UpdateListPublicPageSettings :exec
UPDATE email_lists
SET public_page_enabled = ?1,
    thank_you_url = ?2,
    confirm_redirect_url = ?3,
    unsubscribe_redirect_url = ?4,
    updated_at = datetime('now')
WHERE id = ?5
`

type UpdateListPublicPageSettingsParams struct {
	PublicPageEnabled      sql.NullInt64  `json:"public_page_enabled"`
	ThankYouUrl            sql.NullString `json:"thank_you_url"`
	ConfirmRedirectUrl     sql.NullString `json:"confirm_redirect_url"`
	UnsubscribeRedirectUrl sql.NullString `json:"unsubscribe_redirect_url"`
	ID                     int64          `json:"id"`
}

func (q *Queries) UpdateListPublicPageSettings(ctx context.Context, arg UpdateListPublicPageSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateListPublicPageSettings,
		arg.PublicPageEnabled,
		arg.ThankYouUrl,
		arg.ConfirmRedirectUrl,
		arg.UnsubscribeRedirectUrl,
		arg.ID,
	)
	return err
}

const updateOrgSettings = `-- name: UpdateOrgSettings :exec
UPDATE organizations
SET settings = ?1, updated_at = datetime('now')
WHERE id = ?2
`

type UpdateOrgSettingsParams struct {
	Settings sql.NullString `json:"settings"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateOrgSettings(ctx context.Context, arg UpdateOrgSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateOrgSettings, arg.Settings, arg.ID)
	return err
}
