// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddBlockedDomain(ctx context.Context, arg AddBlockedDomainParams) (BlockedDomain, error)
	AddContactTag(ctx context.Context, arg AddContactTagParams) (ContactTag, error)
	// ========== SUPPRESSION LIST ==========
	AddToSuppressionList(ctx context.Context, arg AddToSuppressionListParams) (SuppressionList, error)
	AddUserToOrganization(ctx context.Context, arg AddUserToOrganizationParams) error
	BlockContact(ctx context.Context, id string) error
	// ========== BLOCK CONTACT BY EMAIL ==========
	BlockContactByEmail(ctx context.Context, email string) error
	// Used when subscribing with multiple field values at once
	BulkCreateCustomFieldValues(ctx context.Context, arg BulkCreateCustomFieldValuesParams) error
	BulkInsertBlockedDomains(ctx context.Context, arg BulkInsertBlockedDomainsParams) error
	CancelAllContactSequences(ctx context.Context, arg CancelAllContactSequencesParams) error
	CancelContactSequence(ctx context.Context, arg CancelContactSequenceParams) error
	CancelEmail(ctx context.Context, id string) error
	CancelEmailsForContact(ctx context.Context, contactID sql.NullString) error
	CancelImportJob(ctx context.Context, arg CancelImportJobParams) error
	CancelPendingEmailsForContactSequence(ctx context.Context, arg CancelPendingEmailsForContactSequenceParams) error
	CheckCampaignSendExists(ctx context.Context, arg CheckCampaignSendExistsParams) (int64, error)
	CheckEmailExists(ctx context.Context, email string) (int64, error)
	// Check if an event has already been processed by a rule
	CheckEventProcessed(ctx context.Context, arg CheckEventProcessedParams) (int64, error)
	CheckListSubscription(ctx context.Context, arg CheckListSubscriptionParams) (int64, error)
	CleanupExpiredMCPOAuthCodes(ctx context.Context) error
	CleanupExpiredMCPOAuthTokens(ctx context.Context) error
	// Delete sessions older than 30 days
	CleanupOldMCPSessions(ctx context.Context) error
	ClearSuppressionList(ctx context.Context, orgID string) error
	CompleteContactSequence(ctx context.Context, arg CompleteContactSequenceParams) error
	ConfirmListSubscription(ctx context.Context, token sql.NullString) (ListSubscriber, error)
	CountActiveSequencesForContact(ctx context.Context, contactID sql.NullString) (int64, error)
	CountActiveSubscribers(ctx context.Context, listID int64) (int64, error)
	// Count automation log entries with optional filters
	CountAutomationLog(ctx context.Context, arg CountAutomationLogParams) (int64, error)
	CountBackups(ctx context.Context) (int64, error)
	CountBlockedDomains(ctx context.Context, orgID string) (int64, error)
	CountBouncesInDateRange(ctx context.Context, arg CountBouncesInDateRangeParams) (int64, error)
	CountCampaignSendsByStatus(ctx context.Context, arg CountCampaignSendsByStatusParams) (int64, error)
	CountCampaigns(ctx context.Context, orgID string) (int64, error)
	CountCampaignsByStatus(ctx context.Context, arg CountCampaignsByStatusParams) (int64, error)
	CountComplaintsInDateRange(ctx context.Context, arg CountComplaintsInDateRangeParams) (int64, error)
	CountContacts(ctx context.Context) (int64, error)
	CountContactsByOrg(ctx context.Context, orgID sql.NullString) (int64, error)
	CountContactsByStatus(ctx context.Context, status sql.NullString) (int64, error)
	CountContactsByTag(ctx context.Context, tag string) (int64, error)
	CountCustomFieldsByList(ctx context.Context, listID int64) (int64, error)
	CountEmailDesigns(ctx context.Context, orgID string) (int64, error)
	CountEmailDesignsByCategory(ctx context.Context, arg CountEmailDesignsByCategoryParams) (int64, error)
	CountInactiveContacts90Days(ctx context.Context, orgID sql.NullString) (int64, error)
	CountListSubscribers(ctx context.Context, arg CountListSubscribersParams) (int64, error)
	// Count rules with optional filters
	CountOrgRules(ctx context.Context, arg CountOrgRulesParams) (int64, error)
	CountPendingCampaignSends(ctx context.Context, campaignID string) (int64, error)
	CountSentCampaignSends(ctx context.Context, campaignID string) (int64, error)
	CountSuppressedEmails(ctx context.Context, orgID string) (int64, error)
	CountTemplatesBySequence(ctx context.Context, sequenceID sql.NullString) (int64, error)
	CountTransactionalEmails(ctx context.Context, orgID string) (int64, error)
	CountTransactionalSends(ctx context.Context, templateID string) (int64, error)
	CountUnconfirmedContactsOlderThan(ctx context.Context, arg CountUnconfirmedContactsOlderThanParams) (int64, error)
	CountUsers(ctx context.Context, arg CountUsersParams) (int64, error)
	CountWebhookLogs(ctx context.Context, webhookID string) (int64, error)
	CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) (AuthToken, error)
	CreateBackupRecord(ctx context.Context, arg CreateBackupRecordParams) (BackupHistory, error)
	// ========== BLOCKED DOMAINS ==========
	CreateBlockedDomain(ctx context.Context, arg CreateBlockedDomainParams) (BlockedDomain, error)
	// Email Campaigns (One-time Broadcasts)
	// Campaign management
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (EmailCampaign, error)
	// Campaign Clicks
	CreateCampaignClick(ctx context.Context, arg CreateCampaignClickParams) (CampaignClick, error)
	// Campaign Sends
	CreateCampaignSend(ctx context.Context, arg CreateCampaignSendParams) (CampaignSend, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	CreateContactSequenceState(ctx context.Context, arg CreateContactSequenceStateParams) (ContactSequenceState, error)
	CreateCustomField(ctx context.Context, arg CreateCustomFieldParams) (CustomField, error)
	// Custom Field Values
	CreateCustomFieldValue(ctx context.Context, arg CreateCustomFieldValueParams) (CustomFieldValue, error)
	CreateDomainIdentity(ctx context.Context, arg CreateDomainIdentityParams) (DomainIdentity, error)
	// Email blocklist queries for bounce and complaint management
	// ========== BOUNCES ==========
	CreateEmailBounce(ctx context.Context, arg CreateEmailBounceParams) (EmailBounce, error)
	CreateEmailClick(ctx context.Context, arg CreateEmailClickParams) (EmailClick, error)
	// ========== COMPLAINTS ==========
	CreateEmailComplaint(ctx context.Context, arg CreateEmailComplaintParams) (EmailComplaint, error)
	// Email Designs (Global Templates)
	// Reusable email designs at org level
	CreateEmailDesign(ctx context.Context, arg CreateEmailDesignParams) (EmailDesign, error)
	CreateEmailList(ctx context.Context, arg CreateEmailListParams) (EmailList, error)
	CreateEntryRule(ctx context.Context, arg CreateEntryRuleParams) (SequenceEntryRule, error)
	// ========== IMPORT JOBS ==========
	CreateImportJob(ctx context.Context, arg CreateImportJobParams) (ImportJob, error)
	CreateListSubscriber(ctx context.Context, arg CreateListSubscriberParams) (ListSubscriber, error)
	// MCP API Keys
	CreateMCPAPIKey(ctx context.Context, arg CreateMCPAPIKeyParams) (McpApiKey, error)
	// MCP OAuth Clients
	CreateMCPOAuthClient(ctx context.Context, arg CreateMCPOAuthClientParams) (McpOauthClient, error)
	// MCP OAuth Authorization Codes
	CreateMCPOAuthCode(ctx context.Context, arg CreateMCPOAuthCodeParams) (McpOauthCode, error)
	// MCP OAuth Tokens
	CreateMCPOAuthToken(ctx context.Context, arg CreateMCPOAuthTokenParams) (McpOauthToken, error)
	// Create a new rule
	CreateOrgRule(ctx context.Context, arg CreateOrgRuleParams) (OrgRule, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	// Create a new rule template (platform admin only)
	CreateRuleTemplate(ctx context.Context, arg CreateRuleTemplateParams) (RuleTemplate, error)
	CreateSequence(ctx context.Context, arg CreateSequenceParams) (EmailSequence, error)
	CreateTemplate(ctx context.Context, arg CreateTemplateParams) (EmailTemplate, error)
	// Transactional Emails
	// API-triggered transactional email templates and sends
	// Templates
	CreateTransactionalEmail(ctx context.Context, arg CreateTransactionalEmailParams) (TransactionalEmail, error)
	// Sends (Logging)
	CreateTransactionalSend(ctx context.Context, arg CreateTransactionalSendParams) (TransactionalSend, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	CreateWebhookLog(ctx context.Context, arg CreateWebhookLogParams) (WebhookLog, error)
	DeactivateMCPOAuthClient(ctx context.Context, id string) error
	DeleteAuthTokensByUser(ctx context.Context, arg DeleteAuthTokensByUserParams) error
	DeleteBackup(ctx context.Context, id string) error
	DeleteBlockedDomain(ctx context.Context, arg DeleteBlockedDomainParams) error
	DeleteBlockedDomainByID(ctx context.Context, arg DeleteBlockedDomainByIDParams) error
	DeleteCampaign(ctx context.Context, arg DeleteCampaignParams) error
	DeleteContact(ctx context.Context, id string) error
	DeleteCustomField(ctx context.Context, id string) error
	DeleteCustomFieldValue(ctx context.Context, arg DeleteCustomFieldValueParams) error
	DeleteCustomFieldValuesBySubscriber(ctx context.Context, subscriberID string) error
	DeleteCustomFieldsByList(ctx context.Context, listID int64) error
	DeleteDomainIdentity(ctx context.Context, id string) error
	DeleteDomainIdentityByOrg(ctx context.Context, arg DeleteDomainIdentityByOrgParams) error
	DeleteEmailBounce(ctx context.Context, email string) error
	DeleteEmailComplaint(ctx context.Context, email string) error
	DeleteEmailDesign(ctx context.Context, arg DeleteEmailDesignParams) error
	DeleteEmailList(ctx context.Context, id int64) error
	DeleteEntryRule(ctx context.Context, id string) error
	DeleteEntryRulesBySequence(ctx context.Context, sequenceID string) error
	DeleteExpiredAuthTokens(ctx context.Context) error
	DeleteFromSuppressionList(ctx context.Context, arg DeleteFromSuppressionListParams) error
	DeleteImportJob(ctx context.Context, arg DeleteImportJobParams) error
	DeleteInactiveContacts90Days(ctx context.Context, orgID sql.NullString) (int64, error)
	DeleteMCPAPIKey(ctx context.Context, id string) error
	DeleteMCPSession(ctx context.Context, sessionID string) error
	DeleteOldBackups(ctx context.Context, daysAgo sql.NullString) error
	// Delete a rule
	DeleteOrgRule(ctx context.Context, arg DeleteOrgRuleParams) error
	DeleteOrganization(ctx context.Context, id string) error
	DeletePlatformSetting(ctx context.Context, key string) error
	// Delete a rule template
	DeleteRuleTemplate(ctx context.Context, id string) error
	DeleteSequence(ctx context.Context, id string) error
	DeleteSuppressionByID(ctx context.Context, arg DeleteSuppressionByIDParams) error
	DeleteTemplate(ctx context.Context, id string) error
	DeleteTransactionalEmail(ctx context.Context, arg DeleteTransactionalEmailParams) error
	DeleteUnconfirmedContactsOlderThan(ctx context.Context, arg DeleteUnconfirmedContactsOlderThanParams) (int64, error)
	DeleteUser(ctx context.Context, id string) error
	DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error
	GetActiveEntryRuleForTrigger(ctx context.Context, arg GetActiveEntryRuleForTriggerParams) ([]GetActiveEntryRuleForTriggerRow, error)
	GetActiveSequenceForContact(ctx context.Context, contactID sql.NullString) (GetActiveSequenceForContactRow, error)
	GetActiveSubscribersForList(ctx context.Context, listID int64) ([]GetActiveSubscribersForListRow, error)
	// Get all rules for an organization (including disabled), for admin listing
	GetAllOrgRules(ctx context.Context, orgID string) ([]OrgRule, error)
	GetAuthTokenByToken(ctx context.Context, token string) (AuthToken, error)
	// Get recent automation log entries for an organization
	GetAutomationLog(ctx context.Context, arg GetAutomationLogParams) ([]AutomationLog, error)
	// Get automation log entries for a specific rule
	GetAutomationLogByRule(ctx context.Context, arg GetAutomationLogByRuleParams) ([]AutomationLog, error)
	// Get automation log with filters
	GetAutomationLogFiltered(ctx context.Context, arg GetAutomationLogFilteredParams) ([]AutomationLog, error)
	// Get stats for automation log (for dashboard)
	GetAutomationLogStats(ctx context.Context, orgID string) (GetAutomationLogStatsRow, error)
	GetBackup(ctx context.Context, id string) (BackupHistory, error)
	GetBackupsByType(ctx context.Context, arg GetBackupsByTypeParams) ([]BackupHistory, error)
	GetBackupsInProgress(ctx context.Context) ([]BackupHistory, error)
	GetBlockedDomain(ctx context.Context, arg GetBlockedDomainParams) (BlockedDomain, error)
	GetCampaign(ctx context.Context, arg GetCampaignParams) (EmailCampaign, error)
	// Campaign Scheduler Queries
	GetCampaignByID(ctx context.Context, id string) (EmailCampaign, error)
	GetCampaignLinkStats(ctx context.Context, campaignID string) ([]GetCampaignLinkStatsRow, error)
	GetCampaignSend(ctx context.Context, id string) (CampaignSend, error)
	GetCampaignSendByTracking(ctx context.Context, trackingToken sql.NullString) (CampaignSend, error)
	GetCampaignSendByTrackingToken(ctx context.Context, token sql.NullString) (GetCampaignSendByTrackingTokenRow, error)
	GetConfirmationTemplate(ctx context.Context, sequenceID sql.NullString) (GetConfirmationTemplateRow, error)
	GetContact(ctx context.Context, id string) (Contact, error)
	GetContactByEmail(ctx context.Context, email string) (Contact, error)
	GetContactByEmailForPublicPage(ctx context.Context, arg GetContactByEmailForPublicPageParams) (GetContactByEmailForPublicPageRow, error)
	GetContactByID(ctx context.Context, id string) (Contact, error)
	GetContactByOrgAndEmail(ctx context.Context, arg GetContactByOrgAndEmailParams) (Contact, error)
	GetContactByOrgID(ctx context.Context, arg GetContactByOrgIDParams) (Contact, error)
	GetContactByTrackingToken(ctx context.Context, trackingToken sql.NullString) (Contact, error)
	GetContactByVerificationToken(ctx context.Context, token sql.NullString) (Contact, error)
	// ============================================
	// GDPR EXPORT QUERIES
	// ============================================
	GetContactCampaignSends(ctx context.Context, contactID string) ([]GetContactCampaignSendsRow, error)
	GetContactEmailClicks(ctx context.Context, contactID sql.NullString) ([]GetContactEmailClicksRow, error)
	GetContactSequenceEmails(ctx context.Context, contactID sql.NullString) ([]GetContactSequenceEmailsRow, error)
	GetContactSequenceState(ctx context.Context, arg GetContactSequenceStateParams) (GetContactSequenceStateRow, error)
	GetContactSequenceStateWithDetails(ctx context.Context, arg GetContactSequenceStateWithDetailsParams) (GetContactSequenceStateWithDetailsRow, error)
	GetContactTags(ctx context.Context, contactID sql.NullString) ([]ContactTag, error)
	GetContactTransactionalSends(ctx context.Context, contactID sql.NullString) ([]GetContactTransactionalSendsRow, error)
	GetContactsByTag(ctx context.Context, arg GetContactsByTagParams) ([]Contact, error)
	GetCustomField(ctx context.Context, id string) (CustomField, error)
	GetCustomFieldByKey(ctx context.Context, arg GetCustomFieldByKeyParams) (CustomField, error)
	GetCustomFieldValue(ctx context.Context, arg GetCustomFieldValueParams) (CustomFieldValue, error)
	// Dashboard Stats
	GetDashboardEmailStats30Days(ctx context.Context, orgID string) (GetDashboardEmailStats30DaysRow, error)
	GetDashboardSubscriberGrowth(ctx context.Context, orgID sql.NullString) (GetDashboardSubscriberGrowthRow, error)
	// ============================================
	// DASHBOARD STATS QUERIES
	// ============================================
	GetDashboardSubscriberStats(ctx context.Context, orgID sql.NullString) (GetDashboardSubscriberStatsRow, error)
	// Get all rule templates marked as defaults
	GetDefaultRuleTemplates(ctx context.Context) ([]RuleTemplate, error)
	GetDomainIdentity(ctx context.Context, id string) (DomainIdentity, error)
	GetDomainIdentityByDomain(ctx context.Context, arg GetDomainIdentityByDomainParams) (DomainIdentity, error)
	GetEmailBounce(ctx context.Context, email string) (EmailBounce, error)
	GetEmailByTrackingToken(ctx context.Context, trackingToken sql.NullString) (GetEmailByTrackingTokenRow, error)
	GetEmailComplaint(ctx context.Context, email string) (EmailComplaint, error)
	GetEmailDesign(ctx context.Context, arg GetEmailDesignParams) (EmailDesign, error)
	GetEmailDesignBySlug(ctx context.Context, arg GetEmailDesignBySlugParams) (EmailDesign, error)
	GetEmailList(ctx context.Context, id int64) (EmailList, error)
	GetEmailListByOrgAndSlug(ctx context.Context, arg GetEmailListByOrgAndSlugParams) (EmailList, error)
	GetEmailListByPublicID(ctx context.Context, publicID string) (EmailList, error)
	GetEmailQueueByTrackingToken(ctx context.Context, token sql.NullString) (GetEmailQueueByTrackingTokenRow, error)
	GetEmailQueueForContact(ctx context.Context, contactID sql.NullString) ([]GetEmailQueueForContactRow, error)
	GetEmailStatsForSequence(ctx context.Context, sequenceID sql.NullString) (GetEmailStatsForSequenceRow, error)
	GetEmailStatsForTemplate(ctx context.Context, templateID sql.NullString) (GetEmailStatsForTemplateRow, error)
	GetEmailStatsInDateRange(ctx context.Context, arg GetEmailStatsInDateRangeParams) (GetEmailStatsInDateRangeRow, error)
	// Get enabled rules for a specific entity (e.g., email_list, product)
	GetEntityRules(ctx context.Context, arg GetEntityRulesParams) ([]OrgRule, error)
	GetEntryRule(ctx context.Context, id string) (SequenceEntryRule, error)
	// Retry Worker Queries
	GetFailedCampaignSendsForRetry(ctx context.Context, limitCount int64) ([]GetFailedCampaignSendsForRetryRow, error)
	GetImportJob(ctx context.Context, arg GetImportJobParams) (ImportJob, error)
	GetLatestBackup(ctx context.Context) (BackupHistory, error)
	GetListByIDForPublicPage(ctx context.Context, id int64) (GetListByIDForPublicPageRow, error)
	GetListByPublicIDForPublicPage(ctx context.Context, publicID string) (GetListByPublicIDForPublicPageRow, error)
	// Public Pages Queries
	// These support the server-side rendered public subscribe/confirm/unsubscribe pages
	GetListBySlugForPublicPage(ctx context.Context, slug string) (GetListBySlugForPublicPageRow, error)
	GetListSubscriber(ctx context.Context, arg GetListSubscriberParams) (ListSubscriber, error)
	GetListSubscriberByID(ctx context.Context, id string) (GetListSubscriberByIDRow, error)
	GetListSubscriberByToken(ctx context.Context, token sql.NullString) (GetListSubscriberByTokenRow, error)
	GetListSubscriberDetail(ctx context.Context, id string) (GetListSubscriberDetailRow, error)
	GetMCPAPIKeyByHash(ctx context.Context, keyHash string) (GetMCPAPIKeyByHashRow, error)
	GetMCPAPIKeyByPrefix(ctx context.Context, keyPrefix string) ([]McpApiKey, error)
	GetMCPOAuthClientByClientID(ctx context.Context, clientID string) (McpOauthClient, error)
	GetMCPOAuthCodeByHash(ctx context.Context, codeHash string) (GetMCPOAuthCodeByHashRow, error)
	GetMCPOAuthTokenByAccessHash(ctx context.Context, accessTokenHash string) (GetMCPOAuthTokenByAccessHashRow, error)
	GetMCPOAuthTokenByRefreshHash(ctx context.Context, refreshTokenHash sql.NullString) (GetMCPOAuthTokenByRefreshHashRow, error)
	GetMCPSession(ctx context.Context, sessionID string) (McpSession, error)
	// Fallback: get most recent org selection for a user (when session ID changes)
	GetMCPSessionByUser(ctx context.Context, userID string) (McpSession, error)
	GetNextTemplate(ctx context.Context, arg GetNextTemplateParams) (GetNextTemplateRow, error)
	GetOrgEmailConfig(ctx context.Context, id string) (GetOrgEmailConfigRow, error)
	GetOrgEmailSettings(ctx context.Context, id string) (GetOrgEmailSettingsRow, error)
	// Get a single rule by ID
	GetOrgRuleById(ctx context.Context, arg GetOrgRuleByIdParams) (OrgRule, error)
	// =====================================================
	// Org Rules
	// =====================================================
	// Get all enabled rules for an organization, ordered by salience
	GetOrgRules(ctx context.Context, orgID string) ([]OrgRule, error)
	// Get enabled rules for an organization filtered by category
	GetOrgRulesByCategory(ctx context.Context, arg GetOrgRulesByCategoryParams) ([]OrgRule, error)
	// Get rules with optional category and enabled filters
	GetOrgRulesFiltered(ctx context.Context, arg GetOrgRulesFilteredParams) ([]OrgRule, error)
	GetOrganizationByAPIKey(ctx context.Context, apiKey string) (Organization, error)
	GetOrganizationByID(ctx context.Context, id string) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetOrganizationUsers(ctx context.Context, orgID string) ([]GetOrganizationUsersRow, error)
	GetPendingAuthToken(ctx context.Context, arg GetPendingAuthTokenParams) (AuthToken, error)
	GetPendingCampaignSends(ctx context.Context, limitCount int64) ([]GetPendingCampaignSendsRow, error)
	GetPendingEmails(ctx context.Context, arg GetPendingEmailsParams) ([]GetPendingEmailsRow, error)
	GetPlatformSetting(ctx context.Context, key string) (PlatformSetting, error)
	GetPlatformSettingValue(ctx context.Context, key string) (GetPlatformSettingValueRow, error)
	GetPlatformSettingsByCategory(ctx context.Context, category string) ([]PlatformSetting, error)
	GetPlatformSettingsValues(ctx context.Context, category string) ([]GetPlatformSettingsValuesRow, error)
	// Get a single rule template by ID
	GetRuleTemplateById(ctx context.Context, id string) (RuleTemplate, error)
	// =====================================================
	// Rule Templates
	// =====================================================
	// Get all rule templates
	GetRuleTemplates(ctx context.Context) ([]RuleTemplate, error)
	// Get rule templates filtered by category
	GetRuleTemplatesByCategory(ctx context.Context, category string) ([]RuleTemplate, error)
	// Get rules that need revalidation (hash doesn't match content)
	GetRulesWithStaleValidation(ctx context.Context, orgID string) ([]OrgRule, error)
	GetScheduledCampaigns(ctx context.Context) ([]EmailCampaign, error)
	GetSequenceByID(ctx context.Context, id string) (GetSequenceByIDRow, error)
	GetSequenceByListAndSlug(ctx context.Context, arg GetSequenceByListAndSlugParams) (GetSequenceByListAndSlugRow, error)
	GetSequenceByListAndTrigger(ctx context.Context, arg GetSequenceByListAndTriggerParams) (GetSequenceByListAndTriggerRow, error)
	// SDK Sequence queries
	GetSequenceByOrgAndSlug(ctx context.Context, arg GetSequenceByOrgAndSlugParams) (GetSequenceByOrgAndSlugRow, error)
	GetSequenceStats(ctx context.Context, sequenceID sql.NullString) (GetSequenceStatsRow, error)
	GetSubscriberCampaignActivity(ctx context.Context, contactID string) ([]GetSubscriberCampaignActivityRow, error)
	// Returns field_key -> value pairs for use in email merge tags
	GetSubscriberCustomFieldsForMerge(ctx context.Context, subscriberID string) ([]GetSubscriberCustomFieldsForMergeRow, error)
	GetSubscriberSequenceEnrollments(ctx context.Context, contactID sql.NullString) ([]GetSubscriberSequenceEnrollmentsRow, error)
	GetSuppressedEmail(ctx context.Context, arg GetSuppressedEmailParams) (SuppressionList, error)
	GetTemplateByID(ctx context.Context, id string) (GetTemplateByIDRow, error)
	GetTransactionalEmail(ctx context.Context, arg GetTransactionalEmailParams) (TransactionalEmail, error)
	GetTransactionalEmailBySlug(ctx context.Context, arg GetTransactionalEmailBySlugParams) (TransactionalEmail, error)
	GetTransactionalSend(ctx context.Context, id string) (TransactionalSend, error)
	GetTransactionalSendByTracking(ctx context.Context, trackingToken sql.NullString) (TransactionalSend, error)
	GetTransactionalSendByTrackingAndOrg(ctx context.Context, arg GetTransactionalSendByTrackingAndOrgParams) (GetTransactionalSendByTrackingAndOrgRow, error)
	GetTransactionalSendByTrackingToken(ctx context.Context, token sql.NullString) (GetTransactionalSendByTrackingTokenRow, error)
	GetTransactionalStats(ctx context.Context, templateID string) (GetTransactionalStatsRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserOrganizations(ctx context.Context, userID string) ([]GetUserOrganizationsRow, error)
	GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error)
	GetWebhookByID(ctx context.Context, id string) (Webhook, error)
	GlobalUnsubscribeByOrgAndEmail(ctx context.Context, arg GlobalUnsubscribeByOrgAndEmailParams) error
	HasContactTag(ctx context.Context, arg HasContactTagParams) (int64, error)
	IncrementBlockedDomainAttempts(ctx context.Context, arg IncrementBlockedDomainAttemptsParams) error
	IncrementCampaignClicked(ctx context.Context, id string) error
	IncrementCampaignOpened(ctx context.Context, id string) error
	IncrementCampaignSendRetry(ctx context.Context, id string) error
	IncrementCampaignSent(ctx context.Context, id string) error
	IncrementFailedLogins(ctx context.Context, id string) error
	IncrementSuppressionAttempts(ctx context.Context, arg IncrementSuppressionAttemptsParams) error
	IsDomainBlocked(ctx context.Context, arg IsDomainBlockedParams) (int64, error)
	// ========== COMBINED CHECK ==========
	IsEmailBlocked(ctx context.Context, arg IsEmailBlockedParams) (int64, error)
	IsEmailBounced(ctx context.Context, email string) (int64, error)
	IsEmailComplaint(ctx context.Context, email string) (int64, error)
	// ========== COMBINED BLOCK CHECK (Enhanced) ==========
	IsEmailFullyBlocked(ctx context.Context, arg IsEmailFullyBlockedParams) (int64, error)
	IsEmailSuppressed(ctx context.Context, arg IsEmailSuppressedParams) (int64, error)
	ListActiveAgents(ctx context.Context) ([]ListActiveAgentsRow, error)
	ListAllContactTags(ctx context.Context) ([]ListAllContactTagsRow, error)
	ListAllSequences(ctx context.Context) ([]ListAllSequencesRow, error)
	ListBackups(ctx context.Context, arg ListBackupsParams) ([]BackupHistory, error)
	ListBlockedDomains(ctx context.Context, arg ListBlockedDomainsParams) ([]BlockedDomain, error)
	ListCampaignClicks(ctx context.Context, arg ListCampaignClicksParams) ([]ListCampaignClicksRow, error)
	ListCampaignSends(ctx context.Context, arg ListCampaignSendsParams) ([]ListCampaignSendsRow, error)
	ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]EmailCampaign, error)
	ListCampaignsByStatus(ctx context.Context, arg ListCampaignsByStatusParams) ([]EmailCampaign, error)
	ListContactSequenceStatesWithDetails(ctx context.Context, arg ListContactSequenceStatesWithDetailsParams) ([]ListContactSequenceStatesWithDetailsRow, error)
	ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error)
	ListContactsByOrg(ctx context.Context, arg ListContactsByOrgParams) ([]Contact, error)
	ListCustomFieldValuesBySubscriber(ctx context.Context, subscriberID string) ([]ListCustomFieldValuesBySubscriberRow, error)
	ListCustomFieldsByList(ctx context.Context, listID int64) ([]CustomField, error)
	ListDomainIdentitiesByOrg(ctx context.Context, orgID string) ([]DomainIdentity, error)
	ListEmailDesigns(ctx context.Context, orgID string) ([]EmailDesign, error)
	ListEmailDesignsByCategory(ctx context.Context, arg ListEmailDesignsByCategoryParams) ([]EmailDesign, error)
	ListEmailLists(ctx context.Context, orgID string) ([]EmailList, error)
	ListEmailQueueByOrg(ctx context.Context, arg ListEmailQueueByOrgParams) ([]ListEmailQueueByOrgRow, error)
	ListEntryRulesByList(ctx context.Context, sourceID string) ([]ListEntryRulesByListRow, error)
	ListEntryRulesBySequence(ctx context.Context, sequenceID string) ([]ListEntryRulesBySequenceRow, error)
	ListImportJobs(ctx context.Context, arg ListImportJobsParams) ([]ImportJob, error)
	ListListSubscribers(ctx context.Context, arg ListListSubscribersParams) ([]ListListSubscribersRow, error)
	ListMCPAPIKeysByUser(ctx context.Context, userID string) ([]McpApiKey, error)
	ListMCPOAuthClients(ctx context.Context) ([]McpOauthClient, error)
	ListOrganizations(ctx context.Context) ([]Organization, error)
	ListPendingDomainIdentities(ctx context.Context) ([]DomainIdentity, error)
	ListPendingImportJobs(ctx context.Context) ([]ImportJob, error)
	ListPlatformSettings(ctx context.Context) ([]PlatformSetting, error)
	ListRecentBounces(ctx context.Context, arg ListRecentBouncesParams) ([]EmailBounce, error)
	ListRecentComplaints(ctx context.Context, arg ListRecentComplaintsParams) ([]EmailComplaint, error)
	ListSequencesByList(ctx context.Context, listID sql.NullInt64) ([]ListSequencesByListRow, error)
	ListSequencesByOrg(ctx context.Context, orgID sql.NullString) ([]ListSequencesByOrgRow, error)
	ListSuppressedEmails(ctx context.Context, arg ListSuppressedEmailsParams) ([]SuppressionList, error)
	ListTemplatesBySequence(ctx context.Context, sequenceID sql.NullString) ([]ListTemplatesBySequenceRow, error)
	ListTransactionalEmails(ctx context.Context, orgID string) ([]TransactionalEmail, error)
	ListTransactionalSends(ctx context.Context, arg ListTransactionalSendsParams) ([]TransactionalSend, error)
	ListTransactionalSendsByOrg(ctx context.Context, arg ListTransactionalSendsByOrgParams) ([]ListTransactionalSendsByOrgRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	ListWebhookLogs(ctx context.Context, arg ListWebhookLogsParams) ([]WebhookLog, error)
	ListWebhooks(ctx context.Context, orgID string) ([]Webhook, error)
	// =====================================================
	// Automation Log
	// =====================================================
	// Log a rule execution (idempotent - skips if already processed)
	LogAutomation(ctx context.Context, arg LogAutomationParams) (AutomationLog, error)
	ManuallyVerifyContact(ctx context.Context, id string) error
	MarkAuthTokenUsed(ctx context.Context, id string) error
	MarkCampaignSendFailed(ctx context.Context, arg MarkCampaignSendFailedParams) error
	MarkCampaignSendPermanentlyFailed(ctx context.Context, id string) error
	MarkCampaignSendSent(ctx context.Context, id string) error
	MarkEmailFailed(ctx context.Context, arg MarkEmailFailedParams) error
	MarkEmailSent(ctx context.Context, id string) error
	MarkMCPOAuthCodeUsed(ctx context.Context, id string) error
	PauseContactSequence(ctx context.Context, arg PauseContactSequenceParams) error
	QueueEmail(ctx context.Context, arg QueueEmailParams) (EmailQueue, error)
	// Email tracking queries
	QueueEmailWithTracking(ctx context.Context, arg QueueEmailWithTrackingParams) (EmailQueue, error)
	RecordCampaignClick(ctx context.Context, id string) error
	RecordCampaignOpen(ctx context.Context, id string) error
	RecordEmailClick(ctx context.Context, id string) error
	RecordEmailOpen(ctx context.Context, id string) error
	RecordTransactionalClick(ctx context.Context, id string) error
	RecordTransactionalOpen(ctx context.Context, id string) error
	RegenerateAPIKey(ctx context.Context, arg RegenerateAPIKeyParams) (Organization, error)
	RemoveContactTag(ctx context.Context, arg RemoveContactTagParams) error
	RemoveSubscriberFromList(ctx context.Context, arg RemoveSubscriberFromListParams) error
	RemoveUserFromOrganization(ctx context.Context, arg RemoveUserFromOrganizationParams) error
	ResetFailedLogins(ctx context.Context, id string) error
	ResubscribeContact(ctx context.Context, id string) error
	ResumeContactSequence(ctx context.Context, arg ResumeContactSequenceParams) error
	RevokeMCPAPIKey(ctx context.Context, id string) error
	RevokeMCPOAuthToken(ctx context.Context, id string) error
	RevokeMCPOAuthTokensByUser(ctx context.Context, userID string) error
	ScheduleCampaign(ctx context.Context, arg ScheduleCampaignParams) (EmailCampaign, error)
	SetCampaignRecipientsCount(ctx context.Context, arg SetCampaignRecipientsCountParams) error
	SetContactVerificationToken(ctx context.Context, arg SetContactVerificationTokenParams) error
	SetImportJobErrors(ctx context.Context, arg SetImportJobErrorsParams) error
	SetImportJobTotalRows(ctx context.Context, arg SetImportJobTotalRowsParams) error
	SetUserEmailVerified(ctx context.Context, id string) error
	SubscribeToList(ctx context.Context, arg SubscribeToListParams) (ListSubscriber, error)
	SubscribeToListPending(ctx context.Context, arg SubscribeToListPendingParams) (ListSubscriber, error)
	// Toggle enabled state of a rule
	ToggleOrgRule(ctx context.Context, arg ToggleOrgRuleParams) (OrgRule, error)
	UnblockContact(ctx context.Context, id string) error
	UnsubscribeContact(ctx context.Context, id string) error
	UnsubscribeContactFromSequence(ctx context.Context, contactID sql.NullString) error
	UnsubscribeFromList(ctx context.Context, arg UnsubscribeFromListParams) error
	UpdateBackupComplete(ctx context.Context, arg UpdateBackupCompleteParams) (BackupHistory, error)
	UpdateBackupS3Key(ctx context.Context, arg UpdateBackupS3KeyParams) error
	UpdateBackupStatus(ctx context.Context, arg UpdateBackupStatusParams) (BackupHistory, error)
	UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (EmailCampaign, error)
	UpdateCampaignSendStatus(ctx context.Context, arg UpdateCampaignSendStatusParams) error
	UpdateCampaignStats(ctx context.Context, arg UpdateCampaignStatsParams) error
	UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) (EmailCampaign, error)
	UpdateCampaignStatusByID(ctx context.Context, arg UpdateCampaignStatusByIDParams) error
	UpdateContactGDPR(ctx context.Context, arg UpdateContactGDPRParams) error
	UpdateContactName(ctx context.Context, arg UpdateContactNameParams) error
	UpdateContactSequencePosition(ctx context.Context, arg UpdateContactSequencePositionParams) error
	UpdateContactStatus(ctx context.Context, arg UpdateContactStatusParams) error
	UpdateCustomField(ctx context.Context, arg UpdateCustomFieldParams) (CustomField, error)
	UpdateDomainIdentityDNSRecords(ctx context.Context, arg UpdateDomainIdentityDNSRecordsParams) (DomainIdentity, error)
	UpdateDomainIdentityMailFrom(ctx context.Context, arg UpdateDomainIdentityMailFromParams) (DomainIdentity, error)
	UpdateDomainIdentityStatus(ctx context.Context, arg UpdateDomainIdentityStatusParams) (DomainIdentity, error)
	UpdateEmailDesign(ctx context.Context, arg UpdateEmailDesignParams) (EmailDesign, error)
	UpdateEmailList(ctx context.Context, arg UpdateEmailListParams) (EmailList, error)
	UpdateEntryRule(ctx context.Context, arg UpdateEntryRuleParams) error
	UpdateImportJobProgress(ctx context.Context, arg UpdateImportJobProgressParams) error
	UpdateImportJobStatus(ctx context.Context, arg UpdateImportJobStatusParams) error
	UpdateLastLogin(ctx context.Context, id string) error
	UpdateListPublicPageSettings(ctx context.Context, arg UpdateListPublicPageSettingsParams) error
	UpdateMCPAPIKeyLastUsed(ctx context.Context, id string) error
	UpdateMCPOAuthClient(ctx context.Context, arg UpdateMCPOAuthClientParams) (McpOauthClient, error)
	UpdateOrgEmailSettings(ctx context.Context, arg UpdateOrgEmailSettingsParams) (Organization, error)
	// Update an existing rule
	UpdateOrgRule(ctx context.Context, arg UpdateOrgRuleParams) (OrgRule, error)
	UpdateOrgSettings(ctx context.Context, arg UpdateOrgSettingsParams) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	// Update a rule template
	UpdateRuleTemplate(ctx context.Context, arg UpdateRuleTemplateParams) (RuleTemplate, error)
	// Update just the validation fields (after recompiling)
	UpdateRuleValidation(ctx context.Context, arg UpdateRuleValidationParams) error
	UpdateSDKContact(ctx context.Context, arg UpdateSDKContactParams) (Contact, error)
	UpdateSequence(ctx context.Context, arg UpdateSequenceParams) error
	UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) error
	UpdateTransactionalEmail(ctx context.Context, arg UpdateTransactionalEmailParams) (TransactionalEmail, error)
	UpdateTransactionalSendStatus(ctx context.Context, arg UpdateTransactionalSendStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error)
	UpdateWebhookDeliveryStats(ctx context.Context, arg UpdateWebhookDeliveryStatsParams) error
	UpsertCustomFieldValue(ctx context.Context, arg UpsertCustomFieldValueParams) (CustomFieldValue, error)
	// MCP Sessions (for persisting org selection across server restarts)
	UpsertMCPSession(ctx context.Context, arg UpsertMCPSessionParams) error
	UpsertPlatformSetting(ctx context.Context, arg UpsertPlatformSettingParams) (PlatformSetting, error)
	VerifyContact(ctx context.Context, id string) error
	VerifyContactEmail(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
