// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactional_emails.sql

package db

import (
	"context"
	"database/sql"
)

const countTransactionalEmails = `-- name: CountTransactionalEmails :one
SELECT COUNT(*) as count FROM transactional_emails
WHERE org_id = ?1
`

func (q *Queries) CountTransactionalEmails(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionalEmails, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactionalSends = `-- name: CountTransactionalSends :one
SELECT COUNT(*) as count FROM transactional_sends
WHERE template_id = ?1
`

func (q *Queries) CountTransactionalSends(ctx context.Context, templateID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactionalSends, templateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransactionalEmail = `-- name: CreateTransactionalEmail :one


INSERT INTO transactional_emails (
    id, org_id, design_id, name, slug, description,
    subject, html_body, plain_text,
    from_name, from_email, reply_to, is_active,
    created_at, updated_at
)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, datetime('now'), datetime('now'))
RETURNING id, org_id, design_id, name, slug, description, subject, html_body, plain_text, from_name, from_email, reply_to, is_active, created_at, updated_at
`

type CreateTransactionalEmailParams struct {
	ID          string         `json:"id"`
	OrgID       string         `json:"org_id"`
	DesignID    sql.NullInt64  `json:"design_id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	Subject     string         `json:"subject"`
	HtmlBody    string         `json:"html_body"`
	PlainText   sql.NullString `json:"plain_text"`
	FromName    sql.NullString `json:"from_name"`
	FromEmail   sql.NullString `json:"from_email"`
	ReplyTo     sql.NullString `json:"reply_to"`
	IsActive    sql.NullInt64  `json:"is_active"`
}

// Transactional Emails
// API-triggered transactional email templates and sends
// Templates
func (q *Queries) CreateTransactionalEmail(ctx context.Context, arg CreateTransactionalEmailParams) (TransactionalEmail, error) {
	row := q.db.QueryRowContext(ctx, createTransactionalEmail,
		arg.ID,
		arg.OrgID,
		arg.DesignID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Subject,
		arg.HtmlBody,
		arg.PlainText,
		arg.FromName,
		arg.FromEmail,
		arg.ReplyTo,
		arg.IsActive,
	)
	var i TransactionalEmail
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DesignID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Subject,
		&i.HtmlBody,
		&i.PlainText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransactionalSend = `-- name: CreateTransactionalSend :one

INSERT INTO transactional_sends (
    id, template_id, org_id, to_email, to_name, contact_id,
    status, tracking_token, context_data, created_at
)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, datetime('now'))
RETURNING id, template_id, org_id, to_email, to_name, contact_id, status, sent_at, delivered_at, tracking_token, opened_at, clicked_at, context_data, error_message, created_at
`

type CreateTransactionalSendParams struct {
	ID            string         `json:"id"`
	TemplateID    string         `json:"template_id"`
	OrgID         string         `json:"org_id"`
	ToEmail       string         `json:"to_email"`
	ToName        sql.NullString `json:"to_name"`
	ContactID     sql.NullString `json:"contact_id"`
	Status        sql.NullString `json:"status"`
	TrackingToken sql.NullString `json:"tracking_token"`
	ContextData   sql.NullString `json:"context_data"`
}

// Sends (Logging)
func (q *Queries) CreateTransactionalSend(ctx context.Context, arg CreateTransactionalSendParams) (TransactionalSend, error) {
	row := q.db.QueryRowContext(ctx, createTransactionalSend,
		arg.ID,
		arg.TemplateID,
		arg.OrgID,
		arg.ToEmail,
		arg.ToName,
		arg.ContactID,
		arg.Status,
		arg.TrackingToken,
		arg.ContextData,
	)
	var i TransactionalSend
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.OrgID,
		&i.ToEmail,
		&i.ToName,
		&i.ContactID,
		&i.Status,
		&i.SentAt,
		&i.DeliveredAt,
		&i.TrackingToken,
		&i.OpenedAt,
		&i.ClickedAt,
		&i.ContextData,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransactionalEmail = `-- name: DeleteTransactionalEmail :exec
DELETE FROM transactional_emails
WHERE id = ?1 AND org_id = ?2
`

type DeleteTransactionalEmailParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteTransactionalEmail(ctx context.Context, arg DeleteTransactionalEmailParams) error {
	_, err := q.db.ExecContext(ctx, deleteTransactionalEmail, arg.ID, arg.OrgID)
	return err
}

const getTransactionalEmail = `-- name: GetTransactionalEmail :one
SELECT id, org_id, design_id, name, slug, description, subject, html_body, plain_text, from_name, from_email, reply_to, is_active, created_at, updated_at FROM transactional_emails
WHERE id = ?1 AND org_id = ?2
`

type GetTransactionalEmailParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetTransactionalEmail(ctx context.Context, arg GetTransactionalEmailParams) (TransactionalEmail, error) {
	row := q.db.QueryRowContext(ctx, getTransactionalEmail, arg.ID, arg.OrgID)
	var i TransactionalEmail
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DesignID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Subject,
		&i.HtmlBody,
		&i.PlainText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionalEmailBySlug = `-- name: GetTransactionalEmailBySlug :one
SELECT id, org_id, design_id, name, slug, description, subject, html_body, plain_text, from_name, from_email, reply_to, is_active, created_at, updated_at FROM transactional_emails
WHERE slug = ?1 AND org_id = ?2
`

type GetTransactionalEmailBySlugParams struct {
	Slug  string `json:"slug"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetTransactionalEmailBySlug(ctx context.Context, arg GetTransactionalEmailBySlugParams) (TransactionalEmail, error) {
	row := q.db.QueryRowContext(ctx, getTransactionalEmailBySlug, arg.Slug, arg.OrgID)
	var i TransactionalEmail
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DesignID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Subject,
		&i.HtmlBody,
		&i.PlainText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionalSend = `-- name: GetTransactionalSend :one
SELECT id, template_id, org_id, to_email, to_name, contact_id, status, sent_at, delivered_at, tracking_token, opened_at, clicked_at, context_data, error_message, created_at FROM transactional_sends
WHERE id = ?1
`

func (q *Queries) GetTransactionalSend(ctx context.Context, id string) (TransactionalSend, error) {
	row := q.db.QueryRowContext(ctx, getTransactionalSend, id)
	var i TransactionalSend
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.OrgID,
		&i.ToEmail,
		&i.ToName,
		&i.ContactID,
		&i.Status,
		&i.SentAt,
		&i.DeliveredAt,
		&i.TrackingToken,
		&i.OpenedAt,
		&i.ClickedAt,
		&i.ContextData,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionalSendByTracking = `-- name: GetTransactionalSendByTracking :one
SELECT id, template_id, org_id, to_email, to_name, contact_id, status, sent_at, delivered_at, tracking_token, opened_at, clicked_at, context_data, error_message, created_at FROM transactional_sends
WHERE tracking_token = ?1
`

func (q *Queries) GetTransactionalSendByTracking(ctx context.Context, trackingToken sql.NullString) (TransactionalSend, error) {
	row := q.db.QueryRowContext(ctx, getTransactionalSendByTracking, trackingToken)
	var i TransactionalSend
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.OrgID,
		&i.ToEmail,
		&i.ToName,
		&i.ContactID,
		&i.Status,
		&i.SentAt,
		&i.DeliveredAt,
		&i.TrackingToken,
		&i.OpenedAt,
		&i.ClickedAt,
		&i.ContextData,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionalSendByTrackingAndOrg = `-- name: GetTransactionalSendByTrackingAndOrg :one
SELECT ts.id, ts.template_id, ts.org_id, ts.to_email, ts.to_name, ts.contact_id, ts.status, ts.sent_at, ts.delivered_at, ts.tracking_token, ts.opened_at, ts.clicked_at, ts.context_data, ts.error_message, ts.created_at, te.subject
FROM transactional_sends ts
JOIN transactional_emails te ON ts.template_id = te.id
WHERE ts.tracking_token = ?1 AND ts.org_id = ?2
`

type GetTransactionalSendByTrackingAndOrgParams struct {
	TrackingToken sql.NullString `json:"tracking_token"`
	OrgID         string         `json:"org_id"`
}

type GetTransactionalSendByTrackingAndOrgRow struct {
	ID            string         `json:"id"`
	TemplateID    string         `json:"template_id"`
	OrgID         string         `json:"org_id"`
	ToEmail       string         `json:"to_email"`
	ToName        sql.NullString `json:"to_name"`
	ContactID     sql.NullString `json:"contact_id"`
	Status        sql.NullString `json:"status"`
	SentAt        sql.NullString `json:"sent_at"`
	DeliveredAt   sql.NullString `json:"delivered_at"`
	TrackingToken sql.NullString `json:"tracking_token"`
	OpenedAt      sql.NullString `json:"opened_at"`
	ClickedAt     sql.NullString `json:"clicked_at"`
	ContextData   sql.NullString `json:"context_data"`
	ErrorMessage  sql.NullString `json:"error_message"`
	CreatedAt     sql.NullString `json:"created_at"`
	Subject       string         `json:"subject"`
}

func (q *Queries) GetTransactionalSendByTrackingAndOrg(ctx context.Context, arg GetTransactionalSendByTrackingAndOrgParams) (GetTransactionalSendByTrackingAndOrgRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionalSendByTrackingAndOrg, arg.TrackingToken, arg.OrgID)
	var i GetTransactionalSendByTrackingAndOrgRow
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.OrgID,
		&i.ToEmail,
		&i.ToName,
		&i.ContactID,
		&i.Status,
		&i.SentAt,
		&i.DeliveredAt,
		&i.TrackingToken,
		&i.OpenedAt,
		&i.ClickedAt,
		&i.ContextData,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.Subject,
	)
	return i, err
}

const getTransactionalStats = `-- name: GetTransactionalStats :one
SELECT
    COUNT(*) as total,
    SUM(CASE WHEN status = 'sent' OR status = 'delivered' THEN 1 ELSE 0 END) as sent,
    SUM(CASE WHEN status = 'delivered' THEN 1 ELSE 0 END) as delivered,
    SUM(CASE WHEN opened_at IS NOT NULL THEN 1 ELSE 0 END) as opened,
    SUM(CASE WHEN clicked_at IS NOT NULL THEN 1 ELSE 0 END) as clicked,
    SUM(CASE WHEN status = 'bounced' THEN 1 ELSE 0 END) as bounced,
    SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END) as failed
FROM transactional_sends
WHERE template_id = ?1
`

type GetTransactionalStatsRow struct {
	Total     int64           `json:"total"`
	Sent      sql.NullFloat64 `json:"sent"`
	Delivered sql.NullFloat64 `json:"delivered"`
	Opened    sql.NullFloat64 `json:"opened"`
	Clicked   sql.NullFloat64 `json:"clicked"`
	Bounced   sql.NullFloat64 `json:"bounced"`
	Failed    sql.NullFloat64 `json:"failed"`
}

func (q *Queries) GetTransactionalStats(ctx context.Context, templateID string) (GetTransactionalStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getTransactionalStats, templateID)
	var i GetTransactionalStatsRow
	err := row.Scan(
		&i.Total,
		&i.Sent,
		&i.Delivered,
		&i.Opened,
		&i.Clicked,
		&i.Bounced,
		&i.Failed,
	)
	return i, err
}

const listTransactionalEmails = `-- name: ListTransactionalEmails :many
SELECT id, org_id, design_id, name, slug, description, subject, html_body, plain_text, from_name, from_email, reply_to, is_active, created_at, updated_at FROM transactional_emails
WHERE org_id = ?1
ORDER BY created_at DESC
`

func (q *Queries) ListTransactionalEmails(ctx context.Context, orgID string) ([]TransactionalEmail, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionalEmails, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionalEmail
	for rows.Next() {
		var i TransactionalEmail
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.DesignID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Subject,
			&i.HtmlBody,
			&i.PlainText,
			&i.FromName,
			&i.FromEmail,
			&i.ReplyTo,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionalSends = `-- name: ListTransactionalSends :many
SELECT id, template_id, org_id, to_email, to_name, contact_id, status, sent_at, delivered_at, tracking_token, opened_at, clicked_at, context_data, error_message, created_at FROM transactional_sends
WHERE template_id = ?1
ORDER BY created_at DESC
LIMIT ?3 OFFSET ?2
`

type ListTransactionalSendsParams struct {
	TemplateID string `json:"template_id"`
	PageOffset int64  `json:"page_offset"`
	PageSize   int64  `json:"page_size"`
}

func (q *Queries) ListTransactionalSends(ctx context.Context, arg ListTransactionalSendsParams) ([]TransactionalSend, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionalSends, arg.TemplateID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionalSend
	for rows.Next() {
		var i TransactionalSend
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.OrgID,
			&i.ToEmail,
			&i.ToName,
			&i.ContactID,
			&i.Status,
			&i.SentAt,
			&i.DeliveredAt,
			&i.TrackingToken,
			&i.OpenedAt,
			&i.ClickedAt,
			&i.ContextData,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionalSendsByOrg = `-- name: ListTransactionalSendsByOrg :many
SELECT ts.id, ts.template_id, ts.org_id, ts.to_email, ts.to_name, ts.contact_id, ts.status, ts.sent_at, ts.delivered_at, ts.tracking_token, ts.opened_at, ts.clicked_at, ts.context_data, ts.error_message, ts.created_at, te.name as template_name, te.slug as template_slug
FROM transactional_sends ts
JOIN transactional_emails te ON ts.template_id = te.id
WHERE ts.org_id = ?1
ORDER BY ts.created_at DESC
LIMIT ?3 OFFSET ?2
`

type ListTransactionalSendsByOrgParams struct {
	OrgID      string `json:"org_id"`
	PageOffset int64  `json:"page_offset"`
	PageSize   int64  `json:"page_size"`
}

type ListTransactionalSendsByOrgRow struct {
	ID            string         `json:"id"`
	TemplateID    string         `json:"template_id"`
	OrgID         string         `json:"org_id"`
	ToEmail       string         `json:"to_email"`
	ToName        sql.NullString `json:"to_name"`
	ContactID     sql.NullString `json:"contact_id"`
	Status        sql.NullString `json:"status"`
	SentAt        sql.NullString `json:"sent_at"`
	DeliveredAt   sql.NullString `json:"delivered_at"`
	TrackingToken sql.NullString `json:"tracking_token"`
	OpenedAt      sql.NullString `json:"opened_at"`
	ClickedAt     sql.NullString `json:"clicked_at"`
	ContextData   sql.NullString `json:"context_data"`
	ErrorMessage  sql.NullString `json:"error_message"`
	CreatedAt     sql.NullString `json:"created_at"`
	TemplateName  string         `json:"template_name"`
	TemplateSlug  string         `json:"template_slug"`
}

func (q *Queries) ListTransactionalSendsByOrg(ctx context.Context, arg ListTransactionalSendsByOrgParams) ([]ListTransactionalSendsByOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionalSendsByOrg, arg.OrgID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionalSendsByOrgRow
	for rows.Next() {
		var i ListTransactionalSendsByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.OrgID,
			&i.ToEmail,
			&i.ToName,
			&i.ContactID,
			&i.Status,
			&i.SentAt,
			&i.DeliveredAt,
			&i.TrackingToken,
			&i.OpenedAt,
			&i.ClickedAt,
			&i.ContextData,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.TemplateName,
			&i.TemplateSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTransactionalClick = `-- name: RecordTransactionalClick :exec
UPDATE transactional_sends
SET clicked_at = COALESCE(clicked_at, datetime('now'))
WHERE id = ?1
`

func (q *Queries) RecordTransactionalClick(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, recordTransactionalClick, id)
	return err
}

const recordTransactionalOpen = `-- name: RecordTransactionalOpen :exec
UPDATE transactional_sends
SET opened_at = COALESCE(opened_at, datetime('now'))
WHERE id = ?1
`

func (q *Queries) RecordTransactionalOpen(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, recordTransactionalOpen, id)
	return err
}

const updateTransactionalEmail = `-- name: UpdateTransactionalEmail :one
UPDATE transactional_emails
SET name = COALESCE(NULLIF(?1, ''), name),
    slug = COALESCE(NULLIF(?2, ''), slug),
    description = COALESCE(NULLIF(?3, ''), description),
    subject = COALESCE(NULLIF(?4, ''), subject),
    html_body = COALESCE(NULLIF(?5, ''), html_body),
    plain_text = COALESCE(NULLIF(?6, ''), plain_text),
    from_name = COALESCE(NULLIF(?7, ''), from_name),
    from_email = COALESCE(NULLIF(?8, ''), from_email),
    reply_to = COALESCE(NULLIF(?9, ''), reply_to),
    is_active = COALESCE(?10, is_active),
    updated_at = datetime('now')
WHERE id = ?11 AND org_id = ?12
RETURNING id, org_id, design_id, name, slug, description, subject, html_body, plain_text, from_name, from_email, reply_to, is_active, created_at, updated_at
`

type UpdateTransactionalEmailParams struct {
	Name        interface{}   `json:"name"`
	Slug        interface{}   `json:"slug"`
	Description interface{}   `json:"description"`
	Subject     interface{}   `json:"subject"`
	HtmlBody    interface{}   `json:"html_body"`
	PlainText   interface{}   `json:"plain_text"`
	FromName    interface{}   `json:"from_name"`
	FromEmail   interface{}   `json:"from_email"`
	ReplyTo     interface{}   `json:"reply_to"`
	IsActive    sql.NullInt64 `json:"is_active"`
	ID          string        `json:"id"`
	OrgID       string        `json:"org_id"`
}

func (q *Queries) UpdateTransactionalEmail(ctx context.Context, arg UpdateTransactionalEmailParams) (TransactionalEmail, error) {
	row := q.db.QueryRowContext(ctx, updateTransactionalEmail,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Subject,
		arg.HtmlBody,
		arg.PlainText,
		arg.FromName,
		arg.FromEmail,
		arg.ReplyTo,
		arg.IsActive,
		arg.ID,
		arg.OrgID,
	)
	var i TransactionalEmail
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.DesignID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Subject,
		&i.HtmlBody,
		&i.PlainText,
		&i.FromName,
		&i.FromEmail,
		&i.ReplyTo,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransactionalSendStatus = `-- name: UpdateTransactionalSendStatus :exec
UPDATE transactional_sends
SET status = ?1,
    sent_at = CASE WHEN ?1 = 'sent' THEN datetime('now') ELSE sent_at END,
    delivered_at = CASE WHEN ?1 = 'delivered' THEN datetime('now') ELSE delivered_at END,
    error_message = ?2
WHERE id = ?3
`

type UpdateTransactionalSendStatusParams struct {
	Status       sql.NullString `json:"status"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) UpdateTransactionalSendStatus(ctx context.Context, arg UpdateTransactionalSendStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionalSendStatus, arg.Status, arg.ErrorMessage, arg.ID)
	return err
}
