// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package db

import (
	"context"
	"database/sql"
)

const countWebhookLogs = `-- name: CountWebhookLogs :one
SELECT COUNT(*) as count FROM webhook_logs
WHERE webhook_id = ?1
`

func (q *Queries) CountWebhookLogs(ctx context.Context, webhookID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWebhookLogs, webhookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (id, org_id, url, secret, events, active, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, datetime('now'), datetime('now'))
RETURNING id, org_id, url, secret, events, active, deliveries_total, deliveries_success, deliveries_failed, last_delivery_at, last_status, created_at, updated_at
`

type CreateWebhookParams struct {
	ID     string        `json:"id"`
	OrgID  string        `json:"org_id"`
	Url    string        `json:"url"`
	Secret string        `json:"secret"`
	Events string        `json:"events"`
	Active sql.NullInt64 `json:"active"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, createWebhook,
		arg.ID,
		arg.OrgID,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.Active,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.DeliveriesTotal,
		&i.DeliveriesSuccess,
		&i.DeliveriesFailed,
		&i.LastDeliveryAt,
		&i.LastStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookLog = `-- name: CreateWebhookLog :one
INSERT INTO webhook_logs (id, webhook_id, event, payload, status_code, response, error, duration_ms, delivered_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, datetime('now'))
RETURNING id, webhook_id, event, payload, status_code, response, error, duration_ms, delivered_at
`

type CreateWebhookLogParams struct {
	ID         string         `json:"id"`
	WebhookID  string         `json:"webhook_id"`
	Event      string         `json:"event"`
	Payload    string         `json:"payload"`
	StatusCode sql.NullInt64  `json:"status_code"`
	Response   sql.NullString `json:"response"`
	Error      sql.NullString `json:"error"`
	DurationMs sql.NullInt64  `json:"duration_ms"`
}

func (q *Queries) CreateWebhookLog(ctx context.Context, arg CreateWebhookLogParams) (WebhookLog, error) {
	row := q.db.QueryRowContext(ctx, createWebhookLog,
		arg.ID,
		arg.WebhookID,
		arg.Event,
		arg.Payload,
		arg.StatusCode,
		arg.Response,
		arg.Error,
		arg.DurationMs,
	)
	var i WebhookLog
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.Event,
		&i.Payload,
		&i.StatusCode,
		&i.Response,
		&i.Error,
		&i.DurationMs,
		&i.DeliveredAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks
WHERE id = ?1 AND org_id = ?2
`

type DeleteWebhookParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) DeleteWebhook(ctx context.Context, arg DeleteWebhookParams) error {
	_, err := q.db.ExecContext(ctx, deleteWebhook, arg.ID, arg.OrgID)
	return err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, org_id, url, secret, events, active, deliveries_total, deliveries_success, deliveries_failed, last_delivery_at, last_status, created_at, updated_at FROM webhooks
WHERE id = ?1 AND org_id = ?2
`

type GetWebhookParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) GetWebhook(ctx context.Context, arg GetWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhook, arg.ID, arg.OrgID)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.DeliveriesTotal,
		&i.DeliveriesSuccess,
		&i.DeliveriesFailed,
		&i.LastDeliveryAt,
		&i.LastStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, org_id, url, secret, events, active, deliveries_total, deliveries_success, deliveries_failed, last_delivery_at, last_status, created_at, updated_at FROM webhooks
WHERE id = ?1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id string) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.DeliveriesTotal,
		&i.DeliveriesSuccess,
		&i.DeliveriesFailed,
		&i.LastDeliveryAt,
		&i.LastStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhookLogs = `-- name: ListWebhookLogs :many
SELECT id, webhook_id, event, payload, status_code, response, error, duration_ms, delivered_at FROM webhook_logs
WHERE webhook_id = ?1
ORDER BY delivered_at DESC
LIMIT ?2
`

type ListWebhookLogsParams struct {
	WebhookID  string `json:"webhook_id"`
	LimitCount int64  `json:"limit_count"`
}

func (q *Queries) ListWebhookLogs(ctx context.Context, arg ListWebhookLogsParams) ([]WebhookLog, error) {
	rows, err := q.db.QueryContext(ctx, listWebhookLogs, arg.WebhookID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookLog
	for rows.Next() {
		var i WebhookLog
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.Payload,
			&i.StatusCode,
			&i.Response,
			&i.Error,
			&i.DurationMs,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, org_id, url, secret, events, active, deliveries_total, deliveries_success, deliveries_failed, last_delivery_at, last_status, created_at, updated_at FROM webhooks
WHERE org_id = ?1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhooks(ctx context.Context, orgID string) ([]Webhook, error) {
	rows, err := q.db.QueryContext(ctx, listWebhooks, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Webhook
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Active,
			&i.DeliveriesTotal,
			&i.DeliveriesSuccess,
			&i.DeliveriesFailed,
			&i.LastDeliveryAt,
			&i.LastStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks
SET url = COALESCE(NULLIF(?1, ''), url),
    events = COALESCE(NULLIF(?2, ''), events),
    active = ?3,
    updated_at = datetime('now')
WHERE id = ?4 AND org_id = ?5
RETURNING id, org_id, url, secret, events, active, deliveries_total, deliveries_success, deliveries_failed, last_delivery_at, last_status, created_at, updated_at
`

type UpdateWebhookParams struct {
	Url    interface{}   `json:"url"`
	Events interface{}   `json:"events"`
	Active sql.NullInt64 `json:"active"`
	ID     string        `json:"id"`
	OrgID  string        `json:"org_id"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRowContext(ctx, updateWebhook,
		arg.Url,
		arg.Events,
		arg.Active,
		arg.ID,
		arg.OrgID,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Active,
		&i.DeliveriesTotal,
		&i.DeliveriesSuccess,
		&i.DeliveriesFailed,
		&i.LastDeliveryAt,
		&i.LastStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookDeliveryStats = `-- name: UpdateWebhookDeliveryStats :exec
UPDATE webhooks
SET deliveries_total = deliveries_total + 1,
    deliveries_success = CASE WHEN ?1 = 1 THEN deliveries_success + 1 ELSE deliveries_success END,
    deliveries_failed = CASE WHEN ?1 = 0 THEN deliveries_failed + 1 ELSE deliveries_failed END,
    last_delivery_at = datetime('now'),
    last_status = ?2
WHERE id = ?3
`

type UpdateWebhookDeliveryStatsParams struct {
	Success    interface{}   `json:"success"`
	LastStatus sql.NullInt64 `json:"last_status"`
	ID         string        `json:"id"`
}

func (q *Queries) UpdateWebhookDeliveryStats(ctx context.Context, arg UpdateWebhookDeliveryStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateWebhookDeliveryStats, arg.Success, arg.LastStatus, arg.ID)
	return err
}
